syntax = "proto3";

package dev.planton.azure.azuremanagedredis.v1alpha1;

import "catalog/azure/azuremanagedredis/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureManagedRedisIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureManagedRedisIacInput {
  // the catalog object to deploy to be deployed
  AzureManagedRedis target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
