apiVersion: aws.openmcf.org/v1
kind: AwsNatGateway
metadata:
  name: main-nat
spec:
  region: us-west-2
  connectivityType: public
  subnetId:
    valueFrom:
      kind: AwsSubnet
      name: <public-subnet-name>
      fieldPath: status.outputs.subnet_id
  allocationId:
    valueFrom:
      kind: AwsElasticIp
      name: <elastic-ip-name>
      fieldPath: status.outputs.allocation_id
