syntax = "proto3";

package dev.planton.digitalocean.digitaloceandatabasekafkatopic.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceandatabasekafkatopic/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceandatabasekafkatopic/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-database-kafka-topic
message DigitalOceanDatabaseKafkaTopic {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'digital-ocean.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'DigitalOceanDatabaseKafkaTopic'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanDatabaseKafkaTopicSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanDatabaseKafkaTopicStatus status = 5;
}

// digital-ocean-database-kafka-topic status
message DigitalOceanDatabaseKafkaTopicStatus {
  //outputs
  //  digital-ocean-database-kafka-topic outputs
  DigitalOceanDatabaseKafkaTopicOutputs outputs = 1;
}
