apiVersion: aws.planton.dev/v1
kind: AwsFsxOntapVolume
metadata:
  name: <REPLACE>
  id: <REPLACE>
  org: <REPLACE>
  env: <REPLACE>
spec:
  region: <aws-region>
  storage_virtual_machine_id:
    value: svm-0123456789abcdef0
  name: vol_highperf
  size_in_megabytes: 1048576
  junction_path: /highperf
  volume_style: FLEXGROUP
  security_style: UNIX
  storage_efficiency_enabled: true
  tiering_policy:
    name: NONE
  aggregate_configuration:
    aggregates:
      - aggr1
      - aggr2
    constituents_per_aggregate: 8
