apiVersion: aws.planton.dev/v1
kind: AwsDynamodb
metadata:
  name: my-provisioned-table
spec:
  region: <aws-region>
  billingMode: PROVISIONED
  provisionedThroughput:
    readCapacityUnits: 25
    writeCapacityUnits: 25
  attributeDefinitions:
    - name: pk
      type: S
    - name: sk
      type: S
  keySchema:
    - attributeName: pk
      keyType: HASH
    - attributeName: sk
      keyType: RANGE
  pointInTimeRecoveryEnabled: true
  deletionProtectionEnabled: true
  serverSideEncryption:
    enabled: true
