syntax = "proto3";

package dev.planton.azure.azurecontainerappenvironmentdaprcomponent.v1alpha1;

import "catalog/azure/azurecontainerappenvironmentdaprcomponent/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureContainerAppEnvironmentDaprComponentIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureContainerAppEnvironmentDaprComponentIacInput {
  // the catalog object to deploy to be deployed
  AzureContainerAppEnvironmentDaprComponent target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
