// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpnetworkendpointgroup/v1alpha1/api.proto

package gcpnetworkendpointgroupv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-network-endpoint-group
type GcpNetworkEndpointGroup struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ApiVersion    string                         `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                         `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *shared.CloudResourceMetadata  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *GcpNetworkEndpointGroupSpec   `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *GcpNetworkEndpointGroupStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpNetworkEndpointGroup) Reset() {
	*x = GcpNetworkEndpointGroup{}
	mi := &file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpNetworkEndpointGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpNetworkEndpointGroup) ProtoMessage() {}

func (x *GcpNetworkEndpointGroup) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpNetworkEndpointGroup.ProtoReflect.Descriptor instead.
func (*GcpNetworkEndpointGroup) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GcpNetworkEndpointGroup) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GcpNetworkEndpointGroup) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GcpNetworkEndpointGroup) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GcpNetworkEndpointGroup) GetSpec() *GcpNetworkEndpointGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GcpNetworkEndpointGroup) GetStatus() *GcpNetworkEndpointGroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GcpNetworkEndpointGroupStatus struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Outputs       *GcpNetworkEndpointGroupStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpNetworkEndpointGroupStatus) Reset() {
	*x = GcpNetworkEndpointGroupStatus{}
	mi := &file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpNetworkEndpointGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpNetworkEndpointGroupStatus) ProtoMessage() {}

func (x *GcpNetworkEndpointGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpNetworkEndpointGroupStatus.ProtoReflect.Descriptor instead.
func (*GcpNetworkEndpointGroupStatus) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GcpNetworkEndpointGroupStatus) GetOutputs() *GcpNetworkEndpointGroupStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"6catalog/gcp/gcpnetworkendpointgroup/v1alpha1/api.proto\x120dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a:catalog/gcp/gcpnetworkendpointgroup/v1alpha1/outputs.proto\x1a7catalog/gcp/gcpnetworkendpointgroup/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xb2\x03\n" +
	"\x17GcpNetworkEndpointGroup\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18gcp.planton.dev/v1alpha1R\n" +
	"apiVersion\x122\n" +
	"\x04kind\x18\x02 \x01(\tB\x1e\xbaH\x1br\x19\n" +
	"\x17GcpNetworkEndpointGroupR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12i\n" +
	"\x04spec\x18\x04 \x01(\v2M.dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12g\n" +
	"\x06status\x18\x05 \x01(\v2O.dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStatusR\x06status\"\x90\x01\n" +
	"\x1dGcpNetworkEndpointGroupStatus\x12o\n" +
	"\aoutputs\x18\x01 \x01(\v2U.dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStackOutputsR\aoutputsB\x90\x03\n" +
	"4com.dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1B\bApiProtoP\x01Zigithub.com/plantonhq/planton/catalog/gcp/gcpnetworkendpointgroup/v1alpha1;gcpnetworkendpointgroupv1alpha1\xa2\x02\x04DPGG\xaa\x020Dev.Planton.Gcp.Gcpnetworkendpointgroup.V1alpha1\xca\x020Dev\\Planton\\Gcp\\Gcpnetworkendpointgroup\\V1alpha1\xe2\x02<Dev\\Planton\\Gcp\\Gcpnetworkendpointgroup\\V1alpha1\\GPBMetadata\xea\x024Dev::Planton::Gcp::Gcpnetworkendpointgroup::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDescData
}

var file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_goTypes = []any{
	(*GcpNetworkEndpointGroup)(nil),             // 0: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroup
	(*GcpNetworkEndpointGroupStatus)(nil),       // 1: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStatus
	(*shared.CloudResourceMetadata)(nil),        // 2: dev.planton.shared.CloudResourceMetadata
	(*GcpNetworkEndpointGroupSpec)(nil),         // 3: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupSpec
	(*GcpNetworkEndpointGroupStackOutputs)(nil), // 4: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStackOutputs
}
var file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroup.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroup.spec:type_name -> dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupSpec
	1, // 2: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroup.status:type_name -> dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStatus
	4, // 3: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStatus.outputs:type_name -> dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_init() }
func file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_init() {
	if File_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_init()
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto = out.File
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_goTypes = nil
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_api_proto_depIdxs = nil
}
