// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpnetworkendpointgroup/v1alpha1/outputs.proto

package gcpnetworkendpointgroupv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcpNetworkEndpointGroupStackOutputs captures the group after
// provisioning -- above all the self_link a backend service names in its
// backends[].group.
type GcpNetworkEndpointGroupStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Self-link URI of the group: the value a GcpBackendService backend
	// names. A zonal link carries zones/{zone}, a global one says global.
	SelfLink string `protobuf:"bytes,1,opt,name=self_link,json=selfLink,proto3" json:"self_link,omitempty"`
	// Name of the group as it exists in GCP -- the resolved value
	// (metadata.name when the spec left neg_name empty).
	NegName string `protobuf:"bytes,2,opt,name=neg_name,json=negName,proto3" json:"neg_name,omitempty"`
	// Google's unique identifier for the group.
	NegId string `protobuf:"bytes,3,opt,name=neg_id,json=negId,proto3" json:"neg_id,omitempty"`
	// Zone of a zonal group; empty for a global one, so a consumer can tell
	// the scope from the outputs alone.
	Zone string `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	// Number of endpoints declared in the group -- the manifest's list is
	// the whole membership on both scopes.
	Size          string `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpNetworkEndpointGroupStackOutputs) Reset() {
	*x = GcpNetworkEndpointGroupStackOutputs{}
	mi := &file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpNetworkEndpointGroupStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpNetworkEndpointGroupStackOutputs) ProtoMessage() {}

func (x *GcpNetworkEndpointGroupStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpNetworkEndpointGroupStackOutputs.ProtoReflect.Descriptor instead.
func (*GcpNetworkEndpointGroupStackOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *GcpNetworkEndpointGroupStackOutputs) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *GcpNetworkEndpointGroupStackOutputs) GetNegName() string {
	if x != nil {
		return x.NegName
	}
	return ""
}

func (x *GcpNetworkEndpointGroupStackOutputs) GetNegId() string {
	if x != nil {
		return x.NegId
	}
	return ""
}

func (x *GcpNetworkEndpointGroupStackOutputs) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *GcpNetworkEndpointGroupStackOutputs) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

var File_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	":catalog/gcp/gcpnetworkendpointgroup/v1alpha1/outputs.proto\x120dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1\"\x9c\x01\n" +
	"#GcpNetworkEndpointGroupStackOutputs\x12\x1b\n" +
	"\tself_link\x18\x01 \x01(\tR\bselfLink\x12\x19\n" +
	"\bneg_name\x18\x02 \x01(\tR\anegName\x12\x15\n" +
	"\x06neg_id\x18\x03 \x01(\tR\x05negId\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04sizeB\x94\x03\n" +
	"4com.dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1B\fOutputsProtoP\x01Zigithub.com/plantonhq/planton/catalog/gcp/gcpnetworkendpointgroup/v1alpha1;gcpnetworkendpointgroupv1alpha1\xa2\x02\x04DPGG\xaa\x020Dev.Planton.Gcp.Gcpnetworkendpointgroup.V1alpha1\xca\x020Dev\\Planton\\Gcp\\Gcpnetworkendpointgroup\\V1alpha1\xe2\x02<Dev\\Planton\\Gcp\\Gcpnetworkendpointgroup\\V1alpha1\\GPBMetadata\xea\x024Dev::Planton::Gcp::Gcpnetworkendpointgroup::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDesc), len(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_goTypes = []any{
	(*GcpNetworkEndpointGroupStackOutputs)(nil), // 0: dev.planton.gcp.gcpnetworkendpointgroup.v1alpha1.GcpNetworkEndpointGroupStackOutputs
}
var file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_init() }
func file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_init() {
	if File_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDesc), len(file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto = out.File
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_gcp_gcpnetworkendpointgroup_v1alpha1_outputs_proto_depIdxs = nil
}
