syntax = "proto3";

package dev.planton.cloudflare.cloudflarezerotrusttunnelroute.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/cloudflare/cloudflarezerotrusttunnelroute/v1alpha1/outputs.proto";
import "catalog/cloudflare/cloudflarezerotrusttunnelroute/v1alpha1/spec.proto";
import "shared/metadata.proto";

// cloudflare-zero-trust-tunnel-route
message CloudflareZeroTrustTunnelRoute {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'cloudflare.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'CloudflareZeroTrustTunnelRoute'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  CloudflareZeroTrustTunnelRouteSpec spec = 4 [(buf.validate.field).required = true];

  //status
  CloudflareZeroTrustTunnelRouteStatus status = 5;
}

// cloudflare-zero-trust-tunnel-route status
message CloudflareZeroTrustTunnelRouteStatus {
  //outputs
  //  cloudflare-zero-trust-tunnel-route outputs
  CloudflareZeroTrustTunnelRouteOutputs outputs = 1;
}
