syntax = "proto3";

package dev.planton.aws.awsssmassociation.v1alpha1;

import "catalog/aws/awsssmassociation/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSsmAssociationIacInput is the input for the IaC modules that
// manage a State Manager association.
message AwsSsmAssociationIacInput {
  // target is the AwsSsmAssociation resource to deploy.
  AwsSsmAssociation target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
