// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/kubernetes/kubernetessecret/v1/spec.proto

package kubernetessecretv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kubernetes "github.com/plantonhq/planton/apis/dev/planton/provider/kubernetes"
	_ "github.com/plantonhq/planton/apis/dev/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// **KubernetesSecretSpec** defines the configuration for creating and managing a Kubernetes Secret.
// This spec implements a "Secret-as-a-Service" pattern, providing type-safe configuration for all
// common Kubernetes secret types while keeping values as plain strings matching the Kubernetes API.
//
// The type-safe oneof design ensures that exactly one secret type is configured per resource,
// with type-specific fields and validations for each variant.
type KubernetesSecretSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Kubernetes cluster in which the secret should be created.
	TargetCluster *kubernetes.KubernetesClusterSelector `protobuf:"bytes,1,opt,name=target_cluster,json=targetCluster,proto3" json:"target_cluster,omitempty"`
	// *
	// The name of the Kubernetes Secret.
	// Must be a valid DNS subdomain name (lowercase alphanumeric, hyphens, and dots).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// The namespace where the secret will be created.
	// Default: default
	Namespace *string `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	// *
	// Additional labels to apply to the secret.
	// These are merged with standard Planton labels for resource tracking and governance.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// Additional annotations to apply to the secret.
	Annotations map[string]string `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// When true, the secret data cannot be updated after creation.
	// Immutable secrets provide protection against accidental updates and
	// improve cluster performance by reducing watch load on the API server.
	Immutable bool `protobuf:"varint,6,opt,name=immutable,proto3" json:"immutable,omitempty"`
	// *
	// Type-safe secret data. Exactly one variant must be provided.
	// The variant determines the Kubernetes secret type and required fields.
	//
	// Types that are valid to be assigned to SecretData:
	//
	//	*KubernetesSecretSpec_Opaque
	//	*KubernetesSecretSpec_Tls
	//	*KubernetesSecretSpec_DockerConfigJson
	//	*KubernetesSecretSpec_BasicAuth
	//	*KubernetesSecretSpec_SshAuth
	SecretData    isKubernetesSecretSpec_SecretData `protobuf_oneof:"secret_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSecretSpec) Reset() {
	*x = KubernetesSecretSpec{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSecretSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSecretSpec) ProtoMessage() {}

func (x *KubernetesSecretSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSecretSpec.ProtoReflect.Descriptor instead.
func (*KubernetesSecretSpec) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesSecretSpec) GetTargetCluster() *kubernetes.KubernetesClusterSelector {
	if x != nil {
		return x.TargetCluster
	}
	return nil
}

func (x *KubernetesSecretSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubernetesSecretSpec) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *KubernetesSecretSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *KubernetesSecretSpec) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *KubernetesSecretSpec) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *KubernetesSecretSpec) GetSecretData() isKubernetesSecretSpec_SecretData {
	if x != nil {
		return x.SecretData
	}
	return nil
}

func (x *KubernetesSecretSpec) GetOpaque() *KubernetesSecretOpaqueData {
	if x != nil {
		if x, ok := x.SecretData.(*KubernetesSecretSpec_Opaque); ok {
			return x.Opaque
		}
	}
	return nil
}

func (x *KubernetesSecretSpec) GetTls() *KubernetesSecretTlsData {
	if x != nil {
		if x, ok := x.SecretData.(*KubernetesSecretSpec_Tls); ok {
			return x.Tls
		}
	}
	return nil
}

func (x *KubernetesSecretSpec) GetDockerConfigJson() *KubernetesSecretDockerConfigJsonData {
	if x != nil {
		if x, ok := x.SecretData.(*KubernetesSecretSpec_DockerConfigJson); ok {
			return x.DockerConfigJson
		}
	}
	return nil
}

func (x *KubernetesSecretSpec) GetBasicAuth() *KubernetesSecretBasicAuthData {
	if x != nil {
		if x, ok := x.SecretData.(*KubernetesSecretSpec_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

func (x *KubernetesSecretSpec) GetSshAuth() *KubernetesSecretSshAuthData {
	if x != nil {
		if x, ok := x.SecretData.(*KubernetesSecretSpec_SshAuth); ok {
			return x.SshAuth
		}
	}
	return nil
}

type isKubernetesSecretSpec_SecretData interface {
	isKubernetesSecretSpec_SecretData()
}

type KubernetesSecretSpec_Opaque struct {
	// Opaque secret with arbitrary key-value string data.
	// Maps to Kubernetes secret type "Opaque".
	Opaque *KubernetesSecretOpaqueData `protobuf:"bytes,7,opt,name=opaque,proto3,oneof"`
}

type KubernetesSecretSpec_Tls struct {
	// TLS secret containing a certificate and private key.
	// Maps to Kubernetes secret type "kubernetes.io/tls".
	Tls *KubernetesSecretTlsData `protobuf:"bytes,8,opt,name=tls,proto3,oneof"`
}

type KubernetesSecretSpec_DockerConfigJson struct {
	// Docker registry credentials for image pulls.
	// Maps to Kubernetes secret type "kubernetes.io/dockerconfigjson".
	DockerConfigJson *KubernetesSecretDockerConfigJsonData `protobuf:"bytes,9,opt,name=docker_config_json,json=dockerConfigJson,proto3,oneof"`
}

type KubernetesSecretSpec_BasicAuth struct {
	// Basic authentication credentials (username/password).
	// Maps to Kubernetes secret type "kubernetes.io/basic-auth".
	BasicAuth *KubernetesSecretBasicAuthData `protobuf:"bytes,10,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

type KubernetesSecretSpec_SshAuth struct {
	// SSH authentication credentials (private key).
	// Maps to Kubernetes secret type "kubernetes.io/ssh-auth".
	SshAuth *KubernetesSecretSshAuthData `protobuf:"bytes,11,opt,name=ssh_auth,json=sshAuth,proto3,oneof"`
}

func (*KubernetesSecretSpec_Opaque) isKubernetesSecretSpec_SecretData() {}

func (*KubernetesSecretSpec_Tls) isKubernetesSecretSpec_SecretData() {}

func (*KubernetesSecretSpec_DockerConfigJson) isKubernetesSecretSpec_SecretData() {}

func (*KubernetesSecretSpec_BasicAuth) isKubernetesSecretSpec_SecretData() {}

func (*KubernetesSecretSpec_SshAuth) isKubernetesSecretSpec_SecretData() {}

// *
// **KubernetesSecretOpaqueData** defines data for an Opaque secret.
// This is the most common secret type, used for arbitrary key-value pairs.
type KubernetesSecretOpaqueData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Key-value pairs of secret data.
	// Values are plain strings (Kubernetes stringData semantics).
	// At least one entry is required.
	Data          map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSecretOpaqueData) Reset() {
	*x = KubernetesSecretOpaqueData{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSecretOpaqueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSecretOpaqueData) ProtoMessage() {}

func (x *KubernetesSecretOpaqueData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSecretOpaqueData.ProtoReflect.Descriptor instead.
func (*KubernetesSecretOpaqueData) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesSecretOpaqueData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// *
// **KubernetesSecretTlsData** defines data for a TLS secret.
// Used for storing TLS certificates and private keys, commonly consumed by
// Ingress controllers and other TLS-terminating services.
type KubernetesSecretTlsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// PEM-encoded TLS certificate (or certificate chain).
	// Stored as the "tls.crt" key in the Kubernetes Secret.
	TlsCrt string `protobuf:"bytes,1,opt,name=tls_crt,json=tlsCrt,proto3" json:"tls_crt,omitempty"`
	// *
	// PEM-encoded TLS private key.
	// Stored as the "tls.key" key in the Kubernetes Secret.
	TlsKey        string `protobuf:"bytes,2,opt,name=tls_key,json=tlsKey,proto3" json:"tls_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSecretTlsData) Reset() {
	*x = KubernetesSecretTlsData{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSecretTlsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSecretTlsData) ProtoMessage() {}

func (x *KubernetesSecretTlsData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSecretTlsData.ProtoReflect.Descriptor instead.
func (*KubernetesSecretTlsData) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesSecretTlsData) GetTlsCrt() string {
	if x != nil {
		return x.TlsCrt
	}
	return ""
}

func (x *KubernetesSecretTlsData) GetTlsKey() string {
	if x != nil {
		return x.TlsKey
	}
	return ""
}

// *
// **KubernetesSecretDockerConfigJsonData** defines data for a Docker registry secret.
// Used for authenticating with container registries during image pulls.
// The IaC module constructs the .dockerconfigjson JSON from these fields.
type KubernetesSecretDockerConfigJsonData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Docker registry server URL (e.g., "https://index.docker.io/v1/", "gcr.io", "ghcr.io").
	RegistryServer string `protobuf:"bytes,1,opt,name=registry_server,json=registryServer,proto3" json:"registry_server,omitempty"`
	// *
	// Username for registry authentication.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// *
	// Password or access token for registry authentication.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// *
	// Optional email associated with the registry account.
	Email         string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSecretDockerConfigJsonData) Reset() {
	*x = KubernetesSecretDockerConfigJsonData{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSecretDockerConfigJsonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSecretDockerConfigJsonData) ProtoMessage() {}

func (x *KubernetesSecretDockerConfigJsonData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSecretDockerConfigJsonData.ProtoReflect.Descriptor instead.
func (*KubernetesSecretDockerConfigJsonData) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesSecretDockerConfigJsonData) GetRegistryServer() string {
	if x != nil {
		return x.RegistryServer
	}
	return ""
}

func (x *KubernetesSecretDockerConfigJsonData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *KubernetesSecretDockerConfigJsonData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *KubernetesSecretDockerConfigJsonData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// *
// **KubernetesSecretBasicAuthData** defines data for a basic authentication secret.
// Used for services that require username/password authentication.
type KubernetesSecretBasicAuthData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Username for basic authentication.
	// Stored as the "username" key in the Kubernetes Secret.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// *
	// Password for basic authentication.
	// Stored as the "password" key in the Kubernetes Secret.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSecretBasicAuthData) Reset() {
	*x = KubernetesSecretBasicAuthData{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSecretBasicAuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSecretBasicAuthData) ProtoMessage() {}

func (x *KubernetesSecretBasicAuthData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSecretBasicAuthData.ProtoReflect.Descriptor instead.
func (*KubernetesSecretBasicAuthData) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *KubernetesSecretBasicAuthData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *KubernetesSecretBasicAuthData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// *
// **KubernetesSecretSshAuthData** defines data for an SSH authentication secret.
// Used for Git operations, SSH tunneling, and other SSH-based authentication.
type KubernetesSecretSshAuthData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// PEM-encoded SSH private key.
	// Stored as the "ssh-privatekey" key in the Kubernetes Secret.
	SshPrivateKey string `protobuf:"bytes,1,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSecretSshAuthData) Reset() {
	*x = KubernetesSecretSshAuthData{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSecretSshAuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSecretSshAuthData) ProtoMessage() {}

func (x *KubernetesSecretSshAuthData) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSecretSshAuthData.ProtoReflect.Descriptor instead.
func (*KubernetesSecretSshAuthData) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *KubernetesSecretSshAuthData) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

var File_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto protoreflect.FileDescriptor

const file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDesc = "" +
	"\n" +
	">dev/planton/provider/kubernetes/kubernetessecret/v1/spec.proto\x123dev.planton.provider.kubernetes.kubernetessecret.v1\x1a\x1bbuf/validate/validate.proto\x1a4dev/planton/provider/kubernetes/target_cluster.proto\x1a(dev/planton/shared/options/options.proto\"\xba\x0e\n" +
	"\x14KubernetesSecretSpec\x12a\n" +
	"\x0etarget_cluster\x18\x01 \x01(\v2:.dev.planton.provider.kubernetes.KubernetesClusterSelectorR\rtargetCluster\x12\xe5\x01\n" +
	"\x04name\x18\x02 \x01(\tB\xd0\x01\xbaH\xcc\x01\xba\x01\xc1\x01\n" +
	"\x12name.dns_subdomain\x12sName must be a valid DNS subdomain (lowercase alphanumeric, hyphens, and dots, no leading/trailing dots or hyphens)\x1a6this.matches('^[a-z0-9]([a-z0-9.-]{0,251}[a-z0-9])?$')r\x05\x10\x01\x18\xfd\x01R\x04name\x12\xfb\x01\n" +
	"\tnamespace\x18\x03 \x01(\tB\xd7\x01\xbaH\xc8\x01\xba\x01\xc0\x01\n" +
	"\x13namespace.dns_label\x12eNamespace must be a valid DNS label (lowercase alphanumeric and hyphens, no leading/trailing hyphens)\x1aBthis == '' || this.matches('^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')r\x02\x18?\x8a\xa6\x1d\adefaultH\x01R\tnamespace\x88\x01\x01\x12m\n" +
	"\x06labels\x18\x04 \x03(\v2U.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.LabelsEntryR\x06labels\x12|\n" +
	"\vannotations\x18\x05 \x03(\v2Z.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\timmutable\x18\x06 \x01(\bR\timmutable\x12i\n" +
	"\x06opaque\x18\a \x01(\v2O.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueDataH\x00R\x06opaque\x12`\n" +
	"\x03tls\x18\b \x01(\v2L.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretTlsDataH\x00R\x03tls\x12\x89\x01\n" +
	"\x12docker_config_json\x18\t \x01(\v2Y.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretDockerConfigJsonDataH\x00R\x10dockerConfigJson\x12s\n" +
	"\n" +
	"basic_auth\x18\n" +
	" \x01(\v2R.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretBasicAuthDataH\x00R\tbasicAuth\x12m\n" +
	"\bssh_auth\x18\v \x01(\v2P.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSshAuthDataH\x00R\asshAuth\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xf8\x01\xbaH\xf4\x01\x1a\xf1\x01\n" +
	"\x14secret_data_required\x12hExactly one secret data type must be provided (opaque, tls, docker_config_json, basic_auth, or ssh_auth)\x1aohas(this.opaque) || has(this.tls) || has(this.docker_config_json) || has(this.basic_auth) || has(this.ssh_auth)B\r\n" +
	"\vsecret_dataB\f\n" +
	"\n" +
	"_namespace\"\xce\x01\n" +
	"\x1aKubernetesSecretOpaqueData\x12w\n" +
	"\x04data\x18\x01 \x03(\v2Y.dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueData.DataEntryB\b\xbaH\x05\x9a\x01\x02\b\x01R\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x17KubernetesSecretTlsData\x12 \n" +
	"\atls_crt\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06tlsCrt\x12 \n" +
	"\atls_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06tlsKey\"\xb8\x01\n" +
	"$KubernetesSecretDockerConfigJsonData\x120\n" +
	"\x0fregistry_server\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eregistryServer\x12#\n" +
	"\busername\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"i\n" +
	"\x1dKubernetesSecretBasicAuthData\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpassword\"N\n" +
	"\x1bKubernetesSecretSshAuthData\x12/\n" +
	"\x0fssh_private_key\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rsshPrivateKeyB\xa1\x03\n" +
	"7com.dev.planton.provider.kubernetes.kubernetessecret.v1B\tSpecProtoP\x01Zhgithub.com/plantonhq/planton/apis/dev/planton/provider/kubernetes/kubernetessecret/v1;kubernetessecretv1\xa2\x02\x05DPPKK\xaa\x023Dev.Planton.Provider.Kubernetes.Kubernetessecret.V1\xca\x023Dev\\Planton\\Provider\\Kubernetes\\Kubernetessecret\\V1\xe2\x02?Dev\\Planton\\Provider\\Kubernetes\\Kubernetessecret\\V1\\GPBMetadata\xea\x028Dev::Planton::Provider::Kubernetes::Kubernetessecret::V1b\x06proto3"

var (
	file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescOnce sync.Once
	file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescData []byte
)

func file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDesc)))
	})
	return file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDescData
}

var file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_goTypes = []any{
	(*KubernetesSecretSpec)(nil),                 // 0: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec
	(*KubernetesSecretOpaqueData)(nil),           // 1: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueData
	(*KubernetesSecretTlsData)(nil),              // 2: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretTlsData
	(*KubernetesSecretDockerConfigJsonData)(nil), // 3: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretDockerConfigJsonData
	(*KubernetesSecretBasicAuthData)(nil),        // 4: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretBasicAuthData
	(*KubernetesSecretSshAuthData)(nil),          // 5: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSshAuthData
	nil,                                          // 6: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.LabelsEntry
	nil,                                          // 7: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.AnnotationsEntry
	nil,                                          // 8: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueData.DataEntry
	(*kubernetes.KubernetesClusterSelector)(nil), // 9: dev.planton.provider.kubernetes.KubernetesClusterSelector
}
var file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_depIdxs = []int32{
	9, // 0: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.target_cluster:type_name -> dev.planton.provider.kubernetes.KubernetesClusterSelector
	6, // 1: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.labels:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.LabelsEntry
	7, // 2: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.annotations:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.AnnotationsEntry
	1, // 3: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.opaque:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueData
	2, // 4: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.tls:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretTlsData
	3, // 5: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.docker_config_json:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretDockerConfigJsonData
	4, // 6: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.basic_auth:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretBasicAuthData
	5, // 7: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSpec.ssh_auth:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretSshAuthData
	8, // 8: dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueData.data:type_name -> dev.planton.provider.kubernetes.kubernetessecret.v1.KubernetesSecretOpaqueData.DataEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_init() }
func file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_init() {
	if File_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto != nil {
		return
	}
	file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes[0].OneofWrappers = []any{
		(*KubernetesSecretSpec_Opaque)(nil),
		(*KubernetesSecretSpec_Tls)(nil),
		(*KubernetesSecretSpec_DockerConfigJson)(nil),
		(*KubernetesSecretSpec_BasicAuth)(nil),
		(*KubernetesSecretSpec_SshAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto = out.File
	file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_goTypes = nil
	file_dev_planton_provider_kubernetes_kubernetessecret_v1_spec_proto_depIdxs = nil
}
