apiVersion: aws.openmcf.org/v1
kind: AwsFsxOntapStorageVirtualMachine
metadata:
  name: <REPLACE>
  id: <REPLACE>
  org: <REPLACE>
  env: <REPLACE>
spec:
  region: <aws-region>
  file_system_id:
    value: fs-0123456789abcdef0
  name: svm_nfs
  root_volume_security_style: UNIX
