load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "locals.go",
        "main.go",
        "outputs.go",
        "secret_environment.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/aws/awsecstaskdefinition/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/aws/awsecstaskdefinition/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/aws/awstagkeys",
        "//pkg/iac/pulumi/pulumimodule/provider/aws/pulumiawsprovider",
        "//shared/cloudresourcekind",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_aws_sdk_v7//go/aws/cloudwatch",
        "@com_github_pulumi_pulumi_aws_sdk_v7//go/aws/ecs",
        "@com_github_pulumi_pulumi_aws_sdk_v7//go/aws/secretsmanager",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
