syntax = "proto3";

package dev.planton.aws.awsconfigrule.v1alpha1;

import "catalog/aws/awsconfigrule/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsConfigRuleIacInput is the input for the IaC modules that
// manage an AWS Config rule.
message AwsConfigRuleIacInput {
  // target is the AwsConfigRule resource to deploy.
  AwsConfigRule target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
