syntax = "proto3";

package dev.planton.aws.awssesaccountsettings.v1alpha1;

import "catalog/aws/awssesaccountsettings/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSesAccountSettingsIacInput is the input for the IaC modules
// that manage the region's SES account settings.
message AwsSesAccountSettingsIacInput {
  // target is the AwsSesAccountSettings resource to deploy.
  AwsSesAccountSettings target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
