syntax = "proto3";

package dev.planton.azure.azureprivatednsrecord.v1alpha1;

import "catalog/azure/azureprivatednsrecord/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzurePrivateDnsRecordIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and
// Azure provider credentials.
message AzurePrivateDnsRecordIacInput {
  // The private DNS record resource to deploy.
  AzurePrivateDnsRecord target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
