// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcphavpnconnection/v1alpha1/api.proto

package gcphavpnconnectionv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-ha-vpn-connection
type GcpHaVpnConnection struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ApiVersion    string                        `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                        `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *GcpHaVpnConnectionSpec       `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *GcpHaVpnConnectionStatus     `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpHaVpnConnection) Reset() {
	*x = GcpHaVpnConnection{}
	mi := &file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpHaVpnConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpHaVpnConnection) ProtoMessage() {}

func (x *GcpHaVpnConnection) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpHaVpnConnection.ProtoReflect.Descriptor instead.
func (*GcpHaVpnConnection) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GcpHaVpnConnection) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GcpHaVpnConnection) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GcpHaVpnConnection) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GcpHaVpnConnection) GetSpec() *GcpHaVpnConnectionSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GcpHaVpnConnection) GetStatus() *GcpHaVpnConnectionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GcpHaVpnConnectionStatus struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Outputs       *GcpHaVpnConnectionStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpHaVpnConnectionStatus) Reset() {
	*x = GcpHaVpnConnectionStatus{}
	mi := &file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpHaVpnConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpHaVpnConnectionStatus) ProtoMessage() {}

func (x *GcpHaVpnConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpHaVpnConnectionStatus.ProtoReflect.Descriptor instead.
func (*GcpHaVpnConnectionStatus) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GcpHaVpnConnectionStatus) GetOutputs() *GcpHaVpnConnectionStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"1catalog/gcp/gcphavpnconnection/v1alpha1/api.proto\x12+dev.planton.gcp.gcphavpnconnection.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a5catalog/gcp/gcphavpnconnection/v1alpha1/outputs.proto\x1a2catalog/gcp/gcphavpnconnection/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\x94\x03\n" +
	"\x12GcpHaVpnConnection\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18gcp.planton.dev/v1alpha1R\n" +
	"apiVersion\x12-\n" +
	"\x04kind\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\n" +
	"\x12GcpHaVpnConnectionR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12_\n" +
	"\x04spec\x18\x04 \x01(\v2C.dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12]\n" +
	"\x06status\x18\x05 \x01(\v2E.dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStatusR\x06status\"\x81\x01\n" +
	"\x18GcpHaVpnConnectionStatus\x12e\n" +
	"\aoutputs\x18\x01 \x01(\v2K.dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStackOutputsR\aoutputsB\xed\x02\n" +
	"/com.dev.planton.gcp.gcphavpnconnection.v1alpha1B\bApiProtoP\x01Z_github.com/plantonhq/planton/catalog/gcp/gcphavpnconnection/v1alpha1;gcphavpnconnectionv1alpha1\xa2\x02\x04DPGG\xaa\x02+Dev.Planton.Gcp.Gcphavpnconnection.V1alpha1\xca\x02+Dev\\Planton\\Gcp\\Gcphavpnconnection\\V1alpha1\xe2\x027Dev\\Planton\\Gcp\\Gcphavpnconnection\\V1alpha1\\GPBMetadata\xea\x02/Dev::Planton::Gcp::Gcphavpnconnection::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDescData
}

var file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_goTypes = []any{
	(*GcpHaVpnConnection)(nil),             // 0: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnection
	(*GcpHaVpnConnectionStatus)(nil),       // 1: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStatus
	(*shared.CloudResourceMetadata)(nil),   // 2: dev.planton.shared.CloudResourceMetadata
	(*GcpHaVpnConnectionSpec)(nil),         // 3: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionSpec
	(*GcpHaVpnConnectionStackOutputs)(nil), // 4: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStackOutputs
}
var file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnection.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnection.spec:type_name -> dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionSpec
	1, // 2: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnection.status:type_name -> dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStatus
	4, // 3: dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStatus.outputs:type_name -> dev.planton.gcp.gcphavpnconnection.v1alpha1.GcpHaVpnConnectionStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_init() }
func file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_init() {
	if File_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_gcp_gcphavpnconnection_v1alpha1_outputs_proto_init()
	file_catalog_gcp_gcphavpnconnection_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto = out.File
	file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_goTypes = nil
	file_catalog_gcp_gcphavpnconnection_v1alpha1_api_proto_depIdxs = nil
}
