apiVersion: cloudflare.planton.dev/v1
kind: CloudflareEmailRoutingRule
metadata:
  name: test-email-routing-rule
spec:
  zoneId:
    value: "023e105f4ecef8ad9ca31a8372d0c353"
  name: support-to-ops
  enabled: true
  priority: 0
  matchers:
    - type: literal
      field: to
      value: support@example.com
  action:
    type: forward
    forwardTo:
      - value: ops@example.com
