// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/kubernetes/kubernetessolroperator/v1/spec.proto

package kubernetessolroperatorv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kubernetes "github.com/plantonhq/planton/apis/dev/planton/provider/kubernetes"
	v1 "github.com/plantonhq/planton/apis/dev/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/apis/dev/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **KubernetesSolrOperatorSpec** defines the configuration for deploying Apache Solr Operator on a Kubernetes cluster.
// This message specifies the parameters needed to create and manage an Apache Solr Operator deployment within a Kubernetes environment.
// It includes container specifications to control resource allocation.
type KubernetesSolrOperatorSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target Kubernetes Cluster
	TargetCluster *kubernetes.KubernetesClusterSelector `protobuf:"bytes,1,opt,name=target_cluster,json=targetCluster,proto3" json:"target_cluster,omitempty"`
	// Kubernetes Namespace
	Namespace *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// flag to indicate if the namespace should be created
	CreateNamespace bool `protobuf:"varint,3,opt,name=create_namespace,json=createNamespace,proto3" json:"create_namespace,omitempty"`
	// The version of the Apache Solr Operator to deploy.
	// https://github.com/apache/solr-operator/releases
	OperatorVersion string `protobuf:"bytes,4,opt,name=operator_version,json=operatorVersion,proto3" json:"operator_version,omitempty"`
	// The container specifications for the Apache Solr Operator deployment.
	Container     *KubernetesSolrOperatorSpecContainer `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSolrOperatorSpec) Reset() {
	*x = KubernetesSolrOperatorSpec{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSolrOperatorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSolrOperatorSpec) ProtoMessage() {}

func (x *KubernetesSolrOperatorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSolrOperatorSpec.ProtoReflect.Descriptor instead.
func (*KubernetesSolrOperatorSpec) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesSolrOperatorSpec) GetTargetCluster() *kubernetes.KubernetesClusterSelector {
	if x != nil {
		return x.TargetCluster
	}
	return nil
}

func (x *KubernetesSolrOperatorSpec) GetNamespace() *v1.StringValueOrRef {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *KubernetesSolrOperatorSpec) GetCreateNamespace() bool {
	if x != nil {
		return x.CreateNamespace
	}
	return false
}

func (x *KubernetesSolrOperatorSpec) GetOperatorVersion() string {
	if x != nil {
		return x.OperatorVersion
	}
	return ""
}

func (x *KubernetesSolrOperatorSpec) GetContainer() *KubernetesSolrOperatorSpecContainer {
	if x != nil {
		return x.Container
	}
	return nil
}

// **KubernetesSolrOperatorSpecContainer** specifies the container configuration for the Apache Solr Operator application.
// It includes resource allocations for CPU and memory to ensure the application runs efficiently.
type KubernetesSolrOperatorSpecContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CPU and memory resources allocated to the Apache Solr Operator container.
	Resources     *kubernetes.ContainerResources `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesSolrOperatorSpecContainer) Reset() {
	*x = KubernetesSolrOperatorSpecContainer{}
	mi := &file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSolrOperatorSpecContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSolrOperatorSpecContainer) ProtoMessage() {}

func (x *KubernetesSolrOperatorSpecContainer) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSolrOperatorSpecContainer.ProtoReflect.Descriptor instead.
func (*KubernetesSolrOperatorSpecContainer) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesSolrOperatorSpecContainer) GetResources() *kubernetes.ContainerResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto protoreflect.FileDescriptor

const file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDesc = "" +
	"\n" +
	"Ddev/planton/provider/kubernetes/kubernetessolroperator/v1/spec.proto\x129dev.planton.provider.kubernetes.kubernetessolroperator.v1\x1a\x1bbuf/validate/validate.proto\x1a0dev/planton/provider/kubernetes/kubernetes.proto\x1a-dev/planton/provider/kubernetes/options.proto\x1a4dev/planton/provider/kubernetes/target_cluster.proto\x1a2dev/planton/shared/foreignkey/v1/foreign_key.proto\x1a(dev/planton/shared/options/options.proto\"\xd4\x03\n" +
	"\x1aKubernetesSolrOperatorSpec\x12a\n" +
	"\x0etarget_cluster\x18\x01 \x01(\v2:.dev.planton.provider.kubernetes.KubernetesClusterSelectorR\rtargetCluster\x12j\n" +
	"\tnamespace\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x18\xbaH\x03\xc8\x01\x01\x88\xd4a\xc4\x06\x92\xd4a\tspec.nameR\tnamespace\x12)\n" +
	"\x10create_namespace\x18\x03 \x01(\bR\x0fcreateNamespace\x125\n" +
	"\x10operator_version\x18\x04 \x01(\tB\n" +
	"\x8a\xa6\x1d\x06v0.9.1R\x0foperatorVersion\x12\x84\x01\n" +
	"\tcontainer\x18\x05 \x01(\v2^.dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpecContainerB\x06\xbaH\x03\xc8\x01\x01R\tcontainer\"\x9b\x01\n" +
	"#KubernetesSolrOperatorSpecContainer\x12t\n" +
	"\tresources\x18\x01 \x01(\v23.dev.planton.provider.kubernetes.ContainerResourcesB!\xba\xfb\xa4\x02\x1c\n" +
	"\f\n" +
	"\x051000m\x12\x031Gi\x12\f\n" +
	"\x0350m\x12\x05100MiR\tresourcesB\xcb\x03\n" +
	"=com.dev.planton.provider.kubernetes.kubernetessolroperator.v1B\tSpecProtoP\x01Ztgithub.com/plantonhq/planton/apis/dev/planton/provider/kubernetes/kubernetessolroperator/v1;kubernetessolroperatorv1\xa2\x02\x05DPPKK\xaa\x029Dev.Planton.Provider.Kubernetes.Kubernetessolroperator.V1\xca\x029Dev\\Planton\\Provider\\Kubernetes\\Kubernetessolroperator\\V1\xe2\x02EDev\\Planton\\Provider\\Kubernetes\\Kubernetessolroperator\\V1\\GPBMetadata\xea\x02>Dev::Planton::Provider::Kubernetes::Kubernetessolroperator::V1b\x06proto3"

var (
	file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescOnce sync.Once
	file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescData []byte
)

func file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDesc)))
	})
	return file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDescData
}

var file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_goTypes = []any{
	(*KubernetesSolrOperatorSpec)(nil),           // 0: dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpec
	(*KubernetesSolrOperatorSpecContainer)(nil),  // 1: dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpecContainer
	(*kubernetes.KubernetesClusterSelector)(nil), // 2: dev.planton.provider.kubernetes.KubernetesClusterSelector
	(*v1.StringValueOrRef)(nil),                  // 3: dev.planton.shared.foreignkey.v1.StringValueOrRef
	(*kubernetes.ContainerResources)(nil),        // 4: dev.planton.provider.kubernetes.ContainerResources
}
var file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_depIdxs = []int32{
	2, // 0: dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpec.target_cluster:type_name -> dev.planton.provider.kubernetes.KubernetesClusterSelector
	3, // 1: dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpec.namespace:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 2: dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpec.container:type_name -> dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpecContainer
	4, // 3: dev.planton.provider.kubernetes.kubernetessolroperator.v1.KubernetesSolrOperatorSpecContainer.resources:type_name -> dev.planton.provider.kubernetes.ContainerResources
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_init() }
func file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_init() {
	if File_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto = out.File
	file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_goTypes = nil
	file_dev_planton_provider_kubernetes_kubernetessolroperator_v1_spec_proto_depIdxs = nil
}
