syntax = "proto3";

package dev.planton.digitalocean.digitaloceandatabasereplica.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceandatabasereplica/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceandatabasereplica/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-database-replica
message DigitalOceanDatabaseReplica {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'digital-ocean.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'DigitalOceanDatabaseReplica'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanDatabaseReplicaSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanDatabaseReplicaStatus status = 5;
}

// digital-ocean-database-replica status
message DigitalOceanDatabaseReplicaStatus {
  //outputs
  //  digital-ocean-database-replica outputs
  DigitalOceanDatabaseReplicaOutputs outputs = 1;
}
