syntax = "proto3";

package dev.planton.gcp.gcphavpngateway.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcphavpngateway/v1alpha1/outputs.proto";
import "catalog/gcp/gcphavpngateway/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-ha-vpn-gateway
message GcpHaVpnGateway {
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'GcpHaVpnGateway'];
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];
  GcpHaVpnGatewaySpec spec = 4 [(buf.validate.field).required = true];
  GcpHaVpnGatewayStatus status = 5;
}

message GcpHaVpnGatewayStatus {
  GcpHaVpnGatewayStackOutputs outputs = 1;
}
