syntax = "proto3";

package dev.planton.gcp.gcpdocumentaiprocessor.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcpdocumentaiprocessor/v1alpha1/outputs.proto";
import "catalog/gcp/gcpdocumentaiprocessor/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-document-ai-processor
message GcpDocumentAiProcessor {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'GcpDocumentAiProcessor'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  GcpDocumentAiProcessorSpec spec = 4 [(buf.validate.field).required = true];

  //status
  GcpDocumentAiProcessorStatus status = 5;
}

//gcp-document-ai-processor status
message GcpDocumentAiProcessorStatus {
  //stack-outputs
  GcpDocumentAiProcessorStackOutputs outputs = 1;
}
