syntax = "proto3";

package dev.planton.azure.azurevirtualnetworkpeering.v1alpha1;

import "catalog/azure/azurevirtualnetworkpeering/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureVirtualNetworkPeeringIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and Azure
// provider credentials.
message AzureVirtualNetworkPeeringIacInput {
  // The virtual network peering resource to deploy.
  AzureVirtualNetworkPeering target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
