apiVersion: cloudflare.openmcf.org/v1
kind: CloudflareZeroTrustAccessApplication
metadata:
  name: my-company-wide-email
spec:
  applicationName: Internal App - Company Domain
  zoneId:
    value: <cloudflare-zone-id>
  hostname: <app-subdomain>.<your-domain.com>
  policyType: ALLOW
  allowedEmails:
    - "*@<company-domain>"
  sessionDurationMinutes: 1440
  requireMfa: false
