syntax = "proto3";

package dev.planton.aws.awsmanagedprometheus.v1alpha1;

import "catalog/aws/awsmanagedprometheus/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsManagedPrometheusIacInput is the input for the IaC modules that
// manage an Amazon Managed Prometheus workspace and its satellites.
message AwsManagedPrometheusIacInput {
  // target is the AwsManagedPrometheus resource to deploy.
  AwsManagedPrometheus target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
