// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awselasticacheusergroup/v1alpha1/outputs.proto

package awselasticacheusergroupv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsElasticacheUserGroupOutputs captures observable identifiers from a
// provisioned ElastiCache user group. These outputs are used by downstream
// resources to wire dependencies via StringValueOrRef — most importantly the
// replication group's `user_group_ids` and the serverless cache's
// `user_group_id`.
type AwsElasticacheUserGroupOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group's AWS identifier (the user group id). This is what caches
	// reference to attach RBAC and what the AWS CLI/API address.
	UserGroupId string `protobuf:"bytes,1,opt,name=user_group_id,json=userGroupId,proto3" json:"user_group_id,omitempty"`
	// The Amazon Resource Name of the user group. Used in IAM policies and
	// cross-service permissions.
	Arn           string `protobuf:"bytes,2,opt,name=arn,proto3" json:"arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsElasticacheUserGroupOutputs) Reset() {
	*x = AwsElasticacheUserGroupOutputs{}
	mi := &file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsElasticacheUserGroupOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsElasticacheUserGroupOutputs) ProtoMessage() {}

func (x *AwsElasticacheUserGroupOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsElasticacheUserGroupOutputs.ProtoReflect.Descriptor instead.
func (*AwsElasticacheUserGroupOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *AwsElasticacheUserGroupOutputs) GetUserGroupId() string {
	if x != nil {
		return x.UserGroupId
	}
	return ""
}

func (x *AwsElasticacheUserGroupOutputs) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

var File_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	":catalog/aws/awselasticacheusergroup/v1alpha1/outputs.proto\x120dev.planton.aws.awselasticacheusergroup.v1alpha1\"V\n" +
	"\x1eAwsElasticacheUserGroupOutputs\x12\"\n" +
	"\ruser_group_id\x18\x01 \x01(\tR\vuserGroupId\x12\x10\n" +
	"\x03arn\x18\x02 \x01(\tR\x03arnB\x94\x03\n" +
	"4com.dev.planton.aws.awselasticacheusergroup.v1alpha1B\fOutputsProtoP\x01Zigithub.com/plantonhq/planton/catalog/aws/awselasticacheusergroup/v1alpha1;awselasticacheusergroupv1alpha1\xa2\x02\x04DPAA\xaa\x020Dev.Planton.Aws.Awselasticacheusergroup.V1alpha1\xca\x020Dev\\Planton\\Aws\\Awselasticacheusergroup\\V1alpha1\xe2\x02<Dev\\Planton\\Aws\\Awselasticacheusergroup\\V1alpha1\\GPBMetadata\xea\x024Dev::Planton::Aws::Awselasticacheusergroup::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_goTypes = []any{
	(*AwsElasticacheUserGroupOutputs)(nil), // 0: dev.planton.aws.awselasticacheusergroup.v1alpha1.AwsElasticacheUserGroupOutputs
}
var file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_init() }
func file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_init() {
	if File_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto = out.File
	file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_aws_awselasticacheusergroup_v1alpha1_outputs_proto_depIdxs = nil
}
