load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "module",
    srcs = [
        "locals.go",
        "logging.go",
        "main.go",
        "outputs.go",
        "rules.go",
        "web_acl.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/aws/awswafwebacl/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/aws/awswafwebacl/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/aws/awstagkeys",
        "//pkg/iac/pulumi/pulumimodule/provider/aws/pulumiawsprovider",
        "//shared/catalogkind",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_aws_sdk_v7//go/aws",
        "@com_github_pulumi_pulumi_aws_sdk_v7//go/aws/wafv2",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)

go_test(
    name = "module_test",
    srcs = ["rules_test.go"],
    embed = [":module"],
    deps = [
        "//catalog/aws/awswafwebacl/v1alpha1",
        "//shared/foreignkey/v1:foreignkey",
        "@org_golang_google_protobuf//proto",
    ],
)
