syntax = "proto3";

package dev.planton.azure.azurecognitivedeployment.v1alpha1;

import "catalog/azure/azurecognitivedeployment/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureCognitiveDeploymentIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and
// Azure provider credentials.
message AzureCognitiveDeploymentIacInput {
  // The model deployment resource to deploy.
  AzureCognitiveDeployment target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
