syntax = "proto3";

package dev.planton.cloudflare.cloudflarezerotrustdevicecustomprofile.v1alpha1;

import "catalog/cloudflare/cloudflarezerotrustdevicecustomprofile/v1alpha1/api.proto";
import "catalog/cloudflare/provider.proto";

// CloudflareZeroTrustDeviceCustomProfileIacInput is the input to the IaC
// module. It contains the target resource and provider configuration.
message CloudflareZeroTrustDeviceCustomProfileIacInput {
  // target infra-component to be deployed
  CloudflareZeroTrustDeviceCustomProfile target = 1;
  // provider-config for Cloudflare authentication
  dev.planton.cloudflare.CloudflareProviderConfig provider_config = 2;
}
