apiVersion: aws.planton.dev/v1
kind: AwsLambda
metadata:
  name: my-zip-lambda
spec:
  region: <aws-region>
  functionName: <function-name>
  roleArn:
    value: "<lambda-execution-role-arn>"
  runtime: nodejs18.x
  handler: index.handler
  memoryMb: 256
  timeoutSeconds: 30
  codeSourceType: CODE_SOURCE_TYPE_S3
  s3:
    bucket: <deployment-bucket>
    key: <deployment-package-key>
