syntax = "proto3";

package dev.planton.azure.azurenatgateway.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/azure/azurenatgateway/v1alpha1/outputs.proto";
import "catalog/azure/azurenatgateway/v1alpha1/spec.proto";
import "shared/metadata.proto";

// azure-nat-gateway
message AzureNatGateway {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'azure.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AzureNatGateway'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  AzureNatGatewaySpec spec = 4 [(buf.validate.field).required = true];

  //status
  AzureNatGatewayStatus status = 5;
}

// azure-nat-gateway status
message AzureNatGatewayStatus {
  //outputs
  //  azure-nat-gateway outputs
  AzureNatGatewayOutputs outputs = 1;
}
