// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpdatastreamprivateconnection/v1alpha1/api.proto

package gcpdatastreamprivateconnectionv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-datastream-private-connection
type GcpDatastreamPrivateConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *GcpDatastreamPrivateConnectionSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *GcpDatastreamPrivateConnectionStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpDatastreamPrivateConnection) Reset() {
	*x = GcpDatastreamPrivateConnection{}
	mi := &file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpDatastreamPrivateConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpDatastreamPrivateConnection) ProtoMessage() {}

func (x *GcpDatastreamPrivateConnection) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpDatastreamPrivateConnection.ProtoReflect.Descriptor instead.
func (*GcpDatastreamPrivateConnection) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GcpDatastreamPrivateConnection) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GcpDatastreamPrivateConnection) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GcpDatastreamPrivateConnection) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GcpDatastreamPrivateConnection) GetSpec() *GcpDatastreamPrivateConnectionSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GcpDatastreamPrivateConnection) GetStatus() *GcpDatastreamPrivateConnectionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// gcp-datastream-private-connection status
type GcpDatastreamPrivateConnectionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *GcpDatastreamPrivateConnectionStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpDatastreamPrivateConnectionStatus) Reset() {
	*x = GcpDatastreamPrivateConnectionStatus{}
	mi := &file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpDatastreamPrivateConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpDatastreamPrivateConnectionStatus) ProtoMessage() {}

func (x *GcpDatastreamPrivateConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpDatastreamPrivateConnectionStatus.ProtoReflect.Descriptor instead.
func (*GcpDatastreamPrivateConnectionStatus) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GcpDatastreamPrivateConnectionStatus) GetOutputs() *GcpDatastreamPrivateConnectionStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"=catalog/gcp/gcpdatastreamprivateconnection/v1alpha1/api.proto\x127dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1aAcatalog/gcp/gcpdatastreamprivateconnection/v1alpha1/outputs.proto\x1a>catalog/gcp/gcpdatastreamprivateconnection/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xdc\x03\n" +
	"\x1eGcpDatastreamPrivateConnection\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18gcp.planton.dev/v1alpha1R\n" +
	"apiVersion\x129\n" +
	"\x04kind\x18\x02 \x01(\tB%\xbaH\"r \n" +
	"\x1eGcpDatastreamPrivateConnectionR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12w\n" +
	"\x04spec\x18\x04 \x01(\v2[.dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12u\n" +
	"\x06status\x18\x05 \x01(\v2].dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStatusR\x06status\"\xa5\x01\n" +
	"$GcpDatastreamPrivateConnectionStatus\x12}\n" +
	"\aoutputs\x18\x01 \x01(\v2c.dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStackOutputsR\aoutputsB\xc1\x03\n" +
	";com.dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1B\bApiProtoP\x01Zwgithub.com/plantonhq/planton/catalog/gcp/gcpdatastreamprivateconnection/v1alpha1;gcpdatastreamprivateconnectionv1alpha1\xa2\x02\x04DPGG\xaa\x027Dev.Planton.Gcp.Gcpdatastreamprivateconnection.V1alpha1\xca\x027Dev\\Planton\\Gcp\\Gcpdatastreamprivateconnection\\V1alpha1\xe2\x02CDev\\Planton\\Gcp\\Gcpdatastreamprivateconnection\\V1alpha1\\GPBMetadata\xea\x02;Dev::Planton::Gcp::Gcpdatastreamprivateconnection::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDescData
}

var file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_goTypes = []any{
	(*GcpDatastreamPrivateConnection)(nil),             // 0: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnection
	(*GcpDatastreamPrivateConnectionStatus)(nil),       // 1: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStatus
	(*shared.CloudResourceMetadata)(nil),               // 2: dev.planton.shared.CloudResourceMetadata
	(*GcpDatastreamPrivateConnectionSpec)(nil),         // 3: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionSpec
	(*GcpDatastreamPrivateConnectionStackOutputs)(nil), // 4: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStackOutputs
}
var file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnection.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnection.spec:type_name -> dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionSpec
	1, // 2: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnection.status:type_name -> dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStatus
	4, // 3: dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStatus.outputs:type_name -> dev.planton.gcp.gcpdatastreamprivateconnection.v1alpha1.GcpDatastreamPrivateConnectionStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_init() }
func file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_init() {
	if File_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_outputs_proto_init()
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto = out.File
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_goTypes = nil
	file_catalog_gcp_gcpdatastreamprivateconnection_v1alpha1_api_proto_depIdxs = nil
}
