// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/kubernetes/kuberneteshttproute/v1/stack_input.proto

package kuberneteshttproutev1

import (
	kubernetes "github.com/plantonhq/openmcf/apis/org/openmcf/provider/kubernetes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Input for the KubernetesHttpRoute IaC stack. The platform resolves all
// StringValueOrRef references (namespace) to literal strings before passing this
// to the IaC engine.
type KubernetesHttpRouteStackInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target cloud-resource.
	Target *KubernetesHttpRoute `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Kubernetes provider configuration (cluster credentials).
	ProviderConfig *kubernetes.KubernetesProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesHttpRouteStackInput) Reset() {
	*x = KubernetesHttpRouteStackInput{}
	mi := &file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesHttpRouteStackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesHttpRouteStackInput) ProtoMessage() {}

func (x *KubernetesHttpRouteStackInput) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesHttpRouteStackInput.ProtoReflect.Descriptor instead.
func (*KubernetesHttpRouteStackInput) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesHttpRouteStackInput) GetTarget() *KubernetesHttpRoute {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *KubernetesHttpRouteStackInput) GetProviderConfig() *kubernetes.KubernetesProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

var File_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDesc = "" +
	"\n" +
	"Horg/openmcf/provider/kubernetes/kuberneteshttproute/v1/stack_input.proto\x126org.openmcf.provider.kubernetes.kuberneteshttproute.v1\x1a@org/openmcf/provider/kubernetes/kuberneteshttproute/v1/api.proto\x1a.org/openmcf/provider/kubernetes/provider.proto\"\xe8\x01\n" +
	"\x1dKubernetesHttpRouteStackInput\x12c\n" +
	"\x06target\x18\x01 \x01(\v2K.org.openmcf.provider.kubernetes.kuberneteshttproute.v1.KubernetesHttpRouteR\x06target\x12b\n" +
	"\x0fprovider_config\x18\x02 \x01(\v29.org.openmcf.provider.kubernetes.KubernetesProviderConfigR\x0eproviderConfigB\xbc\x03\n" +
	":com.org.openmcf.provider.kubernetes.kuberneteshttproute.v1B\x0fStackInputProtoP\x01Zngithub.com/plantonhq/openmcf/apis/org/openmcf/provider/kubernetes/kuberneteshttproute/v1;kuberneteshttproutev1\xa2\x02\x05OOPKK\xaa\x026Org.Openmcf.Provider.Kubernetes.Kuberneteshttproute.V1\xca\x026Org\\Openmcf\\Provider\\Kubernetes\\Kuberneteshttproute\\V1\xe2\x02BOrg\\Openmcf\\Provider\\Kubernetes\\Kuberneteshttproute\\V1\\GPBMetadata\xea\x02;Org::Openmcf::Provider::Kubernetes::Kuberneteshttproute::V1b\x06proto3"

var (
	file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescData []byte
)

func file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDesc), len(file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDesc)))
	})
	return file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDescData
}

var file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_goTypes = []any{
	(*KubernetesHttpRouteStackInput)(nil),       // 0: org.openmcf.provider.kubernetes.kuberneteshttproute.v1.KubernetesHttpRouteStackInput
	(*KubernetesHttpRoute)(nil),                 // 1: org.openmcf.provider.kubernetes.kuberneteshttproute.v1.KubernetesHttpRoute
	(*kubernetes.KubernetesProviderConfig)(nil), // 2: org.openmcf.provider.kubernetes.KubernetesProviderConfig
}
var file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_depIdxs = []int32{
	1, // 0: org.openmcf.provider.kubernetes.kuberneteshttproute.v1.KubernetesHttpRouteStackInput.target:type_name -> org.openmcf.provider.kubernetes.kuberneteshttproute.v1.KubernetesHttpRoute
	2, // 1: org.openmcf.provider.kubernetes.kuberneteshttproute.v1.KubernetesHttpRouteStackInput.provider_config:type_name -> org.openmcf.provider.kubernetes.KubernetesProviderConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_init() }
func file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_init() {
	if File_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto != nil {
		return
	}
	file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDesc), len(file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto = out.File
	file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_goTypes = nil
	file_org_openmcf_provider_kubernetes_kuberneteshttproute_v1_stack_input_proto_depIdxs = nil
}
