syntax = "proto3";

package dev.planton.gcp.gcpcertmanagerissuanceconfig.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcpcertmanagerissuanceconfig/v1alpha1/outputs.proto";
import "catalog/gcp/gcpcertmanagerissuanceconfig/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-cert-manager-issuance-config
message GcpCertManagerIssuanceConfig {
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'GcpCertManagerIssuanceConfig'];
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];
  GcpCertManagerIssuanceConfigSpec spec = 4 [(buf.validate.field).required = true];
  GcpCertManagerIssuanceConfigStatus status = 5;
}

message GcpCertManagerIssuanceConfigStatus {
  GcpCertManagerIssuanceConfigStackOutputs outputs = 1;
}
