syntax = "proto3";

package dev.planton.aws.awsebsvolume.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsebsvolume/v1alpha1/outputs.proto";
import "catalog/aws/awsebsvolume/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsEbsVolume {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsEbsVolume'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsEbsVolumeSpec spec = 4 [(buf.validate.field).required = true];
  AwsEbsVolumeStatus status = 5;
}

message AwsEbsVolumeStatus {
  AwsEbsVolumeOutputs outputs = 1;
}
