// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awsdlmlifecyclepolicy/v1alpha1/outputs.proto

package awsdlmlifecyclepolicyv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsDlmLifecyclePolicyOutputs captures the observable state of
// the policy after apply.
type AwsDlmLifecyclePolicyOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy's id (policy-...) - the provider's import ID.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// The policy's ARN.
	PolicyArn     string `protobuf:"bytes,2,opt,name=policy_arn,json=policyArn,proto3" json:"policy_arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsDlmLifecyclePolicyOutputs) Reset() {
	*x = AwsDlmLifecyclePolicyOutputs{}
	mi := &file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsDlmLifecyclePolicyOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsDlmLifecyclePolicyOutputs) ProtoMessage() {}

func (x *AwsDlmLifecyclePolicyOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsDlmLifecyclePolicyOutputs.ProtoReflect.Descriptor instead.
func (*AwsDlmLifecyclePolicyOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *AwsDlmLifecyclePolicyOutputs) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *AwsDlmLifecyclePolicyOutputs) GetPolicyArn() string {
	if x != nil {
		return x.PolicyArn
	}
	return ""
}

var File_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	"8catalog/aws/awsdlmlifecyclepolicy/v1alpha1/outputs.proto\x12.dev.planton.aws.awsdlmlifecyclepolicy.v1alpha1\"Z\n" +
	"\x1cAwsDlmLifecyclePolicyOutputs\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x1d\n" +
	"\n" +
	"policy_arn\x18\x02 \x01(\tR\tpolicyArnB\x86\x03\n" +
	"2com.dev.planton.aws.awsdlmlifecyclepolicy.v1alpha1B\fOutputsProtoP\x01Zegithub.com/plantonhq/planton/catalog/aws/awsdlmlifecyclepolicy/v1alpha1;awsdlmlifecyclepolicyv1alpha1\xa2\x02\x04DPAA\xaa\x02.Dev.Planton.Aws.Awsdlmlifecyclepolicy.V1alpha1\xca\x02.Dev\\Planton\\Aws\\Awsdlmlifecyclepolicy\\V1alpha1\xe2\x02:Dev\\Planton\\Aws\\Awsdlmlifecyclepolicy\\V1alpha1\\GPBMetadata\xea\x022Dev::Planton::Aws::Awsdlmlifecyclepolicy::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_goTypes = []any{
	(*AwsDlmLifecyclePolicyOutputs)(nil), // 0: dev.planton.aws.awsdlmlifecyclepolicy.v1alpha1.AwsDlmLifecyclePolicyOutputs
}
var file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_init() }
func file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_init() {
	if File_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto = out.File
	file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_aws_awsdlmlifecyclepolicy_v1alpha1_outputs_proto_depIdxs = nil
}
