apiVersion: digital-ocean.planton.dev/v1alpha1
kind: DigitalOceanKubernetesCluster
metadata:
  name: my-dev-cluster
spec:
  clusterName: my-dev-cluster
  region: nyc3
  kubernetesVersion: "1.35"
  vpc:
    valueFrom:
      kind: DigitalOceanVpc
      name: my-vpc
      fieldPath: status.outputs.vpc_id
  tags:
    - development
    - kubernetes
  defaultNodePool:
    size: s-2vcpu-4gb
    nodeCount: 2
