syntax = "proto3";

package dev.planton.aws.awsneptunecluster.v1alpha1;

import "catalog/aws/awsneptunecluster/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsNeptuneClusterIacInput is the input for the IaC modules that deploy the Neptune cluster.
message AwsNeptuneClusterIacInput {
  // target is the AwsNeptuneCluster resource to deploy.
  AwsNeptuneCluster target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
