syntax = "proto3";

package dev.planton.cloudflare.cloudflarezerotrustaccessapplication.v1alpha1;

import "catalog/cloudflare/cloudflarezerotrustaccessapplication/v1alpha1/api.proto";
import "catalog/cloudflare/provider.proto";

//cloudflare-zero-trust-access-application iac-input
message CloudflareZeroTrustAccessApplicationIacInput {
  // the catalog object to deploy
  CloudflareZeroTrustAccessApplication target = 1;
  //provider-config
  dev.planton.cloudflare.CloudflareProviderConfig provider_config = 2;
}
