// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpdatastreamstream/v1alpha1/api.proto

package gcpdatastreamstreamv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-datastream-stream
type GcpDatastreamStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *GcpDatastreamStreamSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *GcpDatastreamStreamStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpDatastreamStream) Reset() {
	*x = GcpDatastreamStream{}
	mi := &file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpDatastreamStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpDatastreamStream) ProtoMessage() {}

func (x *GcpDatastreamStream) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpDatastreamStream.ProtoReflect.Descriptor instead.
func (*GcpDatastreamStream) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GcpDatastreamStream) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GcpDatastreamStream) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GcpDatastreamStream) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GcpDatastreamStream) GetSpec() *GcpDatastreamStreamSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GcpDatastreamStream) GetStatus() *GcpDatastreamStreamStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// gcp-datastream-stream status
type GcpDatastreamStreamStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *GcpDatastreamStreamStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpDatastreamStreamStatus) Reset() {
	*x = GcpDatastreamStreamStatus{}
	mi := &file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpDatastreamStreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpDatastreamStreamStatus) ProtoMessage() {}

func (x *GcpDatastreamStreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpDatastreamStreamStatus.ProtoReflect.Descriptor instead.
func (*GcpDatastreamStreamStatus) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GcpDatastreamStreamStatus) GetOutputs() *GcpDatastreamStreamStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"2catalog/gcp/gcpdatastreamstream/v1alpha1/api.proto\x12,dev.planton.gcp.gcpdatastreamstream.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a6catalog/gcp/gcpdatastreamstream/v1alpha1/outputs.proto\x1a3catalog/gcp/gcpdatastreamstream/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\x9a\x03\n" +
	"\x13GcpDatastreamStream\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18gcp.planton.dev/v1alpha1R\n" +
	"apiVersion\x12.\n" +
	"\x04kind\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\n" +
	"\x13GcpDatastreamStreamR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12a\n" +
	"\x04spec\x18\x04 \x01(\v2E.dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12_\n" +
	"\x06status\x18\x05 \x01(\v2G.dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStatusR\x06status\"\x84\x01\n" +
	"\x19GcpDatastreamStreamStatus\x12g\n" +
	"\aoutputs\x18\x01 \x01(\v2M.dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStackOutputsR\aoutputsB\xf4\x02\n" +
	"0com.dev.planton.gcp.gcpdatastreamstream.v1alpha1B\bApiProtoP\x01Zagithub.com/plantonhq/planton/catalog/gcp/gcpdatastreamstream/v1alpha1;gcpdatastreamstreamv1alpha1\xa2\x02\x04DPGG\xaa\x02,Dev.Planton.Gcp.Gcpdatastreamstream.V1alpha1\xca\x02,Dev\\Planton\\Gcp\\Gcpdatastreamstream\\V1alpha1\xe2\x028Dev\\Planton\\Gcp\\Gcpdatastreamstream\\V1alpha1\\GPBMetadata\xea\x020Dev::Planton::Gcp::Gcpdatastreamstream::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDescData
}

var file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_goTypes = []any{
	(*GcpDatastreamStream)(nil),             // 0: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStream
	(*GcpDatastreamStreamStatus)(nil),       // 1: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStatus
	(*shared.CloudResourceMetadata)(nil),    // 2: dev.planton.shared.CloudResourceMetadata
	(*GcpDatastreamStreamSpec)(nil),         // 3: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamSpec
	(*GcpDatastreamStreamStackOutputs)(nil), // 4: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStackOutputs
}
var file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStream.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStream.spec:type_name -> dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamSpec
	1, // 2: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStream.status:type_name -> dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStatus
	4, // 3: dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStatus.outputs:type_name -> dev.planton.gcp.gcpdatastreamstream.v1alpha1.GcpDatastreamStreamStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_init() }
func file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_init() {
	if File_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_outputs_proto_init()
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDesc), len(file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto = out.File
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_goTypes = nil
	file_catalog_gcp_gcpdatastreamstream_v1alpha1_api_proto_depIdxs = nil
}
