apiVersion: auth0.planton.dev/v1alpha1
kind: Auth0User
metadata:
  name: support-oncall
  org: example-org
  env: production
spec:
  connectionName:
    valueFrom:
      kind: Auth0Connection
      name: email
      fieldPath: status.outputs.name
  email: support-oncall@example.com
  name: Support on-call
  emailVerified: true
  passwordless: true
  userMetadata:
    locale: en-US
  roles:
    - valueFrom:
        kind: Auth0Role
        name: support-engineer
        fieldPath: status.outputs.id
