syntax = "proto3";

package dev.planton.aws.awssagemakermodel.v1alpha1;

import "catalog/aws/awssagemakermodel/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSagemakerModelIacInput is the input for the IaC modules that
// deploy the SageMaker model.
message AwsSagemakerModelIacInput {
  // target is the AwsSagemakerModel resource to deploy.
  AwsSagemakerModel target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
