syntax = "proto3";

package dev.planton.kubernetes.kubernetestelemetry.v1alpha1;

import "catalog/kubernetes/kubernetestelemetry/v1alpha1/api.proto";
import "catalog/kubernetes/provider.proto";

// KubernetesTelemetryIacInput provides the inputs for creating the Telemetry
// resource on a Kubernetes cluster.
message KubernetesTelemetryIacInput {
  // target infra-component
  KubernetesTelemetry target = 1;
  // provider-config
  dev.planton.kubernetes.KubernetesProviderConfig provider_config = 2;
}
