// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/oci/ocivcn/v1/spec.proto

package ocivcnv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/openmcf/apis/org/openmcf/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OciVcnSpec defines the specification for an Oracle Cloud Infrastructure
// Virtual Cloud Network (VCN) and its optional gateway sub-resources.
//
// A VCN is the foundational networking construct in OCI, analogous to an AWS
// VPC. It provides an isolated virtual network within a compartment and
// supports multiple CIDR blocks, DNS resolution, and IPv6.
//
// Gateway resources (Internet, NAT, Service) are bundled into this component
// because they are tightly coupled to the VCN lifecycle and rarely useful on
// their own. Each gateway is controlled by a boolean toggle and only created
// when enabled.
type OciVcnSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OCID of the compartment where the VCN and its gateways will be created.
	CompartmentId *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=compartment_id,json=compartmentId,proto3" json:"compartment_id,omitempty"`
	// IPv4 CIDR blocks for the VCN. At least one is required.
	// OCI supports multiple non-overlapping CIDRs per VCN (e.g. ["10.0.0.0/16", "172.16.0.0/16"]).
	// Each block must be between /16 and /30.
	CidrBlocks []string `protobuf:"bytes,2,rep,name=cidr_blocks,json=cidrBlocks,proto3" json:"cidr_blocks,omitempty"`
	// Human-readable name for the VCN shown in the OCI Console.
	// Falls back to metadata.name if not provided.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// DNS label for the VCN. Enables DNS hostnames within the VCN.
	// Must be alphanumeric, start with a letter, and be at most 15 characters.
	// When set, the VCN domain becomes: <dns_label>.oraclevcn.com
	DnsLabel string `protobuf:"bytes,4,opt,name=dns_label,json=dnsLabel,proto3" json:"dns_label,omitempty"`
	// When true, allocate an Oracle-assigned /56 IPv6 GUA prefix for the VCN.
	IsIpv6Enabled bool `protobuf:"varint,5,opt,name=is_ipv6_enabled,json=isIpv6Enabled,proto3" json:"is_ipv6_enabled,omitempty"`
	// When true, create an Internet Gateway attached to this VCN.
	// Required for resources that need direct inbound/outbound internet access.
	IsInternetGatewayEnabled bool `protobuf:"varint,6,opt,name=is_internet_gateway_enabled,json=isInternetGatewayEnabled,proto3" json:"is_internet_gateway_enabled,omitempty"`
	// When true, create a NAT Gateway attached to this VCN.
	// Allows private resources to initiate outbound internet connections
	// without exposing them to inbound traffic.
	IsNatGatewayEnabled bool `protobuf:"varint,7,opt,name=is_nat_gateway_enabled,json=isNatGatewayEnabled,proto3" json:"is_nat_gateway_enabled,omitempty"`
	// When true, create a Service Gateway attached to this VCN.
	// Provides private access to OCI services (Object Storage, etc.) without
	// traffic leaving the Oracle network. The gateway is automatically
	// configured for "All Services in Oracle Services Network".
	IsServiceGatewayEnabled bool `protobuf:"varint,8,opt,name=is_service_gateway_enabled,json=isServiceGatewayEnabled,proto3" json:"is_service_gateway_enabled,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OciVcnSpec) Reset() {
	*x = OciVcnSpec{}
	mi := &file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OciVcnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OciVcnSpec) ProtoMessage() {}

func (x *OciVcnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OciVcnSpec.ProtoReflect.Descriptor instead.
func (*OciVcnSpec) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *OciVcnSpec) GetCompartmentId() *v1.StringValueOrRef {
	if x != nil {
		return x.CompartmentId
	}
	return nil
}

func (x *OciVcnSpec) GetCidrBlocks() []string {
	if x != nil {
		return x.CidrBlocks
	}
	return nil
}

func (x *OciVcnSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OciVcnSpec) GetDnsLabel() string {
	if x != nil {
		return x.DnsLabel
	}
	return ""
}

func (x *OciVcnSpec) GetIsIpv6Enabled() bool {
	if x != nil {
		return x.IsIpv6Enabled
	}
	return false
}

func (x *OciVcnSpec) GetIsInternetGatewayEnabled() bool {
	if x != nil {
		return x.IsInternetGatewayEnabled
	}
	return false
}

func (x *OciVcnSpec) GetIsNatGatewayEnabled() bool {
	if x != nil {
		return x.IsNatGatewayEnabled
	}
	return false
}

func (x *OciVcnSpec) GetIsServiceGatewayEnabled() bool {
	if x != nil {
		return x.IsServiceGatewayEnabled
	}
	return false
}

var File_org_openmcf_provider_oci_ocivcn_v1_spec_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDesc = "" +
	"\n" +
	"-org/openmcf/provider/oci/ocivcn/v1/spec.proto\x12\"org.openmcf.provider.oci.ocivcn.v1\x1a\x1bbuf/validate/validate.proto\x1a2org/openmcf/shared/foreignkey/v1/foreign_key.proto\"\xd9\x03\n" +
	"\n" +
	"OciVcnSpec\x12\x86\x01\n" +
	"\x0ecompartment_id\x18\x01 \x01(\v22.org.openmcf.shared.foreignkey.v1.StringValueOrRefB+\xbaH\x03\xc8\x01\x01\x88\xd4a\xe7\x19\x92\xd4a\x1cstatus.outputs.compartmentIdR\rcompartmentId\x12)\n" +
	"\vcidr_blocks\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"cidrBlocks\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tdns_label\x18\x04 \x01(\tR\bdnsLabel\x12&\n" +
	"\x0fis_ipv6_enabled\x18\x05 \x01(\bR\risIpv6Enabled\x12=\n" +
	"\x1bis_internet_gateway_enabled\x18\x06 \x01(\bR\x18isInternetGatewayEnabled\x123\n" +
	"\x16is_nat_gateway_enabled\x18\a \x01(\bR\x13isNatGatewayEnabled\x12;\n" +
	"\x1ais_service_gateway_enabled\x18\b \x01(\bR\x17isServiceGatewayEnabledB\xb1\x02\n" +
	"&com.org.openmcf.provider.oci.ocivcn.v1B\tSpecProtoP\x01ZMgithub.com/plantonhq/openmcf/apis/org/openmcf/provider/oci/ocivcn/v1;ocivcnv1\xa2\x02\x05OOPOO\xaa\x02\"Org.Openmcf.Provider.Oci.Ocivcn.V1\xca\x02\"Org\\Openmcf\\Provider\\Oci\\Ocivcn\\V1\xe2\x02.Org\\Openmcf\\Provider\\Oci\\Ocivcn\\V1\\GPBMetadata\xea\x02'Org::Openmcf::Provider::Oci::Ocivcn::V1b\x06proto3"

var (
	file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescData []byte
)

func file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDesc), len(file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDesc)))
	})
	return file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDescData
}

var file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_goTypes = []any{
	(*OciVcnSpec)(nil),          // 0: org.openmcf.provider.oci.ocivcn.v1.OciVcnSpec
	(*v1.StringValueOrRef)(nil), // 1: org.openmcf.shared.foreignkey.v1.StringValueOrRef
}
var file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_depIdxs = []int32{
	1, // 0: org.openmcf.provider.oci.ocivcn.v1.OciVcnSpec.compartment_id:type_name -> org.openmcf.shared.foreignkey.v1.StringValueOrRef
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_init() }
func file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_init() {
	if File_org_openmcf_provider_oci_ocivcn_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDesc), len(file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_oci_ocivcn_v1_spec_proto = out.File
	file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_goTypes = nil
	file_org_openmcf_provider_oci_ocivcn_v1_spec_proto_depIdxs = nil
}
