// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/aws/awsnatgateway/v1/spec.proto

package awsnatgatewayv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/openmcf/apis/org/openmcf/shared/foreignkey/v1"
	_ "github.com/plantonhq/openmcf/apis/org/openmcf/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsNatGatewaySpec defines a NAT gateway for an AWS Virtual Private Cloud (VPC).
//
// A NAT (network address translation) gateway gives instances in a private
// subnet outbound access without exposing them to inbound connections from the
// internet. It is an AWS-managed, highly-available service that lives in a
// single subnet and is referenced by other subnets' route tables as the target
// of their default route.
//
// There are two kinds, selected by connectivity_type:
//   - public  (the common case): the gateway lives in a PUBLIC subnet (one that
//     routes to an internet gateway) and is fronted by an Elastic IP. Private
//     subnets send 0.0.0.0/0 to it to reach the internet outbound-only.
//   - private: the gateway lives in any subnet and has no Elastic IP. It enables
//     outbound communication to other VPCs or an on-premises network (via a
//     transit/VPN/peering path) while keeping instances unreachable from those
//     networks.
//
// A NAT gateway does not, by itself, route anything: a private subnet becomes
// NAT-egressed only when its route table sends a default route
// (target_type = nat_gateway) to this gateway. The Elastic IP is composed by
// reference (allocation_id -> AwsElasticIp), never embedded, so the address has
// its own lifecycle and can be reasoned about as a first-class node.
type AwsNatGatewaySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AWS region the NAT gateway is created in. Must match the region of the
	// subnet it lives in. Example: "us-west-2", "eu-west-1". This drives provider
	// construction, so it is required even though the gateway logically inherits
	// the subnet's region.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// How the gateway connects: "public" (default) or "private".
	//
	//   - "public": the gateway is placed in a public subnet and assigned an Elastic
	//     IP (allocation_id is required); it provides outbound internet access for
	//     private subnets that route to it.
	//   - "private": the gateway has no Elastic IP and provides outbound access only
	//     to other private networks (peered/transit/VPN), never the internet.
	//
	// AWS's own default for a new NAT gateway is public; this field is required so
	// the choice is always explicit (an empty value is rejected) and the two IaC
	// engines never need to invent a default. ForceNew: changing it replaces the
	// gateway.
	ConnectivityType string `protobuf:"bytes,2,opt,name=connectivity_type,json=connectivityType,proto3" json:"connectivity_type,omitempty"`
	// The subnet the NAT gateway is created in. Supply a literal subnet-id or
	// reference an AwsSubnet and the platform resolves its subnet_id output. For a
	// public gateway this must be a PUBLIC subnet (one whose route table reaches an
	// internet gateway); for a private gateway any subnet works. Immutable:
	// changing the subnet replaces the gateway.
	SubnetId *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// The Elastic IP allocation that gives a public gateway its stable outbound
	// address. Supply a literal eipalloc-id or reference an AwsElasticIp and the
	// platform resolves its allocation_id output. Required when
	// connectivity_type is public; must be empty when it is private. ForceNew:
	// changing it replaces the gateway.
	AllocationId *v1.StringValueOrRef `protobuf:"bytes,4,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	// The private IPv4 address to assign to a private gateway from the subnet's
	// range. Only valid when connectivity_type is private; leave empty to let AWS
	// choose. ForceNew: changing it replaces the gateway.
	PrivateIp string `protobuf:"bytes,5,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	// Additional Elastic IP allocations to attach to a public gateway, increasing
	// the number of available source ports for very high-throughput egress. Each
	// entry is a literal eipalloc-id or a reference to an AwsElasticIp. Only valid
	// when connectivity_type is public.
	SecondaryAllocationIds []*v1.StringValueOrRef `protobuf:"bytes,6,rep,name=secondary_allocation_ids,json=secondaryAllocationIds,proto3" json:"secondary_allocation_ids,omitempty"`
	// Additional private IPv4 addresses to assign to a private gateway, increasing
	// the number of available source ports. Only valid when connectivity_type is
	// private. Mutually exclusive with secondary_private_ip_address_count.
	SecondaryPrivateIpAddresses []string `protobuf:"bytes,7,rep,name=secondary_private_ip_addresses,json=secondaryPrivateIpAddresses,proto3" json:"secondary_private_ip_addresses,omitempty"`
	// Number of additional private IPv4 addresses to let AWS assign to a private
	// gateway (an alternative to listing them explicitly). Only valid when
	// connectivity_type is private. Mutually exclusive with
	// secondary_private_ip_addresses.
	SecondaryPrivateIpAddressCount int32 `protobuf:"varint,8,opt,name=secondary_private_ip_address_count,json=secondaryPrivateIpAddressCount,proto3" json:"secondary_private_ip_address_count,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AwsNatGatewaySpec) Reset() {
	*x = AwsNatGatewaySpec{}
	mi := &file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsNatGatewaySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsNatGatewaySpec) ProtoMessage() {}

func (x *AwsNatGatewaySpec) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsNatGatewaySpec.ProtoReflect.Descriptor instead.
func (*AwsNatGatewaySpec) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AwsNatGatewaySpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsNatGatewaySpec) GetConnectivityType() string {
	if x != nil {
		return x.ConnectivityType
	}
	return ""
}

func (x *AwsNatGatewaySpec) GetSubnetId() *v1.StringValueOrRef {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *AwsNatGatewaySpec) GetAllocationId() *v1.StringValueOrRef {
	if x != nil {
		return x.AllocationId
	}
	return nil
}

func (x *AwsNatGatewaySpec) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *AwsNatGatewaySpec) GetSecondaryAllocationIds() []*v1.StringValueOrRef {
	if x != nil {
		return x.SecondaryAllocationIds
	}
	return nil
}

func (x *AwsNatGatewaySpec) GetSecondaryPrivateIpAddresses() []string {
	if x != nil {
		return x.SecondaryPrivateIpAddresses
	}
	return nil
}

func (x *AwsNatGatewaySpec) GetSecondaryPrivateIpAddressCount() int32 {
	if x != nil {
		return x.SecondaryPrivateIpAddressCount
	}
	return 0
}

var File_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDesc = "" +
	"\n" +
	"4org/openmcf/provider/aws/awsnatgateway/v1/spec.proto\x12)org.openmcf.provider.aws.awsnatgateway.v1\x1a\x1bbuf/validate/validate.proto\x1a2org/openmcf/shared/foreignkey/v1/foreign_key.proto\x1a(org/openmcf/shared/options/options.proto\"\x85\x0e\n" +
	"\x11AwsNatGatewaySpec\x12\x1f\n" +
	"\x06region\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06region\x12\xa8\x01\n" +
	"\x11connectivity_type\x18\x02 \x01(\tB{\xbaHn\xba\x01k\n" +
	"\x17connectivity_type_valid\x121connectivity_type must be one of: public, private\x1a\x1dthis in ['public', 'private']\x92\xa6\x1d\x06publicR\x10connectivityType\x12x\n" +
	"\tsubnet_id\x18\x03 \x01(\v22.org.openmcf.shared.foreignkey.v1.StringValueOrRefB'\xbaH\x03\xc8\x01\x01\x88\xd4a\x9c\x02\x92\xd4a\x18status.outputs.subnet_idR\bsubnetId\x12~\n" +
	"\rallocation_id\x18\x04 \x01(\v22.org.openmcf.shared.foreignkey.v1.StringValueOrRefB%\x88\xd4a\x99\x02\x92\xd4a\x1cstatus.outputs.allocation_idR\fallocationId\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x05 \x01(\tR\tprivateIp\x12\x93\x01\n" +
	"\x18secondary_allocation_ids\x18\x06 \x03(\v22.org.openmcf.shared.foreignkey.v1.StringValueOrRefB%\x88\xd4a\x99\x02\x92\xd4a\x1cstatus.outputs.allocation_idR\x16secondaryAllocationIds\x12C\n" +
	"\x1esecondary_private_ip_addresses\x18\a \x03(\tR\x1bsecondaryPrivateIpAddresses\x12J\n" +
	"\"secondary_private_ip_address_count\x18\b \x01(\x05R\x1esecondaryPrivateIpAddressCount:\xe3\a\xbaH\xdf\a\x1a\xc5\x01\n" +
	"\x1dpublic_requires_allocation_id\x12eallocation_id is required when connectivity_type is public (a public NAT gateway needs an Elastic IP)\x1a=this.connectivity_type != 'public' || has(this.allocation_id)\x1a\xe3\x01\n" +
	"\x13private_forbids_eip\x12\\allocation_id and secondary_allocation_ids are not allowed when connectivity_type is private\x1anthis.connectivity_type != 'private' || (!has(this.allocation_id) && this.secondary_allocation_ids.size() == 0)\x1a\xcc\x02\n" +
	"!public_forbids_private_addressing\x12\x83\x01private_ip, secondary_private_ip_addresses, and secondary_private_ip_address_count are only valid when connectivity_type is private\x1a\xa0\x01this.connectivity_type != 'public' || (this.private_ip == '' && this.secondary_private_ip_addresses.size() == 0 && this.secondary_private_ip_address_count == 0)\x1a\xdf\x01\n" +
	"\x1esecondary_private_ip_exclusive\x12\\secondary_private_ip_addresses and secondary_private_ip_address_count are mutually exclusive\x1a_this.secondary_private_ip_addresses.size() == 0 || this.secondary_private_ip_address_count == 0B\xe2\x02\n" +
	"-com.org.openmcf.provider.aws.awsnatgateway.v1B\tSpecProtoP\x01Z[github.com/plantonhq/openmcf/apis/org/openmcf/provider/aws/awsnatgateway/v1;awsnatgatewayv1\xa2\x02\x05OOPAA\xaa\x02)Org.Openmcf.Provider.Aws.Awsnatgateway.V1\xca\x02)Org\\Openmcf\\Provider\\Aws\\Awsnatgateway\\V1\xe2\x025Org\\Openmcf\\Provider\\Aws\\Awsnatgateway\\V1\\GPBMetadata\xea\x02.Org::Openmcf::Provider::Aws::Awsnatgateway::V1b\x06proto3"

var (
	file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescData []byte
)

func file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDesc), len(file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDesc)))
	})
	return file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDescData
}

var file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_goTypes = []any{
	(*AwsNatGatewaySpec)(nil),   // 0: org.openmcf.provider.aws.awsnatgateway.v1.AwsNatGatewaySpec
	(*v1.StringValueOrRef)(nil), // 1: org.openmcf.shared.foreignkey.v1.StringValueOrRef
}
var file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_depIdxs = []int32{
	1, // 0: org.openmcf.provider.aws.awsnatgateway.v1.AwsNatGatewaySpec.subnet_id:type_name -> org.openmcf.shared.foreignkey.v1.StringValueOrRef
	1, // 1: org.openmcf.provider.aws.awsnatgateway.v1.AwsNatGatewaySpec.allocation_id:type_name -> org.openmcf.shared.foreignkey.v1.StringValueOrRef
	1, // 2: org.openmcf.provider.aws.awsnatgateway.v1.AwsNatGatewaySpec.secondary_allocation_ids:type_name -> org.openmcf.shared.foreignkey.v1.StringValueOrRef
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_init() }
func file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_init() {
	if File_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDesc), len(file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto = out.File
	file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_goTypes = nil
	file_org_openmcf_provider_aws_awsnatgateway_v1_spec_proto_depIdxs = nil
}
