syntax = "proto3";

package dev.planton.aws.awsbudget.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsbudget/v1alpha1/outputs.proto";
import "catalog/aws/awsbudget/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsBudget {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsBudget'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsBudgetSpec spec = 4 [(buf.validate.field).required = true];
  AwsBudgetStatus status = 5;
}

message AwsBudgetStatus {
  AwsBudgetOutputs outputs = 1;
}
