syntax = "proto3";

package dev.planton.azure.azuremonitordiagnosticsetting.v1alpha1;

import "catalog/azure/azuremonitordiagnosticsetting/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureMonitorDiagnosticSettingIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureMonitorDiagnosticSettingIacInput {
  // the catalog object to deploy to be deployed
  AzureMonitorDiagnosticSetting target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
