load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "locals.go",
        "main.go",
        "namespace.go",
        "outputs.go",
        "solr_cloud.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/kubernetes/kubernetessolr/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/kubernetes",
        "//catalog/kubernetes/kubernetessolr/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/kubernetes/kuberneteslabelkeys",
        "//pkg/iac/pulumi/pulumimodule/provider/kubernetes/pulumikubernetesprovider",
        "//pkg/kubernetes/kubernetestypes/solroperator/kubernetes/solr/v1beta1",
        "//shared/catalogkind",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/core/v1:core",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/meta/v1:meta",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
