// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/oci/ociloadbalancer/v1/api.proto

package ociloadbalancerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/openmcf/apis/org/openmcf/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OciLoadBalancer is the top-level resource representing an Oracle Cloud
// Infrastructure Application Load Balancer (Layer 7).
type OciLoadBalancer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *OciLoadBalancerSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *OciLoadBalancerStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OciLoadBalancer) Reset() {
	*x = OciLoadBalancer{}
	mi := &file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OciLoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OciLoadBalancer) ProtoMessage() {}

func (x *OciLoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OciLoadBalancer.ProtoReflect.Descriptor instead.
func (*OciLoadBalancer) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *OciLoadBalancer) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OciLoadBalancer) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OciLoadBalancer) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OciLoadBalancer) GetSpec() *OciLoadBalancerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *OciLoadBalancer) GetStatus() *OciLoadBalancerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// OciLoadBalancerStatus holds the outputs produced by deploying an
// OciLoadBalancer.
type OciLoadBalancerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *OciLoadBalancerStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OciLoadBalancerStatus) Reset() {
	*x = OciLoadBalancerStatus{}
	mi := &file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OciLoadBalancerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OciLoadBalancerStatus) ProtoMessage() {}

func (x *OciLoadBalancerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OciLoadBalancerStatus.ProtoReflect.Descriptor instead.
func (*OciLoadBalancerStatus) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *OciLoadBalancerStatus) GetOutputs() *OciLoadBalancerStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDesc = "" +
	"\n" +
	"5org/openmcf/provider/oci/ociloadbalancer/v1/api.proto\x12+org.openmcf.provider.oci.ociloadbalancer.v1\x1a\x1bbuf/validate/validate.proto\x1a6org/openmcf/provider/oci/ociloadbalancer/v1/spec.proto\x1a?org/openmcf/provider/oci/ociloadbalancer/v1/stack_outputs.proto\x1a!org/openmcf/shared/metadata.proto\"\x82\x03\n" +
	"\x0fOciLoadBalancer\x12:\n" +
	"\vapi_version\x18\x01 \x01(\tB\x19\xbaH\x16r\x14\n" +
	"\x12oci.openmcf.org/v1R\n" +
	"apiVersion\x12*\n" +
	"\x04kind\x18\x02 \x01(\tB\x16\xbaH\x13r\x11\n" +
	"\x0fOciLoadBalancerR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).org.openmcf.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12\\\n" +
	"\x04spec\x18\x04 \x01(\v2@.org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12Z\n" +
	"\x06status\x18\x05 \x01(\v2B.org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStatusR\x06status\"{\n" +
	"\x15OciLoadBalancerStatus\x12b\n" +
	"\aoutputs\x18\x01 \x01(\v2H.org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStackOutputsR\aoutputsB\xef\x02\n" +
	"/com.org.openmcf.provider.oci.ociloadbalancer.v1B\bApiProtoP\x01Z_github.com/plantonhq/openmcf/apis/org/openmcf/provider/oci/ociloadbalancer/v1;ociloadbalancerv1\xa2\x02\x05OOPOO\xaa\x02+Org.Openmcf.Provider.Oci.Ociloadbalancer.V1\xca\x02+Org\\Openmcf\\Provider\\Oci\\Ociloadbalancer\\V1\xe2\x027Org\\Openmcf\\Provider\\Oci\\Ociloadbalancer\\V1\\GPBMetadata\xea\x020Org::Openmcf::Provider::Oci::Ociloadbalancer::V1b\x06proto3"

var (
	file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescData []byte
)

func file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDesc), len(file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDesc)))
	})
	return file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDescData
}

var file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_goTypes = []any{
	(*OciLoadBalancer)(nil),              // 0: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancer
	(*OciLoadBalancerStatus)(nil),        // 1: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStatus
	(*shared.CloudResourceMetadata)(nil), // 2: org.openmcf.shared.CloudResourceMetadata
	(*OciLoadBalancerSpec)(nil),          // 3: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerSpec
	(*OciLoadBalancerStackOutputs)(nil),  // 4: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStackOutputs
}
var file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_depIdxs = []int32{
	2, // 0: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancer.metadata:type_name -> org.openmcf.shared.CloudResourceMetadata
	3, // 1: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancer.spec:type_name -> org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerSpec
	1, // 2: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancer.status:type_name -> org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStatus
	4, // 3: org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStatus.outputs:type_name -> org.openmcf.provider.oci.ociloadbalancer.v1.OciLoadBalancerStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_init() }
func file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_init() {
	if File_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto != nil {
		return
	}
	file_org_openmcf_provider_oci_ociloadbalancer_v1_spec_proto_init()
	file_org_openmcf_provider_oci_ociloadbalancer_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDesc), len(file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto = out.File
	file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_goTypes = nil
	file_org_openmcf_provider_oci_ociloadbalancer_v1_api_proto_depIdxs = nil
}
