syntax = "proto3";

package dev.planton.aws.awssagemakerpipeline.v1alpha1;

import "catalog/aws/awssagemakerpipeline/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSagemakerPipelineIacInput is the input for the IaC modules that
// deploy the pipeline.
message AwsSagemakerPipelineIacInput {
  // target is the AwsSagemakerPipeline resource to deploy.
  AwsSagemakerPipeline target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
