syntax = "proto3";

package dev.planton.azure.azurelocalnetworkgateway.v1alpha1;

import "catalog/azure/azurelocalnetworkgateway/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureLocalNetworkGatewayIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and
// Azure provider credentials.
message AzureLocalNetworkGatewayIacInput {
  // The local network gateway resource to deploy.
  AzureLocalNetworkGateway target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
