load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cataloglogo",
    srcs = [
        "baseline.go",
        "cataloglogo.go",
    ],
    importpath = "github.com/plantonhq/planton/pkg/cataloglogo",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/catalogkindreflect",
        "//shared/catalogkind",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

go_test(
    name = "cataloglogo_test",
    srcs = ["cataloglogo_test.go"],
    data = ["baseline.yaml"],
    embed = [":cataloglogo"],
)
