apiVersion: kubernetes.planton.dev/v1
kind: KubernetesTcpRoute
metadata:
  name: my-tcp-route
spec:
  namespace:
    value: app-ns
  parentRefs:
    - name: <gateway-name>
      sectionName: tcp
  rules:
    - backendRefs:
        - name: <service-name>
          port: <service-port>
