syntax = "proto3";

package dev.planton.aws.awsvpcpeering.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsvpcpeering/v1alpha1/outputs.proto";
import "catalog/aws/awsvpcpeering/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsVpcPeering {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsVpcPeering'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsVpcPeeringSpec spec = 4 [(buf.validate.field).required = true];
  AwsVpcPeeringStatus status = 5;
}

message AwsVpcPeeringStatus {
  AwsVpcPeeringOutputs outputs = 1;
}
