syntax = "proto3";

package dev.planton.aws.awsroute53zone.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsroute53zone/v1alpha1/outputs.proto";
import "catalog/aws/awsroute53zone/v1alpha1/spec.proto";
import "shared/metadata.proto";

//aws-route53-zone
message AwsRoute53Zone {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AwsRoute53Zone'];

  // metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //aws-route53-zone spec
  AwsRoute53ZoneSpec spec = 4 [(buf.validate.field).required = true];

  //aws-route53-zone status
  AwsRoute53ZoneStatus status = 5;
}

// Status for the AWS Route53 Zone
message AwsRoute53ZoneStatus {
  //outputs
  //  outputs
  AwsRoute53ZoneOutputs outputs = 1;
}
