// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azurevirtualnetworkgateway/v1alpha1/input.proto

package azurevirtualnetworkgatewayv1alpha1

import (
	azure "github.com/plantonhq/planton/catalog/azure"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureVirtualNetworkGatewayIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and
// Azure provider credentials.
type AzureVirtualNetworkGatewayIacInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The virtual network gateway resource to deploy.
	Target *AzureVirtualNetworkGateway `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Azure provider configuration (credentials).
	ProviderConfig *azure.AzureProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzureVirtualNetworkGatewayIacInput) Reset() {
	*x = AzureVirtualNetworkGatewayIacInput{}
	mi := &file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureVirtualNetworkGatewayIacInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureVirtualNetworkGatewayIacInput) ProtoMessage() {}

func (x *AzureVirtualNetworkGatewayIacInput) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureVirtualNetworkGatewayIacInput.ProtoReflect.Descriptor instead.
func (*AzureVirtualNetworkGatewayIacInput) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescGZIP(), []int{0}
}

func (x *AzureVirtualNetworkGatewayIacInput) GetTarget() *AzureVirtualNetworkGateway {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AzureVirtualNetworkGatewayIacInput) GetProviderConfig() *azure.AzureProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

var File_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto protoreflect.FileDescriptor

const file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDesc = "" +
	"\n" +
	"=catalog/azure/azurevirtualnetworkgateway/v1alpha1/input.proto\x125dev.planton.azure.azurevirtualnetworkgateway.v1alpha1\x1a;catalog/azure/azurevirtualnetworkgateway/v1alpha1/api.proto\x1a\x1ccatalog/azure/provider.proto\"\xe0\x01\n" +
	"\"AzureVirtualNetworkGatewayIacInput\x12i\n" +
	"\x06target\x18\x01 \x01(\v2Q.dev.planton.azure.azurevirtualnetworkgateway.v1alpha1.AzureVirtualNetworkGatewayR\x06target\x12O\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2&.dev.planton.azure.AzureProviderConfigR\x0eproviderConfigB\xb3\x03\n" +
	"9com.dev.planton.azure.azurevirtualnetworkgateway.v1alpha1B\n" +
	"InputProtoP\x01Zqgithub.com/plantonhq/planton/catalog/azure/azurevirtualnetworkgateway/v1alpha1;azurevirtualnetworkgatewayv1alpha1\xa2\x02\x04DPAA\xaa\x025Dev.Planton.Azure.Azurevirtualnetworkgateway.V1alpha1\xca\x025Dev\\Planton\\Azure\\Azurevirtualnetworkgateway\\V1alpha1\xe2\x02ADev\\Planton\\Azure\\Azurevirtualnetworkgateway\\V1alpha1\\GPBMetadata\xea\x029Dev::Planton::Azure::Azurevirtualnetworkgateway::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescOnce sync.Once
	file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescData []byte
)

func file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescGZIP() []byte {
	file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDesc), len(file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDesc)))
	})
	return file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDescData
}

var file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_goTypes = []any{
	(*AzureVirtualNetworkGatewayIacInput)(nil), // 0: dev.planton.azure.azurevirtualnetworkgateway.v1alpha1.AzureVirtualNetworkGatewayIacInput
	(*AzureVirtualNetworkGateway)(nil),         // 1: dev.planton.azure.azurevirtualnetworkgateway.v1alpha1.AzureVirtualNetworkGateway
	(*azure.AzureProviderConfig)(nil),          // 2: dev.planton.azure.AzureProviderConfig
}
var file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_depIdxs = []int32{
	1, // 0: dev.planton.azure.azurevirtualnetworkgateway.v1alpha1.AzureVirtualNetworkGatewayIacInput.target:type_name -> dev.planton.azure.azurevirtualnetworkgateway.v1alpha1.AzureVirtualNetworkGateway
	2, // 1: dev.planton.azure.azurevirtualnetworkgateway.v1alpha1.AzureVirtualNetworkGatewayIacInput.provider_config:type_name -> dev.planton.azure.AzureProviderConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_init() }
func file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_init() {
	if File_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto != nil {
		return
	}
	file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDesc), len(file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_depIdxs,
		MessageInfos:      file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_msgTypes,
	}.Build()
	File_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto = out.File
	file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_goTypes = nil
	file_catalog_azure_azurevirtualnetworkgateway_v1alpha1_input_proto_depIdxs = nil
}
