load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "anatomy",
    srcs = [
        "anatomy.go",
        "baseline.go",
    ],
    importpath = "github.com/plantonhq/planton/pkg/anatomy",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/crkreflect",
        "//shared",
        "//shared/cloudresourcekind",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

go_test(
    name = "anatomy_test",
    srcs = ["anatomy_test.go"],
    embed = [":anatomy"],
)
