apiVersion: oci.planton.dev/v1
kind: OciFileSystem
metadata:
  name: my-shared-fs
spec:
  compartmentId:
    value: <compartment-ocid>
  availabilityDomain: <availability-domain>
  displayName: shared-fs
  mountTarget:
    subnetId:
      value: <private-subnet-ocid>
    displayName: shared-fs-mt
    hostnameLabel: sharedfs
  exports:
    - path: /shared
      exportOptions:
        - source: <subnet-cidr>
          access: read_write
          identitySquash: root_squash
          requirePrivilegedSourcePort: true
          anonymousUid: 65534
          anonymousGid: 65534
