apiVersion: aws.planton.dev/v1
kind: AwsKinesisStreamConsumer
metadata:
  name: analytics-consumer
spec:
  region: <aws-region>
  streamArn:
    valueFrom:
      kind: AwsKinesisStream
      name: my-stream
      fieldPath: status.outputs.stream_arn
