apiVersion: alicloud.planton.dev/v1
kind: AliCloudNasFileSystem
metadata:
  name: my-nas
spec:
  region: <alibaba-cloud-region>
  protocolType: NFS
  storageType: Performance
  vpcId: <vpc-id>
  vswitchId: <vswitch-id>
