apiVersion: kubernetes.planton.dev/v1
kind: KubernetesRookCephOperator
metadata:
  name: my-rook-ceph-operator
spec:
  namespace:
    value: rook-ceph
  createNamespace: true
  container:
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
