// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/openstack/openstackcomputekeypair/v1/api.proto

package openstackcomputekeypairv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/openmcf/apis/org/openmcf/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenStackComputeKeypair is a Kubernetes Resource Model (KRM) style resource for managing
// SSH keypairs in OpenStack Nova (Compute service).
//
// Keypairs are used to authenticate SSH access to compute instances. This component supports
// both importing existing public keys and generating new keypairs via OpenStack.
type OpenStackComputeKeypair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *OpenStackComputeKeypairSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *OpenStackComputeKeypairStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStackComputeKeypair) Reset() {
	*x = OpenStackComputeKeypair{}
	mi := &file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStackComputeKeypair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStackComputeKeypair) ProtoMessage() {}

func (x *OpenStackComputeKeypair) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStackComputeKeypair.ProtoReflect.Descriptor instead.
func (*OpenStackComputeKeypair) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *OpenStackComputeKeypair) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OpenStackComputeKeypair) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OpenStackComputeKeypair) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OpenStackComputeKeypair) GetSpec() *OpenStackComputeKeypairSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *OpenStackComputeKeypair) GetStatus() *OpenStackComputeKeypairStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// OpenStackComputeKeypairStatus represents the observed state of an OpenStack compute keypair.
type OpenStackComputeKeypairStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs from the IaC deployment
	Outputs       *OpenStackComputeKeypairStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStackComputeKeypairStatus) Reset() {
	*x = OpenStackComputeKeypairStatus{}
	mi := &file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStackComputeKeypairStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStackComputeKeypairStatus) ProtoMessage() {}

func (x *OpenStackComputeKeypairStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStackComputeKeypairStatus.ProtoReflect.Descriptor instead.
func (*OpenStackComputeKeypairStatus) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *OpenStackComputeKeypairStatus) GetOutputs() *OpenStackComputeKeypairStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDesc = "" +
	"\n" +
	"Corg/openmcf/provider/openstack/openstackcomputekeypair/v1/api.proto\x129org.openmcf.provider.openstack.openstackcomputekeypair.v1\x1a\x1bbuf/validate/validate.proto\x1aDorg/openmcf/provider/openstack/openstackcomputekeypair/v1/spec.proto\x1aMorg/openmcf/provider/openstack/openstackcomputekeypair/v1/stack_outputs.proto\x1a!org/openmcf/shared/metadata.proto\"\xc4\x03\n" +
	"\x17OpenStackComputeKeypair\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18openstack.openmcf.org/v1R\n" +
	"apiVersion\x122\n" +
	"\x04kind\x18\x02 \x01(\tB\x1e\xbaH\x1br\x19\n" +
	"\x17OpenStackComputeKeypairR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).org.openmcf.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12r\n" +
	"\x04spec\x18\x04 \x01(\v2V.org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12p\n" +
	"\x06status\x18\x05 \x01(\v2X.org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStatusR\x06status\"\x99\x01\n" +
	"\x1dOpenStackComputeKeypairStatus\x12x\n" +
	"\aoutputs\x18\x01 \x01(\v2^.org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStackOutputsR\aoutputsB\xcb\x03\n" +
	"=com.org.openmcf.provider.openstack.openstackcomputekeypair.v1B\bApiProtoP\x01Zugithub.com/plantonhq/openmcf/apis/org/openmcf/provider/openstack/openstackcomputekeypair/v1;openstackcomputekeypairv1\xa2\x02\x05OOPOO\xaa\x029Org.Openmcf.Provider.Openstack.Openstackcomputekeypair.V1\xca\x029Org\\Openmcf\\Provider\\Openstack\\Openstackcomputekeypair\\V1\xe2\x02EOrg\\Openmcf\\Provider\\Openstack\\Openstackcomputekeypair\\V1\\GPBMetadata\xea\x02>Org::Openmcf::Provider::Openstack::Openstackcomputekeypair::V1b\x06proto3"

var (
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescData []byte
)

func file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDesc), len(file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDesc)))
	})
	return file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDescData
}

var file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_goTypes = []any{
	(*OpenStackComputeKeypair)(nil),             // 0: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypair
	(*OpenStackComputeKeypairStatus)(nil),       // 1: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStatus
	(*shared.CloudResourceMetadata)(nil),        // 2: org.openmcf.shared.CloudResourceMetadata
	(*OpenStackComputeKeypairSpec)(nil),         // 3: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairSpec
	(*OpenStackComputeKeypairStackOutputs)(nil), // 4: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStackOutputs
}
var file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_depIdxs = []int32{
	2, // 0: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypair.metadata:type_name -> org.openmcf.shared.CloudResourceMetadata
	3, // 1: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypair.spec:type_name -> org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairSpec
	1, // 2: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypair.status:type_name -> org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStatus
	4, // 3: org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStatus.outputs:type_name -> org.openmcf.provider.openstack.openstackcomputekeypair.v1.OpenStackComputeKeypairStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_init() }
func file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_init() {
	if File_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto != nil {
		return
	}
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_spec_proto_init()
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDesc), len(file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto = out.File
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_goTypes = nil
	file_org_openmcf_provider_openstack_openstackcomputekeypair_v1_api_proto_depIdxs = nil
}
