load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "manifest",
    srcs = [
        "envelope.go",
        "load_manifest.go",
        "manifest_validator.go",
        "multidoc.go",
        "print.go",
        "spec_extractor.go",
        "values_setter.go",
    ],
    importpath = "github.com/plantonhq/planton/internal/manifest",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/cli/ui",
        "//internal/cli/workspace",
        "//internal/manifest/manifestprotobuf",
        "//internal/manifest/protodefaults",
        "//pkg/catalogkindreflect",
        "//pkg/protobufyaml",
        "//pkg/ulidgen",
        "//pkg/yamldiag",
        "@build_buf_gen_go_bufbuild_protovalidate_protocolbuffers_go//buf/validate",
        "@build_buf_go_protovalidate//:protovalidate",
        "@com_github_fatih_color//:color",
        "@com_github_pkg_errors//:errors",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)

go_test(
    name = "manifest_test",
    srcs = [
        "load_manifest_test.go",
        "manifest_validator_test.go",
        "multidoc_test.go",
    ],
    embed = [":manifest"],
    deps = ["@com_github_stretchr_testify//assert"],
)
