syntax = "proto3";

package dev.planton.aws.awscloudwatchlogresourcepolicy.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awscloudwatchlogresourcepolicy/v1alpha1/outputs.proto";
import "catalog/aws/awscloudwatchlogresourcepolicy/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsCloudwatchLogResourcePolicy {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsCloudwatchLogResourcePolicy'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsCloudwatchLogResourcePolicySpec spec = 4 [(buf.validate.field).required = true];
  AwsCloudwatchLogResourcePolicyStatus status = 5;
}

message AwsCloudwatchLogResourcePolicyStatus {
  AwsCloudwatchLogResourcePolicyOutputs outputs = 1;
}
