syntax = "proto3";

package dev.planton.azure.azureeventhubcluster.v1alpha1;

import "catalog/azure/azureeventhubcluster/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureEventHubClusterIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureEventHubClusterIacInput {
  // the catalog object to deploy to be deployed
  AzureEventHubCluster target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
