syntax = "proto3";

package dev.planton.aws.awscloudwatchdashboard.v1alpha1;

import "catalog/aws/awscloudwatchdashboard/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsCloudwatchDashboardIacInput is the input for the IaC modules
// that manage a CloudWatch dashboard.
message AwsCloudwatchDashboardIacInput {
  // target is the AwsCloudwatchDashboard resource to deploy.
  AwsCloudwatchDashboard target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
