// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/azure/azurepublicip/v1/spec.proto

package azurepublicipv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/apis/dev/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/apis/dev/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **AzurePublicIpSpec** defines the configuration for creating an Azure Public IP Address.
//
// A Public IP Address is a static, routable IPv4 address in Azure that can be attached
// to load balancers, application gateways, NAT gateways, virtual machines, and other
// resources that need inbound connectivity from the internet. Public IPs are a
// foundational networking primitive -- they sit at Layer 0/1 of most Azure architectures
// and are referenced by higher-level resources via their resource ID.
//
// This component provisions Standard SKU public IPs with static allocation only.
// Azure retired the Basic SKU on September 30, 2025, and Standard SKU requires
// static allocation. These values are hardcoded in the IaC modules to keep the
// spec clean and avoid exposing deprecated or impossible configurations.
//
// This spec follows the 80/20 principle: exposing the essential fields that cover
// the vast majority of deployment scenarios while keeping the configuration minimal.
type AzurePublicIpSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Azure region where the Public IP will be created.
	// Examples: "eastus", "westus2", "westeurope", "southeastasia".
	// The Public IP must be in the same region as the resource it will be attached to
	// (load balancer, application gateway, NAT gateway, etc.).
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// The Azure Resource Group where the Public IP will be created.
	// Can be a literal string or a reference to an AzureResourceGroup output.
	ResourceGroup *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	// The name of the Public IP resource.
	// Must be unique within the resource group.
	// Allowed characters: alphanumeric, underscores, hyphens, and periods.
	// Must start with alphanumeric. Length: 1 to 80 characters.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// An optional DNS label that creates a domain name mapping for this Public IP.
	// When set, Azure creates an A record at: {label}.{region}.cloudapp.azure.com
	// pointing to this IP address. This provides a stable DNS name even if the IP
	// changes (though with Standard SKU + static allocation, IPs are persistent).
	//
	// Constraints:
	// - Must start with a lowercase letter
	// - Must end with a lowercase letter or digit
	// - May contain only lowercase letters, digits, and hyphens
	// - Length: 3 to 63 characters
	// - Must be unique within the Azure region
	DomainNameLabel string `protobuf:"bytes,4,opt,name=domain_name_label,json=domainNameLabel,proto3" json:"domain_name_label,omitempty"`
	// Availability zones for the Public IP.
	// Standard SKU public IPs can be zone-redundant (multiple zones) or zonal (single zone).
	// Valid values: "1", "2", "3" (availability zone numbers).
	// Examples:
	// - ["1", "2", "3"] for zone-redundant (recommended for production)
	// - ["1"] for zonal (pinned to zone 1)
	// - [] or omitted for no zone preference (Azure chooses)
	// Note: Zone support depends on the Azure region. Not all regions have 3 zones.
	Zones []string `protobuf:"bytes,5,rep,name=zones,proto3" json:"zones,omitempty"`
	// The idle timeout in minutes for the Public IP.
	// Controls how long Azure keeps idle TCP/UDP connections open before recycling them.
	// Higher values are better for long-lived connections (WebSocket, gRPC streaming,
	// database connections). Lower values free resources faster for short-lived traffic.
	// Range: 4 to 30 minutes.
	// Default: 4
	IdleTimeoutInMinutes *int32 `protobuf:"varint,6,opt,name=idle_timeout_in_minutes,json=idleTimeoutInMinutes,proto3,oneof" json:"idle_timeout_in_minutes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AzurePublicIpSpec) Reset() {
	*x = AzurePublicIpSpec{}
	mi := &file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzurePublicIpSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzurePublicIpSpec) ProtoMessage() {}

func (x *AzurePublicIpSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzurePublicIpSpec.ProtoReflect.Descriptor instead.
func (*AzurePublicIpSpec) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AzurePublicIpSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AzurePublicIpSpec) GetResourceGroup() *v1.StringValueOrRef {
	if x != nil {
		return x.ResourceGroup
	}
	return nil
}

func (x *AzurePublicIpSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AzurePublicIpSpec) GetDomainNameLabel() string {
	if x != nil {
		return x.DomainNameLabel
	}
	return ""
}

func (x *AzurePublicIpSpec) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *AzurePublicIpSpec) GetIdleTimeoutInMinutes() int32 {
	if x != nil && x.IdleTimeoutInMinutes != nil {
		return *x.IdleTimeoutInMinutes
	}
	return 0
}

var File_dev_planton_provider_azure_azurepublicip_v1_spec_proto protoreflect.FileDescriptor

const file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDesc = "" +
	"\n" +
	"6dev/planton/provider/azure/azurepublicip/v1/spec.proto\x12+dev.planton.provider.azure.azurepublicip.v1\x1a\x1bbuf/validate/validate.proto\x1a2dev/planton/shared/foreignkey/v1/foreign_key.proto\x1a(dev/planton/shared/options/options.proto\"\x96\x05\n" +
	"\x11AzurePublicIpSpec\x12\"\n" +
	"\x06region\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06region\x12\x8c\x01\n" +
	"\x0eresource_group\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB1\xbaH\x03\xc8\x01\x01\x88\xd4a\x90\x03\x92\xd4a\"status.outputs.resource_group_nameR\rresourceGroup\x12 \n" +
	"\x04name\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18PR\x04name\x12\xad\x02\n" +
	"\x11domain_name_label\x18\x04 \x01(\tB\x80\x02\xbaH\xfc\x01\xba\x01\xf8\x01\n" +
	"\x18domain_name_label_format\x12\x9d\x01domain_name_label must start with a lowercase letter, end with a letter or digit, contain only lowercase letters, digits, and hyphens, and be 3-63 characters\x1a<this == '' || this.matches('^[a-z][a-z0-9-]{1,61}[a-z0-9]$')R\x0fdomainNameLabel\x12\x14\n" +
	"\x05zones\x18\x05 \x03(\tR\x05zones\x12J\n" +
	"\x17idle_timeout_in_minutes\x18\x06 \x01(\x05B\x0e\xbaH\x06\x1a\x04\x18\x1e(\x04\x8a\xa6\x1d\x014H\x00R\x14idleTimeoutInMinutes\x88\x01\x01B\x1a\n" +
	"\x18_idle_timeout_in_minutesB\xee\x02\n" +
	"/com.dev.planton.provider.azure.azurepublicip.v1B\tSpecProtoP\x01Z]github.com/plantonhq/planton/apis/dev/planton/provider/azure/azurepublicip/v1;azurepublicipv1\xa2\x02\x05DPPAA\xaa\x02+Dev.Planton.Provider.Azure.Azurepublicip.V1\xca\x02+Dev\\Planton\\Provider\\Azure\\Azurepublicip\\V1\xe2\x027Dev\\Planton\\Provider\\Azure\\Azurepublicip\\V1\\GPBMetadata\xea\x020Dev::Planton::Provider::Azure::Azurepublicip::V1b\x06proto3"

var (
	file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescOnce sync.Once
	file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescData []byte
)

func file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDesc), len(file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDesc)))
	})
	return file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDescData
}

var file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_goTypes = []any{
	(*AzurePublicIpSpec)(nil),   // 0: dev.planton.provider.azure.azurepublicip.v1.AzurePublicIpSpec
	(*v1.StringValueOrRef)(nil), // 1: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_depIdxs = []int32{
	1, // 0: dev.planton.provider.azure.azurepublicip.v1.AzurePublicIpSpec.resource_group:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_init() }
func file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_init() {
	if File_dev_planton_provider_azure_azurepublicip_v1_spec_proto != nil {
		return
	}
	file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDesc), len(file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_azure_azurepublicip_v1_spec_proto = out.File
	file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_goTypes = nil
	file_dev_planton_provider_azure_azurepublicip_v1_spec_proto_depIdxs = nil
}
