load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "locals.go",
        "main.go",
        "outputs.go",
        "spec_builder.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/kubernetes/kubernetescertificate/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/kubernetes/kubernetescertificate/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/kubernetes/kuberneteslabelkeys",
        "//pkg/iac/pulumi/pulumimodule/provider/kubernetes/pulumikubernetesprovider",
        "//pkg/kubernetes/kubernetestypes/certmanager/kubernetes/cert_manager/v1:cert_manager",
        "//shared/catalogkind",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/meta/v1:meta",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
