syntax = "proto3";

package dev.planton.aws.awsfsxdatarepositoryassociation.v1alpha1;

import "catalog/aws/awsfsxdatarepositoryassociation/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsFsxDataRepositoryAssociationIacInput is the input for the
// aws-fsx-data-repository-association IaC modules.
message AwsFsxDataRepositoryAssociationIacInput {
  // target infra-component
  AwsFsxDataRepositoryAssociation target = 1;

  // provider-config
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
