syntax = "proto3";

package dev.planton.kubernetes.kubernetesrabbitmqoperator.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/kubernetes/kubernetesrabbitmqoperator/v1alpha1/outputs.proto";
import "catalog/kubernetes/kubernetesrabbitmqoperator/v1alpha1/spec.proto";
import "shared/metadata.proto";

//kubernetes-rabbit-mq-operator
message KubernetesRabbitMqOperator {
  // api-version
  string api_version = 1 [(buf.validate.field).string.const = 'kubernetes.planton.dev/v1alpha1'];

  // resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'KubernetesRabbitMqOperator'];

  // metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  // spec
  KubernetesRabbitMqOperatorSpec spec = 4 [(buf.validate.field).required = true];

  // status
  KubernetesRabbitMqOperatorStatus status = 5;
}

//kubernetes-rabbit-mq-operator status
message KubernetesRabbitMqOperatorStatus {
  // outputs
  KubernetesRabbitMqOperatorOutputs outputs = 1;
}
