// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azurecosmosdbsqlcontainer/v1alpha1/api.proto

package azurecosmosdbsqlcontainerv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureCosmosdbSqlContainer is the top-level API resource for a SQL
// (NoSQL) API container inside a Cosmos DB database (referenced via
// sql_database_id) -- the unit of storage, indexing, and scale-out where
// documents actually live. Partition key, indexing policy, TTL, unique
// keys, conflict resolution, and dedicated throughput are set per
// container.
type AzureCosmosdbSqlContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *AzureCosmosdbSqlContainerSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *AzureCosmosdbSqlContainerStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureCosmosdbSqlContainer) Reset() {
	*x = AzureCosmosdbSqlContainer{}
	mi := &file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCosmosdbSqlContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCosmosdbSqlContainer) ProtoMessage() {}

func (x *AzureCosmosdbSqlContainer) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCosmosdbSqlContainer.ProtoReflect.Descriptor instead.
func (*AzureCosmosdbSqlContainer) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AzureCosmosdbSqlContainer) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AzureCosmosdbSqlContainer) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AzureCosmosdbSqlContainer) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AzureCosmosdbSqlContainer) GetSpec() *AzureCosmosdbSqlContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AzureCosmosdbSqlContainer) GetStatus() *AzureCosmosdbSqlContainerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AzureCosmosdbSqlContainerStatus holds the deployment status and outputs.
type AzureCosmosdbSqlContainerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs
	Outputs       *AzureCosmosdbSqlContainerOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureCosmosdbSqlContainerStatus) Reset() {
	*x = AzureCosmosdbSqlContainerStatus{}
	mi := &file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCosmosdbSqlContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCosmosdbSqlContainerStatus) ProtoMessage() {}

func (x *AzureCosmosdbSqlContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCosmosdbSqlContainerStatus.ProtoReflect.Descriptor instead.
func (*AzureCosmosdbSqlContainerStatus) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AzureCosmosdbSqlContainerStatus) GetOutputs() *AzureCosmosdbSqlContainerOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	":catalog/azure/azurecosmosdbsqlcontainer/v1alpha1/api.proto\x124dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a>catalog/azure/azurecosmosdbsqlcontainer/v1alpha1/outputs.proto\x1a;catalog/azure/azurecosmosdbsqlcontainer/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xc4\x03\n" +
	"\x19AzureCosmosdbSqlContainer\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1aazure.planton.dev/v1alpha1R\n" +
	"apiVersion\x124\n" +
	"\x04kind\x18\x02 \x01(\tB \xbaH\x1dr\x1b\n" +
	"\x19AzureCosmosdbSqlContainerR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12o\n" +
	"\x04spec\x18\x04 \x01(\v2S.dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12m\n" +
	"\x06status\x18\x05 \x01(\v2U.dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerStatusR\x06status\"\x93\x01\n" +
	"\x1fAzureCosmosdbSqlContainerStatus\x12p\n" +
	"\aoutputs\x18\x01 \x01(\v2V.dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerOutputsR\aoutputsB\xaa\x03\n" +
	"8com.dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1B\bApiProtoP\x01Zogithub.com/plantonhq/planton/catalog/azure/azurecosmosdbsqlcontainer/v1alpha1;azurecosmosdbsqlcontainerv1alpha1\xa2\x02\x04DPAA\xaa\x024Dev.Planton.Azure.Azurecosmosdbsqlcontainer.V1alpha1\xca\x024Dev\\Planton\\Azure\\Azurecosmosdbsqlcontainer\\V1alpha1\xe2\x02@Dev\\Planton\\Azure\\Azurecosmosdbsqlcontainer\\V1alpha1\\GPBMetadata\xea\x028Dev::Planton::Azure::Azurecosmosdbsqlcontainer::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDesc), len(file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDescData
}

var file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_goTypes = []any{
	(*AzureCosmosdbSqlContainer)(nil),        // 0: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainer
	(*AzureCosmosdbSqlContainerStatus)(nil),  // 1: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerStatus
	(*shared.CatalogObjectMetadata)(nil),     // 2: dev.planton.shared.CatalogObjectMetadata
	(*AzureCosmosdbSqlContainerSpec)(nil),    // 3: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerSpec
	(*AzureCosmosdbSqlContainerOutputs)(nil), // 4: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerOutputs
}
var file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainer.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainer.spec:type_name -> dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerSpec
	1, // 2: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainer.status:type_name -> dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerStatus
	4, // 3: dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerStatus.outputs:type_name -> dev.planton.azure.azurecosmosdbsqlcontainer.v1alpha1.AzureCosmosdbSqlContainerOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_init() }
func file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_init() {
	if File_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_outputs_proto_init()
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDesc), len(file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto = out.File
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_goTypes = nil
	file_catalog_azure_azurecosmosdbsqlcontainer_v1alpha1_api_proto_depIdxs = nil
}
