syntax = "proto3";

package dev.planton.azure.azureeventhubdisasterrecoveryconfig.v1alpha1;

import "catalog/azure/azureeventhubdisasterrecoveryconfig/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureEventHubDisasterRecoveryConfigIacInput is the input to the IaC
// module. It contains the target resource and provider configuration.
message AzureEventHubDisasterRecoveryConfigIacInput {
  // the catalog object to deploy to be deployed
  AzureEventHubDisasterRecoveryConfig target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
