syntax = "proto3";

package dev.planton.cloudflare.cloudflarezerotrustmcpserver.v1alpha1;

import "catalog/cloudflare/cloudflarezerotrustmcpserver/v1alpha1/api.proto";
import "catalog/cloudflare/provider.proto";

// CloudflareZeroTrustMcpServerIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message CloudflareZeroTrustMcpServerIacInput {
  // the catalog object to deploy to be deployed
  CloudflareZeroTrustMcpServer target = 1;
  // provider-config for Cloudflare authentication
  dev.planton.cloudflare.CloudflareProviderConfig provider_config = 2;
}
