// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azuremonitorscheduledqueryalert/v1alpha1/api.proto

package azuremonitorscheduledqueryalertv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureMonitorScheduledQueryAlert is the top-level API resource for an Azure
// Monitor scheduled query alert rule -- a KQL query evaluated on a schedule
// against a Log Analytics Workspace or Application Insights resource, firing
// action groups when its condition holds.
type AzureMonitorScheduledQueryAlert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *AzureMonitorScheduledQueryAlertSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *AzureMonitorScheduledQueryAlertStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureMonitorScheduledQueryAlert) Reset() {
	*x = AzureMonitorScheduledQueryAlert{}
	mi := &file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMonitorScheduledQueryAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMonitorScheduledQueryAlert) ProtoMessage() {}

func (x *AzureMonitorScheduledQueryAlert) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMonitorScheduledQueryAlert.ProtoReflect.Descriptor instead.
func (*AzureMonitorScheduledQueryAlert) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AzureMonitorScheduledQueryAlert) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AzureMonitorScheduledQueryAlert) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AzureMonitorScheduledQueryAlert) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AzureMonitorScheduledQueryAlert) GetSpec() *AzureMonitorScheduledQueryAlertSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AzureMonitorScheduledQueryAlert) GetStatus() *AzureMonitorScheduledQueryAlertStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AzureMonitorScheduledQueryAlertStatus holds the deployment status and outputs.
type AzureMonitorScheduledQueryAlertStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs
	Outputs       *AzureMonitorScheduledQueryAlertOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureMonitorScheduledQueryAlertStatus) Reset() {
	*x = AzureMonitorScheduledQueryAlertStatus{}
	mi := &file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMonitorScheduledQueryAlertStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMonitorScheduledQueryAlertStatus) ProtoMessage() {}

func (x *AzureMonitorScheduledQueryAlertStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMonitorScheduledQueryAlertStatus.ProtoReflect.Descriptor instead.
func (*AzureMonitorScheduledQueryAlertStatus) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AzureMonitorScheduledQueryAlertStatus) GetOutputs() *AzureMonitorScheduledQueryAlertOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"@catalog/azure/azuremonitorscheduledqueryalert/v1alpha1/api.proto\x12:dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1aDcatalog/azure/azuremonitorscheduledqueryalert/v1alpha1/outputs.proto\x1aAcatalog/azure/azuremonitorscheduledqueryalert/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xe8\x03\n" +
	"\x1fAzureMonitorScheduledQueryAlert\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1aazure.planton.dev/v1alpha1R\n" +
	"apiVersion\x12:\n" +
	"\x04kind\x18\x02 \x01(\tB&\xbaH#r!\n" +
	"\x1fAzureMonitorScheduledQueryAlertR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12{\n" +
	"\x04spec\x18\x04 \x01(\v2_.dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12y\n" +
	"\x06status\x18\x05 \x01(\v2a.dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertStatusR\x06status\"\xa5\x01\n" +
	"%AzureMonitorScheduledQueryAlertStatus\x12|\n" +
	"\aoutputs\x18\x01 \x01(\v2b.dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertOutputsR\aoutputsB\xd4\x03\n" +
	">com.dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1B\bApiProtoP\x01Z{github.com/plantonhq/planton/catalog/azure/azuremonitorscheduledqueryalert/v1alpha1;azuremonitorscheduledqueryalertv1alpha1\xa2\x02\x04DPAA\xaa\x02:Dev.Planton.Azure.Azuremonitorscheduledqueryalert.V1alpha1\xca\x02:Dev\\Planton\\Azure\\Azuremonitorscheduledqueryalert\\V1alpha1\xe2\x02FDev\\Planton\\Azure\\Azuremonitorscheduledqueryalert\\V1alpha1\\GPBMetadata\xea\x02>Dev::Planton::Azure::Azuremonitorscheduledqueryalert::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDesc), len(file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDescData
}

var file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_goTypes = []any{
	(*AzureMonitorScheduledQueryAlert)(nil),        // 0: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlert
	(*AzureMonitorScheduledQueryAlertStatus)(nil),  // 1: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertStatus
	(*shared.CatalogObjectMetadata)(nil),           // 2: dev.planton.shared.CatalogObjectMetadata
	(*AzureMonitorScheduledQueryAlertSpec)(nil),    // 3: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertSpec
	(*AzureMonitorScheduledQueryAlertOutputs)(nil), // 4: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertOutputs
}
var file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlert.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlert.spec:type_name -> dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertSpec
	1, // 2: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlert.status:type_name -> dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertStatus
	4, // 3: dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertStatus.outputs:type_name -> dev.planton.azure.azuremonitorscheduledqueryalert.v1alpha1.AzureMonitorScheduledQueryAlertOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_init() }
func file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_init() {
	if File_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_outputs_proto_init()
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDesc), len(file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto = out.File
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_goTypes = nil
	file_catalog_azure_azuremonitorscheduledqueryalert_v1alpha1_api_proto_depIdxs = nil
}
