// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/scaleway/scalewaymongodbinstance/v1/stack_input.proto

package scalewaymongodbinstancev1

import (
	scaleway "github.com/plantonhq/planton/apis/dev/planton/provider/scaleway"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// scaleway-mongodb-instance stack-input
type ScalewayMongodbInstanceStackInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target cloud-resource
	Target *ScalewayMongodbInstance `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// provider-config
	ProviderConfig *scaleway.ScalewayProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScalewayMongodbInstanceStackInput) Reset() {
	*x = ScalewayMongodbInstanceStackInput{}
	mi := &file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalewayMongodbInstanceStackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalewayMongodbInstanceStackInput) ProtoMessage() {}

func (x *ScalewayMongodbInstanceStackInput) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalewayMongodbInstanceStackInput.ProtoReflect.Descriptor instead.
func (*ScalewayMongodbInstanceStackInput) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescGZIP(), []int{0}
}

func (x *ScalewayMongodbInstanceStackInput) GetTarget() *ScalewayMongodbInstance {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ScalewayMongodbInstanceStackInput) GetProviderConfig() *scaleway.ScalewayProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

var File_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto protoreflect.FileDescriptor

const file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDesc = "" +
	"\n" +
	"Jdev/planton/provider/scaleway/scalewaymongodbinstance/v1/stack_input.proto\x128dev.planton.provider.scaleway.scalewaymongodbinstance.v1\x1a,dev/planton/provider/scaleway/provider.proto\x1aBdev/planton/provider/scaleway/scalewaymongodbinstance/v1/api.proto\"\xee\x01\n" +
	"!ScalewayMongodbInstanceStackInput\x12i\n" +
	"\x06target\x18\x01 \x01(\v2Q.dev.planton.provider.scaleway.scalewaymongodbinstance.v1.ScalewayMongodbInstanceR\x06target\x12^\n" +
	"\x0fprovider_config\x18\x02 \x01(\v25.dev.planton.provider.scaleway.ScalewayProviderConfigR\x0eproviderConfigB\xcc\x03\n" +
	"<com.dev.planton.provider.scaleway.scalewaymongodbinstance.v1B\x0fStackInputProtoP\x01Ztgithub.com/plantonhq/planton/apis/dev/planton/provider/scaleway/scalewaymongodbinstance/v1;scalewaymongodbinstancev1\xa2\x02\x05DPPSS\xaa\x028Dev.Planton.Provider.Scaleway.Scalewaymongodbinstance.V1\xca\x028Dev\\Planton\\Provider\\Scaleway\\Scalewaymongodbinstance\\V1\xe2\x02DDev\\Planton\\Provider\\Scaleway\\Scalewaymongodbinstance\\V1\\GPBMetadata\xea\x02=Dev::Planton::Provider::Scaleway::Scalewaymongodbinstance::V1b\x06proto3"

var (
	file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescOnce sync.Once
	file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescData []byte
)

func file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDesc), len(file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDesc)))
	})
	return file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDescData
}

var file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_goTypes = []any{
	(*ScalewayMongodbInstanceStackInput)(nil), // 0: dev.planton.provider.scaleway.scalewaymongodbinstance.v1.ScalewayMongodbInstanceStackInput
	(*ScalewayMongodbInstance)(nil),           // 1: dev.planton.provider.scaleway.scalewaymongodbinstance.v1.ScalewayMongodbInstance
	(*scaleway.ScalewayProviderConfig)(nil),   // 2: dev.planton.provider.scaleway.ScalewayProviderConfig
}
var file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_depIdxs = []int32{
	1, // 0: dev.planton.provider.scaleway.scalewaymongodbinstance.v1.ScalewayMongodbInstanceStackInput.target:type_name -> dev.planton.provider.scaleway.scalewaymongodbinstance.v1.ScalewayMongodbInstance
	2, // 1: dev.planton.provider.scaleway.scalewaymongodbinstance.v1.ScalewayMongodbInstanceStackInput.provider_config:type_name -> dev.planton.provider.scaleway.ScalewayProviderConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_init() }
func file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_init() {
	if File_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto != nil {
		return
	}
	file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDesc), len(file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto = out.File
	file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_goTypes = nil
	file_dev_planton_provider_scaleway_scalewaymongodbinstance_v1_stack_input_proto_depIdxs = nil
}
