apiVersion: scaleway.planton.dev/v1
kind: ScalewayObjectBucket
metadata:
  name: my-bucket
spec:
  region: fr-par
  versioningEnabled: false  # recommended_default from spec
  forceDestroy: false  # recommended_default from spec
