syntax = "proto3";

package dev.planton.digitalocean.digitaloceandnszone.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceandnszone/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceandnszone/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-dns-zone
message DigitalOceanDnsZone {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = "digital-ocean.planton.dev/v1alpha1"];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = "DigitalOceanDnsZone"];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanDnsZoneSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanDnsZoneStatus status = 5;
}

// digital-ocean-dns-zone status
message DigitalOceanDnsZoneStatus {
  //outputs
  //  digital-ocean-dns-zone outputs
  DigitalOceanDnsZoneOutputs outputs = 1;
}
