syntax = "proto3";

package dev.planton.digitalocean.digitaloceanvpc.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceanvpc/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceanvpc/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-vpc
message DigitalOceanVpc {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = "digital-ocean.planton.dev/v1alpha1"];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = "DigitalOceanVpc"];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanVpcSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanVpcStatus status = 5;
}

// digital-ocean-vpc status
message DigitalOceanVpcStatus {
  //outputs
  //  digital-ocean-vpc outputs
  DigitalOceanVpcOutputs outputs = 1;
}
