load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "capacityestimator",
    srcs = [
        "capacityestimator.go",
        "quantity.go",
    ],
    importpath = "github.com/plantonhq/planton/pkg/finops/capacityestimator",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/kubernetes",
        "//finops/catalogkindcapacityderivation/v1:catalogkindcapacityderivation",
        "//finops/catalogkindcostestimate/v1:catalogkindcostestimate",
        "//finops/catalogkindcostestimatemodel/v1:catalogkindcostestimatemodel",
        "//pkg/finops/costestimator",
        "//pkg/specpath",
        "//shared/options",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)

go_test(
    name = "capacityestimator_test",
    srcs = ["capacityestimator_test.go"],
    embed = [":capacityestimator"],
    deps = [
        "//catalog/kubernetes",
        "//catalog/kubernetes/kubernetesgrafana/v1alpha1",
        "//catalog/kubernetes/kuberneteskeycloak/v1alpha1",
        "//catalog/kubernetes/kubernetespostgres/v1alpha1",
        "//finops/catalogkindcapacityderivation/v1:catalogkindcapacityderivation",
        "//finops/catalogkindcostderivation/v1:catalogkindcostderivation",
        "@org_golang_google_protobuf//proto",
    ],
)
