syntax = "proto3";

package dev.planton.aws.awssagemakernotebookinstance.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awssagemakernotebookinstance/v1alpha1/outputs.proto";
import "catalog/aws/awssagemakernotebookinstance/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsSagemakerNotebookInstance {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsSagemakerNotebookInstance'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsSagemakerNotebookInstanceSpec spec = 4 [(buf.validate.field).required = true];
  AwsSagemakerNotebookInstanceStatus status = 5;
}

message AwsSagemakerNotebookInstanceStatus {
  AwsSagemakerNotebookInstanceOutputs outputs = 1;
}
