apiVersion: digital-ocean.planton.dev/v1
kind: DigitalOceanKubernetesCluster
metadata:
  name: my-dev-cluster
spec:
  clusterName: my-dev-cluster
  region: nyc1
  kubernetesVersion: "1.31"
  vpc:
    value: "<vpc-name>"
  tags:
    - development
    - kubernetes
  defaultNodePool:
    size: s-2vcpu-4gb
    nodeCount: 2
