syntax = "proto3";

package dev.planton.aws.awsebssnapshot.v1alpha1;

import "catalog/aws/awsebssnapshot/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsEbsSnapshotIacInput is the input for the IaC modules that
// manage an EBS snapshot.
message AwsEbsSnapshotIacInput {
  // target is the AwsEbsSnapshot resource to deploy.
  AwsEbsSnapshot target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
