syntax = "proto3";

package dev.planton.cloudflare.cloudflarenotificationpolicy.v1alpha1;

import "catalog/cloudflare/cloudflarenotificationpolicy/v1alpha1/api.proto";
import "catalog/cloudflare/provider.proto";

// CloudflareNotificationPolicyIacInput is the input to the IaC module. It
// contains the target resource and provider configuration.
message CloudflareNotificationPolicyIacInput {
  // the catalog object to deploy to be deployed
  CloudflareNotificationPolicy target = 1;
  // provider-config for Cloudflare authentication
  dev.planton.cloudflare.CloudflareProviderConfig provider_config = 2;
}
