apiVersion: gcp.openmcf.org/v1
kind: GcpSpannerInstance
metadata:
  name: test-spanner
spec:
  projectId:
    value: "<gcp-project-id>"
  instanceName: my-test-spanner
  config: regional-us-central1
  displayName: My Test Spanner
  numNodes: 1
