syntax = "proto3";

package dev.planton.digitalocean.digitaloceandropletautoscalepool.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceandropletautoscalepool/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceandropletautoscalepool/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-droplet-autoscale-pool
message DigitalOceanDropletAutoscalePool {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'digital-ocean.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'DigitalOceanDropletAutoscalePool'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanDropletAutoscalePoolSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanDropletAutoscalePoolStatus status = 5;
}

// digital-ocean-droplet-autoscale-pool status
message DigitalOceanDropletAutoscalePoolStatus {
  //outputs
  //  digital-ocean-droplet-autoscale-pool outputs
  DigitalOceanDropletAutoscalePoolOutputs outputs = 1;
}
