// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/gcp/gcpglobaladdress/v1/stack_outputs.proto

package gcpglobaladdressv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outputs produced after provisioning a GCP global address.
type GcpGlobalAddressStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reserved IP address or the start of the reserved CIDR range.
	// For EXTERNAL addresses this is a public IP. For INTERNAL VPC_PEERING addresses
	// this is the first address in the reserved range.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The self-link URL of the global address resource.
	// Used to reference this address in other GCP resources like forwarding rules.
	SelfLink string `protobuf:"bytes,2,opt,name=self_link,json=selfLink,proto3" json:"self_link,omitempty"`
	// Creation timestamp in RFC3339 format.
	CreationTimestamp string `protobuf:"bytes,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GcpGlobalAddressStackOutputs) Reset() {
	*x = GcpGlobalAddressStackOutputs{}
	mi := &file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpGlobalAddressStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpGlobalAddressStackOutputs) ProtoMessage() {}

func (x *GcpGlobalAddressStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpGlobalAddressStackOutputs.ProtoReflect.Descriptor instead.
func (*GcpGlobalAddressStackOutputs) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *GcpGlobalAddressStackOutputs) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GcpGlobalAddressStackOutputs) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *GcpGlobalAddressStackOutputs) GetCreationTimestamp() string {
	if x != nil {
		return x.CreationTimestamp
	}
	return ""
}

var File_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"@org/openmcf/provider/gcp/gcpglobaladdress/v1/stack_outputs.proto\x12,org.openmcf.provider.gcp.gcpglobaladdress.v1\"\x84\x01\n" +
	"\x1cGcpGlobalAddressStackOutputs\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tself_link\x18\x02 \x01(\tR\bselfLink\x12-\n" +
	"\x12creation_timestamp\x18\x03 \x01(\tR\x11creationTimestampB\xff\x02\n" +
	"0com.org.openmcf.provider.gcp.gcpglobaladdress.v1B\x11StackOutputsProtoP\x01Zagithub.com/plantonhq/openmcf/apis/org/openmcf/provider/gcp/gcpglobaladdress/v1;gcpglobaladdressv1\xa2\x02\x05OOPGG\xaa\x02,Org.Openmcf.Provider.Gcp.Gcpglobaladdress.V1\xca\x02,Org\\Openmcf\\Provider\\Gcp\\Gcpglobaladdress\\V1\xe2\x028Org\\Openmcf\\Provider\\Gcp\\Gcpglobaladdress\\V1\\GPBMetadata\xea\x021Org::Openmcf::Provider::Gcp::Gcpglobaladdress::V1b\x06proto3"

var (
	file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescData []byte
)

func file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDesc), len(file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDesc)))
	})
	return file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDescData
}

var file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_goTypes = []any{
	(*GcpGlobalAddressStackOutputs)(nil), // 0: org.openmcf.provider.gcp.gcpglobaladdress.v1.GcpGlobalAddressStackOutputs
}
var file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_init() }
func file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_init() {
	if File_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDesc), len(file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto = out.File
	file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_goTypes = nil
	file_org_openmcf_provider_gcp_gcpglobaladdress_v1_stack_outputs_proto_depIdxs = nil
}
