syntax = "proto3";

package dev.planton.aws.awsssmdocument.v1alpha1;

import "catalog/aws/awsssmdocument/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSsmDocumentIacInput is the input for the IaC modules that
// manage a customer-owned SSM document.
message AwsSsmDocumentIacInput {
  // target is the AwsSsmDocument resource to deploy.
  AwsSsmDocument target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
