syntax = "proto3";

package dev.planton.azure.azuremonitordatacollectionruleassociation.v1alpha1;

import "catalog/azure/azuremonitordatacollectionruleassociation/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureMonitorDataCollectionRuleAssociationIacInput is the input to
// the IaC modules (Pulumi/Terraform). It contains the target resource
// definition and Azure provider credentials.
message AzureMonitorDataCollectionRuleAssociationIacInput {
  // The data collection rule association resource to deploy.
  AzureMonitorDataCollectionRuleAssociation target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
