syntax = "proto3";

package dev.planton.azure.azureeventgriddomaintopic.v1alpha1;

import "catalog/azure/azureeventgriddomaintopic/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureEventgridDomainTopicIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and
// Azure provider credentials.
message AzureEventgridDomainTopicIacInput {
  // The Event Grid domain topic resource to deploy.
  AzureEventgridDomainTopic target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
