apiVersion: azure.planton.dev/v1
kind: AzureContainerAppEnvironment
metadata:
  name: my-production-env
spec:
  region: <azure-region>
  resourceGroup:
    value: "<your-resource-group-name>"
  name: <environment-name>
  infrastructureSubnetId:
    value: "<infrastructure-subnet-id>"
  logAnalyticsWorkspaceId:
    value: "<log-analytics-workspace-id>"
  internalLoadBalancerEnabled: true
  zoneRedundancyEnabled: true
  workloadProfiles:
    - name: dedicated
      workloadProfileType: D4
      minimumCount: 1
      maximumCount: 5
