apiVersion: azure.openmcf.org/v1
kind: AzureVpc
metadata:
  name: my-production-vpc
spec:
  region: <azure-region>
  resourceGroup:
    value: "<your-resource-group-name>"
  addressSpaceCidr: 10.0.0.0/16
  nodesSubnetCidr: 10.0.0.0/18
  isNatGatewayEnabled: true
