apiVersion: openstack.planton.dev/v1
kind: OpenStackInstance
metadata:
  name: my-persistent-instance
spec:
  flavorName: <flavor-name>
  keyPair:
    value: <keypair-name>
  networks:
    - uuid:
        value: <network-id>
  securityGroups:
    - value: <security-group-name>
  blockDevice:
    - sourceType: image
      uuid: <image-id>
      destinationType: volume
      bootIndex: 0
      volumeSize: 50
      deleteOnTermination: true
