// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awssagemakermlflowapp/v1alpha1/api.proto

package awssagemakermlflowappv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AwsSagemakerMlflowApp struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ApiVersion    string                        `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                        `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *AwsSagemakerMlflowAppSpec    `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AwsSagemakerMlflowAppStatus  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsSagemakerMlflowApp) Reset() {
	*x = AwsSagemakerMlflowApp{}
	mi := &file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsSagemakerMlflowApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsSagemakerMlflowApp) ProtoMessage() {}

func (x *AwsSagemakerMlflowApp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsSagemakerMlflowApp.ProtoReflect.Descriptor instead.
func (*AwsSagemakerMlflowApp) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AwsSagemakerMlflowApp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AwsSagemakerMlflowApp) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AwsSagemakerMlflowApp) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AwsSagemakerMlflowApp) GetSpec() *AwsSagemakerMlflowAppSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AwsSagemakerMlflowApp) GetStatus() *AwsSagemakerMlflowAppStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AwsSagemakerMlflowAppStatus struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Outputs       *AwsSagemakerMlflowAppOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsSagemakerMlflowAppStatus) Reset() {
	*x = AwsSagemakerMlflowAppStatus{}
	mi := &file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsSagemakerMlflowAppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsSagemakerMlflowAppStatus) ProtoMessage() {}

func (x *AwsSagemakerMlflowAppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsSagemakerMlflowAppStatus.ProtoReflect.Descriptor instead.
func (*AwsSagemakerMlflowAppStatus) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AwsSagemakerMlflowAppStatus) GetOutputs() *AwsSagemakerMlflowAppOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"4catalog/aws/awssagemakermlflowapp/v1alpha1/api.proto\x12.dev.planton.aws.awssagemakermlflowapp.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a8catalog/aws/awssagemakermlflowapp/v1alpha1/outputs.proto\x1a5catalog/aws/awssagemakermlflowapp/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xa6\x03\n" +
	"\x15AwsSagemakerMlflowApp\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18aws.planton.dev/v1alpha1R\n" +
	"apiVersion\x120\n" +
	"\x04kind\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\n" +
	"\x15AwsSagemakerMlflowAppR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12e\n" +
	"\x04spec\x18\x04 \x01(\v2I.dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12c\n" +
	"\x06status\x18\x05 \x01(\v2K.dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppStatusR\x06status\"\x85\x01\n" +
	"\x1bAwsSagemakerMlflowAppStatus\x12f\n" +
	"\aoutputs\x18\x01 \x01(\v2L.dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppOutputsR\aoutputsB\x82\x03\n" +
	"2com.dev.planton.aws.awssagemakermlflowapp.v1alpha1B\bApiProtoP\x01Zegithub.com/plantonhq/planton/catalog/aws/awssagemakermlflowapp/v1alpha1;awssagemakermlflowappv1alpha1\xa2\x02\x04DPAA\xaa\x02.Dev.Planton.Aws.Awssagemakermlflowapp.V1alpha1\xca\x02.Dev\\Planton\\Aws\\Awssagemakermlflowapp\\V1alpha1\xe2\x02:Dev\\Planton\\Aws\\Awssagemakermlflowapp\\V1alpha1\\GPBMetadata\xea\x022Dev::Planton::Aws::Awssagemakermlflowapp::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDesc), len(file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDescData
}

var file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_goTypes = []any{
	(*AwsSagemakerMlflowApp)(nil),        // 0: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowApp
	(*AwsSagemakerMlflowAppStatus)(nil),  // 1: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppStatus
	(*shared.CatalogObjectMetadata)(nil), // 2: dev.planton.shared.CatalogObjectMetadata
	(*AwsSagemakerMlflowAppSpec)(nil),    // 3: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppSpec
	(*AwsSagemakerMlflowAppOutputs)(nil), // 4: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppOutputs
}
var file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowApp.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowApp.spec:type_name -> dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppSpec
	1, // 2: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowApp.status:type_name -> dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppStatus
	4, // 3: dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppStatus.outputs:type_name -> dev.planton.aws.awssagemakermlflowapp.v1alpha1.AwsSagemakerMlflowAppOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_init() }
func file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_init() {
	if File_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_outputs_proto_init()
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDesc), len(file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto = out.File
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_goTypes = nil
	file_catalog_aws_awssagemakermlflowapp_v1alpha1_api_proto_depIdxs = nil
}
