// Code generated by pkg/crkreflect/codegen; DO NOT EDIT.
//
// This file defines ToMessageMap which maps CloudResourceKind enums to protobuf message instances.
// To regenerate: make generate-cloud-resource-kind-map
//
// IMPORTANT: Files that import ToMessageMap should use "//go:build !codegen" tag
// to prevent chicken-and-egg compilation issues during generation.
// See new_instance.go for an example.
package crkreflect

import (
	"github.com/plantonhq/planton/apis/dev/planton/shared/cloudresourcekind"
	"google.golang.org/protobuf/proto"
)

func merge(maps ...map[cloudresourcekind.CloudResourceKind]proto.Message) map[cloudresourcekind.CloudResourceKind]proto.Message {
	out := make(map[cloudresourcekind.CloudResourceKind]proto.Message)
	for _, m := range maps {
		for k, v := range m {
			out[k] = v
		}
	}
	return out
}

var ToMessageMap = merge()
