load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "verify",
    srcs = [
        "apps.go",
        "bucket.go",
        "cdn.go",
        "certificate.go",
        "container_registry.go",
        "database_cluster.go",
        "database_db.go",
        "database_firewall.go",
        "database_pool.go",
        "database_replica.go",
        "database_user.go",
        "domains.go",
        "droplet.go",
        "droplet_autoscale_pool.go",
        "firewall.go",
        "kafka_schema.go",
        "kafka_topic.go",
        "kubernetes.go",
        "loadbalancer.go",
        "monitor_alert.go",
        "project.go",
        "reserved_ip.go",
        "spaces_key.go",
        "ssh_key.go",
        "uptime_check.go",
        "verifier.go",
        "volume.go",
        "vpc.go",
        "vpc_peering.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/digitalocean/aa_e2e/verify",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_credentials//:credentials",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_aws_aws_sdk_go_v2_service_s3//types",
        "@com_github_aws_smithy_go//:smithy-go",
        "@com_github_digitalocean_godo//:godo",
        "@com_github_pkg_errors//:errors",
    ],
)
