syntax = "proto3";

package dev.planton.aws.awsssmmaintenancewindow.v1alpha1;

import "catalog/aws/awsssmmaintenancewindow/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSsmMaintenanceWindowIacInput is the input for the IaC modules
// that manage a maintenance window with its folded targets and tasks.
message AwsSsmMaintenanceWindowIacInput {
  // target is the AwsSsmMaintenanceWindow resource to deploy.
  AwsSsmMaintenanceWindow target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
