apiVersion: aws.planton.dev/v1
kind: AwsEksNodeGroup
metadata:
  name: my-general-node-group
spec:
  region: <aws-region>
  clusterName:
    value: "<eks-cluster-name>"
  nodeRoleArn:
    value: "<node-role-arn>"
  subnetIds:
    - value: "<private-subnet-id-az1>"
    - value: "<private-subnet-id-az2>"
  instanceType: t3.medium
  scaling:
    minSize: 2
    maxSize: 5
    desiredSize: 2
  capacityType: on_demand  # recommended_default from spec
  diskSizeGb: 100  # recommended_default from spec
