syntax = "proto3";

package dev.planton.kubernetes.kuberneteskafkauser.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/kubernetes/kuberneteskafkauser/v1alpha1/outputs.proto";
import "catalog/kubernetes/kuberneteskafkauser/v1alpha1/spec.proto";
import "shared/metadata.proto";

//kubernetes-kafka-user
message KubernetesKafkaUser {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'kubernetes.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'KubernetesKafkaUser'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  KubernetesKafkaUserSpec spec = 4 [(buf.validate.field).required = true];

  //status
  KubernetesKafkaUserStatus status = 5;
}

//kubernetes-kafka-user status
message KubernetesKafkaUserStatus {
  //outputs
  KubernetesKafkaUserOutputs outputs = 1;
}
