// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/cloudflare/cloudflareruleset/v1/stack_outputs.proto

package cloudflarerulesetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CloudflareRulesetStackOutputs captures the observable outputs after provisioning a Cloudflare Ruleset.
type CloudflareRulesetStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Cloudflare-assigned unique identifier of the ruleset.
	RulesetId string `protobuf:"bytes,1,opt,name=ruleset_id,json=rulesetId,proto3" json:"ruleset_id,omitempty"`
	// The current version of the ruleset (increments on each update).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The zone ID the ruleset belongs to (pass-through for downstream resource references).
	ZoneId string `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	// The phase the ruleset executes in (pass-through for infra-chart conditionals).
	Phase string `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	// RFC3339 timestamp of the ruleset's last update.
	LastUpdated   string `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudflareRulesetStackOutputs) Reset() {
	*x = CloudflareRulesetStackOutputs{}
	mi := &file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudflareRulesetStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudflareRulesetStackOutputs) ProtoMessage() {}

func (x *CloudflareRulesetStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudflareRulesetStackOutputs.ProtoReflect.Descriptor instead.
func (*CloudflareRulesetStackOutputs) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *CloudflareRulesetStackOutputs) GetRulesetId() string {
	if x != nil {
		return x.RulesetId
	}
	return ""
}

func (x *CloudflareRulesetStackOutputs) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CloudflareRulesetStackOutputs) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CloudflareRulesetStackOutputs) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *CloudflareRulesetStackOutputs) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

var File_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Horg/openmcf/provider/cloudflare/cloudflareruleset/v1/stack_outputs.proto\x124org.openmcf.provider.cloudflare.cloudflareruleset.v1\"\xaa\x01\n" +
	"\x1dCloudflareRulesetStackOutputs\x12\x1d\n" +
	"\n" +
	"ruleset_id\x18\x01 \x01(\tR\trulesetId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12!\n" +
	"\flast_updated\x18\x05 \x01(\tR\vlastUpdatedB\xb0\x03\n" +
	"8com.org.openmcf.provider.cloudflare.cloudflareruleset.v1B\x11StackOutputsProtoP\x01Zjgithub.com/plantonhq/openmcf/apis/org/openmcf/provider/cloudflare/cloudflareruleset/v1;cloudflarerulesetv1\xa2\x02\x05OOPCC\xaa\x024Org.Openmcf.Provider.Cloudflare.Cloudflareruleset.V1\xca\x024Org\\Openmcf\\Provider\\Cloudflare\\Cloudflareruleset\\V1\xe2\x02@Org\\Openmcf\\Provider\\Cloudflare\\Cloudflareruleset\\V1\\GPBMetadata\xea\x029Org::Openmcf::Provider::Cloudflare::Cloudflareruleset::V1b\x06proto3"

var (
	file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescData []byte
)

func file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDesc), len(file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDesc)))
	})
	return file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDescData
}

var file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_goTypes = []any{
	(*CloudflareRulesetStackOutputs)(nil), // 0: org.openmcf.provider.cloudflare.cloudflareruleset.v1.CloudflareRulesetStackOutputs
}
var file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_init() }
func file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_init() {
	if File_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDesc), len(file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto = out.File
	file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_goTypes = nil
	file_org_openmcf_provider_cloudflare_cloudflareruleset_v1_stack_outputs_proto_depIdxs = nil
}
