syntax = "proto3";

package dev.planton.azure.azurewebapplicationfirewallpolicy.v1alpha1;

import "catalog/azure/azurewebapplicationfirewallpolicy/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureWebApplicationFirewallPolicyIacInput is the input to the IaC
// modules (Pulumi/Terraform). It contains the target resource definition
// and Azure provider credentials.
message AzureWebApplicationFirewallPolicyIacInput {
  // The WAF policy resource to deploy.
  AzureWebApplicationFirewallPolicy target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
