syntax = "proto3";

package dev.planton.aws.awscloudwatchloggroup.v1alpha1;

import "catalog/aws/awscloudwatchloggroup/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsCloudwatchLogGroupIacInput provides the inputs required by Pulumi/Terraform
// modules to provision a CloudWatch Logs log group.
message AwsCloudwatchLogGroupIacInput {
  // the catalog object to deploy
  AwsCloudwatchLogGroup target = 1;
  // provider-config
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
