syntax = "proto3";

package dev.planton.digitalocean.digitaloceankubernetescluster.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceankubernetescluster/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceankubernetescluster/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-kubernetes-cluster
message DigitalOceanKubernetesCluster {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = "digital-ocean.planton.dev/v1alpha1"];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = "DigitalOceanKubernetesCluster"];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanKubernetesClusterSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanKubernetesClusterStatus status = 5;
}

// digital-ocean-kubernetes-cluster status
message DigitalOceanKubernetesClusterStatus {
  //outputs
  //  digital-ocean-kubernetes-cluster outputs
  DigitalOceanKubernetesClusterOutputs outputs = 1;
}
