syntax = "proto3";

package dev.planton.kubernetes.kubernetesauthorizationpolicy.v1alpha1;

import "catalog/kubernetes/kubernetesauthorizationpolicy/v1alpha1/api.proto";
import "catalog/kubernetes/provider.proto";

// KubernetesAuthorizationPolicyIacInput provides the inputs for creating the
// AuthorizationPolicy on a Kubernetes cluster.
message KubernetesAuthorizationPolicyIacInput {
  // target infra-component
  KubernetesAuthorizationPolicy target = 1;
  // provider-config
  dev.planton.kubernetes.KubernetesProviderConfig provider_config = 2;
}
