syntax = "proto3";

package dev.planton.kubernetes.kubernetesplantonplatform.v1alpha1;

import "catalog/kubernetes/kubernetesplantonplatform/v1alpha1/api.proto";
import "catalog/kubernetes/provider.proto";

// KubernetesPlantonPlatformIacInput provides the input for the Planton
// platform IaC stack.
message KubernetesPlantonPlatformIacInput {
  // target infra-component
  KubernetesPlantonPlatform target = 1;
  // provider-config for Kubernetes provider
  dev.planton.kubernetes.KubernetesProviderConfig provider_config = 2;
}
