apiVersion: oci.planton.dev/v1
kind: OciDbSystem
metadata:
  name: my-oracle-rac
spec:
  compartmentId:
    value: <compartment-ocid>
  displayName: oracle-rac
  availabilityDomain: <availability-domain>
  shape: VM.Standard.E4.Flex
  cpuCoreCount: 4
  subnetId:
    value: <private-subnet-ocid>
  sshPublicKeys:
    - <ssh-public-key>
  hostname: oraclerac
  databaseEdition: enterprise_edition_extreme_performance # Required for RAC
  licenseModel: license_included
  dataStorageSizeInGb: 1024
  nodeCount: 2
  clusterName: oraclerac
  faultDomains:
    - FAULT-DOMAIN-1
    - FAULT-DOMAIN-2
  nsgIds:
    - value: <db-nsg-ocid>
  backupSubnetId:
    value: <backup-subnet-ocid>
  maintenanceWindowDetails:
    preference: custom_preference
    patchingMode: rolling # Zero-downtime patching for RAC
    months:
      - JANUARY
      - APRIL
      - JULY
      - OCTOBER
    weeksOfMonth:
      - 2
    daysOfWeek:
      - SUNDAY
    hoursOfDay:
      - 4
  dbHome:
    dbVersion: "19.0.0.0"
    displayName: dbhome1
    database:
      adminPassword: <admin-password>
      dbName: myracdb
      pdbName: mypdb
      dbBackupConfig:
        autoBackupEnabled: true
        recoveryWindowInDays: 60
