load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "external_gateway.go",
        "locals.go",
        "main.go",
        "outputs.go",
        "tunnels.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/gcp/gcphavpnconnection/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/gcp/gcphavpnconnection/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/gcp/gcplabelkeys",
        "//pkg/iac/pulumi/pulumimodule/provider/gcp/pulumigoogleprovider",
        "//shared/cloudresourcekind",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_gcp_sdk_v9//go/gcp",
        "@com_github_pulumi_pulumi_gcp_sdk_v9//go/gcp/compute",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
