syntax = "proto3";

package dev.planton.aws.awsrdsinstance.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsrdsinstance/v1alpha1/outputs.proto";
import "catalog/aws/awsrdsinstance/v1alpha1/spec.proto";
import "shared/metadata.proto";

// AwsRdsInstance represents a single AWS RDS DB instance.
message AwsRdsInstance {
  // api-version must be set to "aws.planton.dev/v1alpha1".
  string api_version = 1 [(buf.validate.field).string.const = "aws.planton.dev/v1alpha1"];

  // resource-kind for this resource, must be "AwsRdsInstance".
  string kind = 2 [(buf.validate.field).string.const = 'AwsRdsInstance'];

  // metadata captures identifying information (name, org, version, etc.).
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  // spec holds the core configuration data defining the DB instance.
  AwsRdsInstanceSpec spec = 4 [(buf.validate.field).required = true];

  // status holds runtime or post-deployment information.
  AwsRdsInstanceStatus status = 5;
}

// AwsRdsInstanceStatus describes the status fields for an RDS instance resource.
message AwsRdsInstanceStatus {
  // outputs
  AwsRdsInstanceOutputs outputs = 1;
}
