// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awshttpapigateway/v1alpha1/api.proto

package awshttpapigatewayv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsHttpApiGateway is the Kubernetes-style resource envelope for an AWS API Gateway HTTP API.
//
// HTTP APIs are the recommended API type for building RESTful APIs and HTTP proxies
// in AWS. They offer lower latency and cost compared to REST APIs, with native support
// for Lambda proxy integration, JWT authorization, and automatic deployments.
type AwsHttpApiGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version must be set to "aws.planton.dev/v1alpha1".
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind for this HTTP API Gateway resource, must be "AwsHttpApiGateway".
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata captures identifying information (name, org, env, id, labels, relationships).
	Metadata *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec holds the desired configuration for the HTTP API Gateway.
	Spec *AwsHttpApiGatewaySpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status holds runtime or post-deployment information.
	Status        *AwsHttpApiGatewayStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsHttpApiGateway) Reset() {
	*x = AwsHttpApiGateway{}
	mi := &file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsHttpApiGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsHttpApiGateway) ProtoMessage() {}

func (x *AwsHttpApiGateway) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsHttpApiGateway.ProtoReflect.Descriptor instead.
func (*AwsHttpApiGateway) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AwsHttpApiGateway) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AwsHttpApiGateway) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AwsHttpApiGateway) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AwsHttpApiGateway) GetSpec() *AwsHttpApiGatewaySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AwsHttpApiGateway) GetStatus() *AwsHttpApiGatewayStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AwsHttpApiGatewayStatus captures lifecycle, audit, job linkage, and observable outputs.
type AwsHttpApiGatewayStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs
	Outputs       *AwsHttpApiGatewayOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsHttpApiGatewayStatus) Reset() {
	*x = AwsHttpApiGatewayStatus{}
	mi := &file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsHttpApiGatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsHttpApiGatewayStatus) ProtoMessage() {}

func (x *AwsHttpApiGatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsHttpApiGatewayStatus.ProtoReflect.Descriptor instead.
func (*AwsHttpApiGatewayStatus) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AwsHttpApiGatewayStatus) GetOutputs() *AwsHttpApiGatewayOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_aws_awshttpapigateway_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"0catalog/aws/awshttpapigateway/v1alpha1/api.proto\x12*dev.planton.aws.awshttpapigateway.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a4catalog/aws/awshttpapigateway/v1alpha1/outputs.proto\x1a1catalog/aws/awshttpapigateway/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\x8e\x03\n" +
	"\x11AwsHttpApiGateway\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18aws.planton.dev/v1alpha1R\n" +
	"apiVersion\x12,\n" +
	"\x04kind\x18\x02 \x01(\tB\x18\xbaH\x15r\x13\n" +
	"\x11AwsHttpApiGatewayR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12]\n" +
	"\x04spec\x18\x04 \x01(\v2A.dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewaySpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12[\n" +
	"\x06status\x18\x05 \x01(\v2C.dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayStatusR\x06status\"y\n" +
	"\x17AwsHttpApiGatewayStatus\x12^\n" +
	"\aoutputs\x18\x01 \x01(\v2D.dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayOutputsR\aoutputsB\xe6\x02\n" +
	".com.dev.planton.aws.awshttpapigateway.v1alpha1B\bApiProtoP\x01Z]github.com/plantonhq/planton/catalog/aws/awshttpapigateway/v1alpha1;awshttpapigatewayv1alpha1\xa2\x02\x04DPAA\xaa\x02*Dev.Planton.Aws.Awshttpapigateway.V1alpha1\xca\x02*Dev\\Planton\\Aws\\Awshttpapigateway\\V1alpha1\xe2\x026Dev\\Planton\\Aws\\Awshttpapigateway\\V1alpha1\\GPBMetadata\xea\x02.Dev::Planton::Aws::Awshttpapigateway::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDesc), len(file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDescData
}

var file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_goTypes = []any{
	(*AwsHttpApiGateway)(nil),            // 0: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGateway
	(*AwsHttpApiGatewayStatus)(nil),      // 1: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayStatus
	(*shared.CatalogObjectMetadata)(nil), // 2: dev.planton.shared.CatalogObjectMetadata
	(*AwsHttpApiGatewaySpec)(nil),        // 3: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewaySpec
	(*AwsHttpApiGatewayOutputs)(nil),     // 4: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayOutputs
}
var file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGateway.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGateway.spec:type_name -> dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewaySpec
	1, // 2: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGateway.status:type_name -> dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayStatus
	4, // 3: dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayStatus.outputs:type_name -> dev.planton.aws.awshttpapigateway.v1alpha1.AwsHttpApiGatewayOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_init() }
func file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_init() {
	if File_catalog_aws_awshttpapigateway_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_aws_awshttpapigateway_v1alpha1_outputs_proto_init()
	file_catalog_aws_awshttpapigateway_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDesc), len(file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_aws_awshttpapigateway_v1alpha1_api_proto = out.File
	file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_goTypes = nil
	file_catalog_aws_awshttpapigateway_v1alpha1_api_proto_depIdxs = nil
}
