// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/cloudflare/cloudflarezonesettings/v1alpha1/api.proto

package cloudflarezonesettingsv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CloudflareZoneSettings is a KRM-style resource for managing a Cloudflare zone's
// behavior settings: the HTTP, SSL/TLS, cache-adjacent, and network posture shown
// under the dashboard's Speed, Security, and Network tabs, plus managed header
// transforms, URL normalization, origin cloud-region hints, and the zone-wide
// waiting-room crawler bypass.
type CloudflareZoneSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *CloudflareZoneSettingsSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *CloudflareZoneSettingsStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudflareZoneSettings) Reset() {
	*x = CloudflareZoneSettings{}
	mi := &file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudflareZoneSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudflareZoneSettings) ProtoMessage() {}

func (x *CloudflareZoneSettings) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudflareZoneSettings.ProtoReflect.Descriptor instead.
func (*CloudflareZoneSettings) Descriptor() ([]byte, []int) {
	return file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CloudflareZoneSettings) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *CloudflareZoneSettings) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CloudflareZoneSettings) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CloudflareZoneSettings) GetSpec() *CloudflareZoneSettingsSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CloudflareZoneSettings) GetStatus() *CloudflareZoneSettingsStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// CloudflareZoneSettingsStatus represents the observed state of a zone's settings.
type CloudflareZoneSettingsStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs from the IaC deployment
	Outputs       *CloudflareZoneSettingsOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudflareZoneSettingsStatus) Reset() {
	*x = CloudflareZoneSettingsStatus{}
	mi := &file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudflareZoneSettingsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudflareZoneSettingsStatus) ProtoMessage() {}

func (x *CloudflareZoneSettingsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudflareZoneSettingsStatus.ProtoReflect.Descriptor instead.
func (*CloudflareZoneSettingsStatus) Descriptor() ([]byte, []int) {
	return file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CloudflareZoneSettingsStatus) GetOutputs() *CloudflareZoneSettingsOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"<catalog/cloudflare/cloudflarezonesettings/v1alpha1/api.proto\x126dev.planton.cloudflare.cloudflarezonesettings.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a@catalog/cloudflare/cloudflarezonesettings/v1alpha1/outputs.proto\x1a=catalog/cloudflare/cloudflarezonesettings/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xc1\x03\n" +
	"\x16CloudflareZoneSettings\x12G\n" +
	"\vapi_version\x18\x01 \x01(\tB&\xbaH#r!\n" +
	"\x1fcloudflare.planton.dev/v1alpha1R\n" +
	"apiVersion\x121\n" +
	"\x04kind\x18\x02 \x01(\tB\x1d\xbaH\x1ar\x18\n" +
	"\x16CloudflareZoneSettingsR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12n\n" +
	"\x04spec\x18\x04 \x01(\v2R.dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12l\n" +
	"\x06status\x18\x05 \x01(\v2T.dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsStatusR\x06status\"\x8f\x01\n" +
	"\x1cCloudflareZoneSettingsStatus\x12o\n" +
	"\aoutputs\x18\x01 \x01(\v2U.dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsOutputsR\aoutputsB\xb3\x03\n" +
	":com.dev.planton.cloudflare.cloudflarezonesettings.v1alpha1B\bApiProtoP\x01Zngithub.com/plantonhq/planton/catalog/cloudflare/cloudflarezonesettings/v1alpha1;cloudflarezonesettingsv1alpha1\xa2\x02\x04DPCC\xaa\x026Dev.Planton.Cloudflare.Cloudflarezonesettings.V1alpha1\xca\x026Dev\\Planton\\Cloudflare\\Cloudflarezonesettings\\V1alpha1\xe2\x02BDev\\Planton\\Cloudflare\\Cloudflarezonesettings\\V1alpha1\\GPBMetadata\xea\x02:Dev::Planton::Cloudflare::Cloudflarezonesettings::V1alpha1b\x06proto3"

var (
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDesc), len(file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDescData
}

var file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_goTypes = []any{
	(*CloudflareZoneSettings)(nil),        // 0: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettings
	(*CloudflareZoneSettingsStatus)(nil),  // 1: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsStatus
	(*shared.CatalogObjectMetadata)(nil),  // 2: dev.planton.shared.CatalogObjectMetadata
	(*CloudflareZoneSettingsSpec)(nil),    // 3: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsSpec
	(*CloudflareZoneSettingsOutputs)(nil), // 4: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsOutputs
}
var file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettings.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettings.spec:type_name -> dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsSpec
	1, // 2: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettings.status:type_name -> dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsStatus
	4, // 3: dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsStatus.outputs:type_name -> dev.planton.cloudflare.cloudflarezonesettings.v1alpha1.CloudflareZoneSettingsOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_init() }
func file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_init() {
	if File_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_outputs_proto_init()
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDesc), len(file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto = out.File
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_goTypes = nil
	file_catalog_cloudflare_cloudflarezonesettings_v1alpha1_api_proto_depIdxs = nil
}
