load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "localmodule",
    srcs = ["local_module.go"],
    importpath = "github.com/plantonhq/planton/pkg/iac/localmodule",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/cli/cliprint",
        "//pkg/catalogkindreflect",
        "//pkg/iac/gitrepo",
        "//pkg/iac/pulumi/pulumimodule",
        "//pkg/iac/tofu/tofumodule",
        "//shared",
        "//shared/catalogkind",
        "@com_github_pkg_errors//:errors",
        "@com_github_spf13_cobra//:cobra",
    ],
)
