// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpprivatecacertificate/v1alpha1/outputs.proto

package gcpprivatecacertificatev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcpPrivateCaCertificateStackOutputs captures the issued certificate -- what the workload
// installs beside its private key.
type GcpPrivateCaCertificateStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full resource name --
	// projects/{project}/locations/{location}/caPools/{pool}/certificates/{certificate_id}.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The certificate's ID (the last segment of name).
	CertificateId string `protobuf:"bytes,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	// The signed certificate, PEM.
	PemCertificate string `protobuf:"bytes,3,opt,name=pem_certificate,json=pemCertificate,proto3" json:"pem_certificate,omitempty"`
	// The chain that verifies it, PEM, issuer first and root last.
	PemCertificateChain []string `protobuf:"bytes,4,rep,name=pem_certificate_chain,json=pemCertificateChain,proto3" json:"pem_certificate_chain,omitempty"`
	// The full name of the authority that signed it.
	IssuerCertificateAuthority string `protobuf:"bytes,5,opt,name=issuer_certificate_authority,json=issuerCertificateAuthority,proto3" json:"issuer_certificate_authority,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GcpPrivateCaCertificateStackOutputs) Reset() {
	*x = GcpPrivateCaCertificateStackOutputs{}
	mi := &file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpPrivateCaCertificateStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpPrivateCaCertificateStackOutputs) ProtoMessage() {}

func (x *GcpPrivateCaCertificateStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpPrivateCaCertificateStackOutputs.ProtoReflect.Descriptor instead.
func (*GcpPrivateCaCertificateStackOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *GcpPrivateCaCertificateStackOutputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GcpPrivateCaCertificateStackOutputs) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *GcpPrivateCaCertificateStackOutputs) GetPemCertificate() string {
	if x != nil {
		return x.PemCertificate
	}
	return ""
}

func (x *GcpPrivateCaCertificateStackOutputs) GetPemCertificateChain() []string {
	if x != nil {
		return x.PemCertificateChain
	}
	return nil
}

func (x *GcpPrivateCaCertificateStackOutputs) GetIssuerCertificateAuthority() string {
	if x != nil {
		return x.IssuerCertificateAuthority
	}
	return ""
}

var File_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	":catalog/gcp/gcpprivatecacertificate/v1alpha1/outputs.proto\x120dev.planton.gcp.gcpprivatecacertificate.v1alpha1\"\xff\x01\n" +
	"#GcpPrivateCaCertificateStackOutputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0ecertificate_id\x18\x02 \x01(\tR\rcertificateId\x12'\n" +
	"\x0fpem_certificate\x18\x03 \x01(\tR\x0epemCertificate\x122\n" +
	"\x15pem_certificate_chain\x18\x04 \x03(\tR\x13pemCertificateChain\x12@\n" +
	"\x1cissuer_certificate_authority\x18\x05 \x01(\tR\x1aissuerCertificateAuthorityB\x94\x03\n" +
	"4com.dev.planton.gcp.gcpprivatecacertificate.v1alpha1B\fOutputsProtoP\x01Zigithub.com/plantonhq/planton/catalog/gcp/gcpprivatecacertificate/v1alpha1;gcpprivatecacertificatev1alpha1\xa2\x02\x04DPGG\xaa\x020Dev.Planton.Gcp.Gcpprivatecacertificate.V1alpha1\xca\x020Dev\\Planton\\Gcp\\Gcpprivatecacertificate\\V1alpha1\xe2\x02<Dev\\Planton\\Gcp\\Gcpprivatecacertificate\\V1alpha1\\GPBMetadata\xea\x024Dev::Planton::Gcp::Gcpprivatecacertificate::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDesc), len(file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_goTypes = []any{
	(*GcpPrivateCaCertificateStackOutputs)(nil), // 0: dev.planton.gcp.gcpprivatecacertificate.v1alpha1.GcpPrivateCaCertificateStackOutputs
}
var file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_init() }
func file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_init() {
	if File_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDesc), len(file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto = out.File
	file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_gcp_gcpprivatecacertificate_v1alpha1_outputs_proto_depIdxs = nil
}
