syntax = "proto3";

package dev.planton.aws.awscostcategory.v1alpha1;

import "catalog/aws/awscostcategory/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsCostCategoryIacInput is the input for the IaC modules that
// manage a Cost Explorer cost category.
message AwsCostCategoryIacInput {
  // target is the AwsCostCategory resource to deploy.
  AwsCostCategory target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
