apiVersion: kubernetes.openmcf.org/v1
kind: KubernetesHttpRoute
metadata:
  name: my-web-route
spec:
  namespace:
    value: app-ns
  parentRefs:
    - name: <gateway-name>
  hostnames:
    - <app-hostname>
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: <service-name>
          port: 8080
