syntax = "proto3";

package dev.planton.gcp.gcpserverlessvpcconnector.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcpserverlessvpcconnector/v1alpha1/outputs.proto";
import "catalog/gcp/gcpserverlessvpcconnector/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-serverless-vpc-connector
message GcpServerlessVpcConnector {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'GcpServerlessVpcConnector'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  GcpServerlessVpcConnectorSpec spec = 4 [(buf.validate.field).required = true];

  //status
  GcpServerlessVpcConnectorStatus status = 5;
}

//gcp-serverless-vpc-connector status
message GcpServerlessVpcConnectorStatus {
  //outputs
  GcpServerlessVpcConnectorOutputs outputs = 1;
}
