syntax = "proto3";

package dev.planton.azure.azuredisksnapshot.v1alpha1;

import "catalog/azure/azuredisksnapshot/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureDiskSnapshotIacInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and
// Azure provider credentials.
message AzureDiskSnapshotIacInput {
  // The disk snapshot resource to deploy.
  AzureDiskSnapshot target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
