// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awskmskey/v1alpha1/outputs.proto

package awskmskeyv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsKmsKeyOutputs captures the observable identifiers of a
// deployed KMS key -- the join keys everything that encrypts with it
// references.
type AwsKmsKeyOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated key ID (UUID; "mrk-..." for multi-Region keys).
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// The key ARN -- the join key encryption-at-rest fields across the
	// catalog reference (databases, queues, buckets, functions, ...).
	KeyArn string `protobuf:"bytes,2,opt,name=key_arn,json=keyArn,proto3" json:"key_arn,omitempty"`
	// The alias names attached to the key (each "alias/..."), in spec
	// order -- the human-friendly addresses SDK callers may use instead
	// of the key ID.
	AliasNames []string `protobuf:"bytes,3,rep,name=alias_names,json=aliasNames,proto3" json:"alias_names,omitempty"`
	// The AWS-generated grant IDs, keyed exactly as the module keys each
	// grant: by the entry's position in spec.grants ("0", "1", ...). Grant
	// identity lives in these IDs, not in the optional friendly name --
	// RetireGrant/RevokeGrant and state import take them. (The one-time
	// grant TOKEN from creation stays deliberately unexposed: it is a
	// sensitive eventual-consistency bridge, not an identifier.)
	GrantIds      map[string]string `protobuf:"bytes,4,rep,name=grant_ids,json=grantIds,proto3" json:"grant_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsKmsKeyOutputs) Reset() {
	*x = AwsKmsKeyOutputs{}
	mi := &file_catalog_aws_awskmskey_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsKmsKeyOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsKmsKeyOutputs) ProtoMessage() {}

func (x *AwsKmsKeyOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awskmskey_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsKmsKeyOutputs.ProtoReflect.Descriptor instead.
func (*AwsKmsKeyOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *AwsKmsKeyOutputs) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AwsKmsKeyOutputs) GetKeyArn() string {
	if x != nil {
		return x.KeyArn
	}
	return ""
}

func (x *AwsKmsKeyOutputs) GetAliasNames() []string {
	if x != nil {
		return x.AliasNames
	}
	return nil
}

func (x *AwsKmsKeyOutputs) GetGrantIds() map[string]string {
	if x != nil {
		return x.GrantIds
	}
	return nil
}

var File_catalog_aws_awskmskey_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	",catalog/aws/awskmskey/v1alpha1/outputs.proto\x12\"dev.planton.aws.awskmskey.v1alpha1\"\x81\x02\n" +
	"\x10AwsKmsKeyOutputs\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\akey_arn\x18\x02 \x01(\tR\x06keyArn\x12\x1f\n" +
	"\valias_names\x18\x03 \x03(\tR\n" +
	"aliasNames\x12_\n" +
	"\tgrant_ids\x18\x04 \x03(\v2B.dev.planton.aws.awskmskey.v1alpha1.AwsKmsKeyOutputs.GrantIdsEntryR\bgrantIds\x1a;\n" +
	"\rGrantIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xb2\x02\n" +
	"&com.dev.planton.aws.awskmskey.v1alpha1B\fOutputsProtoP\x01ZMgithub.com/plantonhq/planton/catalog/aws/awskmskey/v1alpha1;awskmskeyv1alpha1\xa2\x02\x04DPAA\xaa\x02\"Dev.Planton.Aws.Awskmskey.V1alpha1\xca\x02\"Dev\\Planton\\Aws\\Awskmskey\\V1alpha1\xe2\x02.Dev\\Planton\\Aws\\Awskmskey\\V1alpha1\\GPBMetadata\xea\x02&Dev::Planton::Aws::Awskmskey::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_aws_awskmskey_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_aws_awskmskey_v1alpha1_outputs_proto_goTypes = []any{
	(*AwsKmsKeyOutputs)(nil), // 0: dev.planton.aws.awskmskey.v1alpha1.AwsKmsKeyOutputs
	nil,                      // 1: dev.planton.aws.awskmskey.v1alpha1.AwsKmsKeyOutputs.GrantIdsEntry
}
var file_catalog_aws_awskmskey_v1alpha1_outputs_proto_depIdxs = []int32{
	1, // 0: dev.planton.aws.awskmskey.v1alpha1.AwsKmsKeyOutputs.grant_ids:type_name -> dev.planton.aws.awskmskey.v1alpha1.AwsKmsKeyOutputs.GrantIdsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_aws_awskmskey_v1alpha1_outputs_proto_init() }
func file_catalog_aws_awskmskey_v1alpha1_outputs_proto_init() {
	if File_catalog_aws_awskmskey_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awskmskey_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awskmskey_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awskmskey_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awskmskey_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_aws_awskmskey_v1alpha1_outputs_proto = out.File
	file_catalog_aws_awskmskey_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_aws_awskmskey_v1alpha1_outputs_proto_depIdxs = nil
}
