syntax = "proto3";

package dev.planton.gcp.gcpmodelarmortemplate.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcpmodelarmortemplate/v1alpha1/outputs.proto";
import "catalog/gcp/gcpmodelarmortemplate/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-model-armor-template
message GcpModelArmorTemplate {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'GcpModelArmorTemplate'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  GcpModelArmorTemplateSpec spec = 4 [(buf.validate.field).required = true];

  //status
  GcpModelArmorTemplateStatus status = 5;
}

//gcp-model-armor-template status
message GcpModelArmorTemplateStatus {
  //stack-outputs
  GcpModelArmorTemplateStackOutputs outputs = 1;
}
