// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpmodelarmortemplate/v1alpha1/outputs.proto

package gcpmodelarmortemplatev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcpModelArmorTemplateStackOutputs carries the identity an application or
// a Vertex AI Search engine names the template by.
type GcpModelArmorTemplateStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full resource name:
	// projects/{project}/locations/{location}/templates/{template_id} -- what
	// sanitize calls and GcpVertexAiSearchEngine's model_armor_config take.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The template's id (the last segment of name).
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The location the template lives in; the application calls Model
	// Armor's endpoint for this location.
	Location      string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpModelArmorTemplateStackOutputs) Reset() {
	*x = GcpModelArmorTemplateStackOutputs{}
	mi := &file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpModelArmorTemplateStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpModelArmorTemplateStackOutputs) ProtoMessage() {}

func (x *GcpModelArmorTemplateStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpModelArmorTemplateStackOutputs.ProtoReflect.Descriptor instead.
func (*GcpModelArmorTemplateStackOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *GcpModelArmorTemplateStackOutputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GcpModelArmorTemplateStackOutputs) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *GcpModelArmorTemplateStackOutputs) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	"8catalog/gcp/gcpmodelarmortemplate/v1alpha1/outputs.proto\x12.dev.planton.gcp.gcpmodelarmortemplate.v1alpha1\"t\n" +
	"!GcpModelArmorTemplateStackOutputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocationB\x86\x03\n" +
	"2com.dev.planton.gcp.gcpmodelarmortemplate.v1alpha1B\fOutputsProtoP\x01Zegithub.com/plantonhq/planton/catalog/gcp/gcpmodelarmortemplate/v1alpha1;gcpmodelarmortemplatev1alpha1\xa2\x02\x04DPGG\xaa\x02.Dev.Planton.Gcp.Gcpmodelarmortemplate.V1alpha1\xca\x02.Dev\\Planton\\Gcp\\Gcpmodelarmortemplate\\V1alpha1\xe2\x02:Dev\\Planton\\Gcp\\Gcpmodelarmortemplate\\V1alpha1\\GPBMetadata\xea\x022Dev::Planton::Gcp::Gcpmodelarmortemplate::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDesc), len(file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_goTypes = []any{
	(*GcpModelArmorTemplateStackOutputs)(nil), // 0: dev.planton.gcp.gcpmodelarmortemplate.v1alpha1.GcpModelArmorTemplateStackOutputs
}
var file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_init() }
func file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_init() {
	if File_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDesc), len(file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto = out.File
	file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_gcp_gcpmodelarmortemplate_v1alpha1_outputs_proto_depIdxs = nil
}
