.PHONY: preview
preview:
	planton pulumi preview --manifest $(manifest)

.PHONY: up
up:
	planton pulumi up --manifest $(manifest)

.PHONY: down
down:
	planton pulumi down --manifest $(manifest)

.PHONY: refresh
refresh:
	planton pulumi refresh --manifest $(manifest)
