apiVersion: digital-ocean.openmcf.org/v1
kind: DigitalOceanDatabaseCluster
metadata:
  name: my-redis-cache
spec:
  clusterName: my-redis-cache
  engine: redis
  engineVersion: "7"
  region: nyc3
  sizeSlug: db-s-1vcpu-1gb
  nodeCount: 1
  vpc:
    value: "<vpc-id>"
