// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/openmcf/provider/aws/awstransitgateway/v1/stack_outputs.proto

package awstransitgatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsTransitGatewayStackOutputs captures observable identifiers from a
// provisioned Transit Gateway and its VPC attachments.
//
// These outputs are the primary interface for downstream resources. The
// transit_gateway_id is referenced by VPN connections, Direct Connect
// gateways, and any future Transit Gateway route or peering resources.
// The route table IDs enable future static route management without
// modifying the Transit Gateway itself.
type AwsTransitGatewayStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Transit Gateway ID (e.g., "tgw-0123456789abcdef0"). This is the
	// primary identifier used by VPN connections, Direct Connect gateways,
	// peering attachments, and any resource that attaches to the TGW.
	TransitGatewayId string `protobuf:"bytes,1,opt,name=transit_gateway_id,json=transitGatewayId,proto3" json:"transit_gateway_id,omitempty"`
	// The Amazon Resource Name (ARN) of the Transit Gateway. Used for IAM
	// policies, resource-level permissions, and AWS RAM sharing.
	TransitGatewayArn string `protobuf:"bytes,2,opt,name=transit_gateway_arn,json=transitGatewayArn,proto3" json:"transit_gateway_arn,omitempty"`
	// The AWS account ID that owns this Transit Gateway.
	OwnerId string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// The ID of the default association route table. Attachments with
	// default_route_table_association enabled are automatically associated
	// with this route table. Useful for creating static routes via a
	// future AwsTransitGatewayRoute component.
	AssociationDefaultRouteTableId string `protobuf:"bytes,4,opt,name=association_default_route_table_id,json=associationDefaultRouteTableId,proto3" json:"association_default_route_table_id,omitempty"`
	// The ID of the default propagation route table. Attachments with
	// default_route_table_propagation enabled automatically propagate their
	// routes to this table.
	PropagationDefaultRouteTableId string `protobuf:"bytes,5,opt,name=propagation_default_route_table_id,json=propagationDefaultRouteTableId,proto3" json:"propagation_default_route_table_id,omitempty"`
	// Map of attachment name to VPC attachment ID. The keys correspond to
	// the name field of each entry in spec.vpc_attachments. Downstream
	// resources can reference specific attachment IDs via valueFrom using
	// status.outputs.vpc_attachment_ids.{name}.
	VpcAttachmentIds map[string]string `protobuf:"bytes,6,rep,name=vpc_attachment_ids,json=vpcAttachmentIds,proto3" json:"vpc_attachment_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AwsTransitGatewayStackOutputs) Reset() {
	*x = AwsTransitGatewayStackOutputs{}
	mi := &file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsTransitGatewayStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsTransitGatewayStackOutputs) ProtoMessage() {}

func (x *AwsTransitGatewayStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsTransitGatewayStackOutputs.ProtoReflect.Descriptor instead.
func (*AwsTransitGatewayStackOutputs) Descriptor() ([]byte, []int) {
	return file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *AwsTransitGatewayStackOutputs) GetTransitGatewayId() string {
	if x != nil {
		return x.TransitGatewayId
	}
	return ""
}

func (x *AwsTransitGatewayStackOutputs) GetTransitGatewayArn() string {
	if x != nil {
		return x.TransitGatewayArn
	}
	return ""
}

func (x *AwsTransitGatewayStackOutputs) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AwsTransitGatewayStackOutputs) GetAssociationDefaultRouteTableId() string {
	if x != nil {
		return x.AssociationDefaultRouteTableId
	}
	return ""
}

func (x *AwsTransitGatewayStackOutputs) GetPropagationDefaultRouteTableId() string {
	if x != nil {
		return x.PropagationDefaultRouteTableId
	}
	return ""
}

func (x *AwsTransitGatewayStackOutputs) GetVpcAttachmentIds() map[string]string {
	if x != nil {
		return x.VpcAttachmentIds
	}
	return nil
}

var File_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Aorg/openmcf/provider/aws/awstransitgateway/v1/stack_outputs.proto\x12-org.openmcf.provider.aws.awstransitgateway.v1\"\x88\x04\n" +
	"\x1dAwsTransitGatewayStackOutputs\x12,\n" +
	"\x12transit_gateway_id\x18\x01 \x01(\tR\x10transitGatewayId\x12.\n" +
	"\x13transit_gateway_arn\x18\x02 \x01(\tR\x11transitGatewayArn\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12J\n" +
	"\"association_default_route_table_id\x18\x04 \x01(\tR\x1eassociationDefaultRouteTableId\x12J\n" +
	"\"propagation_default_route_table_id\x18\x05 \x01(\tR\x1epropagationDefaultRouteTableId\x12\x90\x01\n" +
	"\x12vpc_attachment_ids\x18\x06 \x03(\v2b.org.openmcf.provider.aws.awstransitgateway.v1.AwsTransitGatewayStackOutputs.VpcAttachmentIdsEntryR\x10vpcAttachmentIds\x1aC\n" +
	"\x15VpcAttachmentIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x86\x03\n" +
	"1com.org.openmcf.provider.aws.awstransitgateway.v1B\x11StackOutputsProtoP\x01Zcgithub.com/plantonhq/openmcf/apis/org/openmcf/provider/aws/awstransitgateway/v1;awstransitgatewayv1\xa2\x02\x05OOPAA\xaa\x02-Org.Openmcf.Provider.Aws.Awstransitgateway.V1\xca\x02-Org\\Openmcf\\Provider\\Aws\\Awstransitgateway\\V1\xe2\x029Org\\Openmcf\\Provider\\Aws\\Awstransitgateway\\V1\\GPBMetadata\xea\x022Org::Openmcf::Provider::Aws::Awstransitgateway::V1b\x06proto3"

var (
	file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescData []byte
)

func file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDesc), len(file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDesc)))
	})
	return file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDescData
}

var file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_goTypes = []any{
	(*AwsTransitGatewayStackOutputs)(nil), // 0: org.openmcf.provider.aws.awstransitgateway.v1.AwsTransitGatewayStackOutputs
	nil,                                   // 1: org.openmcf.provider.aws.awstransitgateway.v1.AwsTransitGatewayStackOutputs.VpcAttachmentIdsEntry
}
var file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_depIdxs = []int32{
	1, // 0: org.openmcf.provider.aws.awstransitgateway.v1.AwsTransitGatewayStackOutputs.vpc_attachment_ids:type_name -> org.openmcf.provider.aws.awstransitgateway.v1.AwsTransitGatewayStackOutputs.VpcAttachmentIdsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_init() }
func file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_init() {
	if File_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDesc), len(file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto = out.File
	file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_goTypes = nil
	file_org_openmcf_provider_aws_awstransitgateway_v1_stack_outputs_proto_depIdxs = nil
}
