load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "keycloak_cr.go",
        "locals.go",
        "main.go",
        "namespace.go",
        "outputs.go",
        "vars.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/kubernetes/kuberneteskeycloak/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/kubernetes",
        "//catalog/kubernetes/kuberneteskeycloak/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/kubernetes/kuberneteslabelkeys",
        "//pkg/iac/pulumi/pulumimodule/provider/kubernetes/pulumikubernetesprovider",
        "//shared/catalogkind",
        "//shared/foreignkey/v1:foreignkey",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/apiextensions",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/core/v1:core",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/meta/v1:meta",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
