syntax = "proto3";

package dev.planton.aws.awssubnet.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awssubnet/v1alpha1/outputs.proto";
import "catalog/aws/awssubnet/v1alpha1/spec.proto";
import "shared/metadata.proto";

// AwsSubnet is the top-level resource representing a single subnet within an AWS
// Virtual Private Cloud (VPC).
message AwsSubnet {
  // api-version
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];

  // resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AwsSubnet'];

  // metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  // spec
  AwsSubnetSpec spec = 4 [(buf.validate.field).required = true];

  // status
  AwsSubnetStatus status = 5;
}

// AwsSubnetStatus holds the outputs produced by deploying an AwsSubnet.
message AwsSubnetStatus {
  // outputs
  AwsSubnetOutputs outputs = 1;
}
