syntax = "proto3";

package dev.planton.aws.awsmanagedprometheusscraper.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsmanagedprometheusscraper/v1alpha1/outputs.proto";
import "catalog/aws/awsmanagedprometheusscraper/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsManagedPrometheusScraper {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsManagedPrometheusScraper'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsManagedPrometheusScraperSpec spec = 4 [(buf.validate.field).required = true];
  AwsManagedPrometheusScraperStatus status = 5;
}

message AwsManagedPrometheusScraperStatus {
  AwsManagedPrometheusScraperOutputs outputs = 1;
}
