syntax = "proto3";

package dev.planton.aws.awsguardduty.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsguardduty/v1alpha1/outputs.proto";
import "catalog/aws/awsguardduty/v1alpha1/spec.proto";
import "shared/metadata.proto";

message AwsGuardDuty {
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'AwsGuardDuty'];
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];
  AwsGuardDutySpec spec = 4 [(buf.validate.field).required = true];
  AwsGuardDutyStatus status = 5;
}

message AwsGuardDutyStatus {
  AwsGuardDutyOutputs outputs = 1;
}
