syntax = "proto3";

package dev.planton.aws.awsguardduty.v1alpha1;

import "catalog/aws/awsguardduty/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsGuardDutyIacInput is the input for the IaC modules that manage
// the region's GuardDuty posture.
message AwsGuardDutyIacInput {
  // target is the AwsGuardDuty resource to deploy.
  AwsGuardDuty target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
