apiVersion: alicloud.openmcf.org/v1
kind: AlicloudVpnGateway
metadata:
  name: <your-vpn-name>
spec:
  region: <alibaba-cloud-region>
  vpcId:
    value: <your-vpc-id>
  vswitchId:
    value: <your-vswitch-id>
  vpnGatewayName: <your-vpn-name>
  bandwidth: 10
  connections:
    - name: <connection-name>
      customerGatewayIp: "<remote-device-public-ip>"
      localSubnets:
        - "<vpc-cidr>"
      remoteSubnets:
        - "<remote-network-cidr>"
