// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azurefrontdoorroute/v1alpha1/api.proto

package azurefrontdoorroutev1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureFrontDoorRoute is the top-level API resource for a route inside an
// Azure Front Door endpoint (referenced via endpoint_id): the rule that
// matches client requests by URL pattern and forwards them to an origin
// group, with protocol policy and edge caching.
type AzureFrontDoorRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *AzureFrontDoorRouteSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *AzureFrontDoorRouteStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureFrontDoorRoute) Reset() {
	*x = AzureFrontDoorRoute{}
	mi := &file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureFrontDoorRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureFrontDoorRoute) ProtoMessage() {}

func (x *AzureFrontDoorRoute) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureFrontDoorRoute.ProtoReflect.Descriptor instead.
func (*AzureFrontDoorRoute) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AzureFrontDoorRoute) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AzureFrontDoorRoute) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AzureFrontDoorRoute) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AzureFrontDoorRoute) GetSpec() *AzureFrontDoorRouteSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AzureFrontDoorRoute) GetStatus() *AzureFrontDoorRouteStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AzureFrontDoorRouteStatus holds the deployment status and outputs.
type AzureFrontDoorRouteStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs
	Outputs       *AzureFrontDoorRouteOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureFrontDoorRouteStatus) Reset() {
	*x = AzureFrontDoorRouteStatus{}
	mi := &file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureFrontDoorRouteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureFrontDoorRouteStatus) ProtoMessage() {}

func (x *AzureFrontDoorRouteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureFrontDoorRouteStatus.ProtoReflect.Descriptor instead.
func (*AzureFrontDoorRouteStatus) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AzureFrontDoorRouteStatus) GetOutputs() *AzureFrontDoorRouteOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"4catalog/azure/azurefrontdoorroute/v1alpha1/api.proto\x12.dev.planton.azure.azurefrontdoorroute.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a8catalog/azure/azurefrontdoorroute/v1alpha1/outputs.proto\x1a5catalog/azure/azurefrontdoorroute/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xa0\x03\n" +
	"\x13AzureFrontDoorRoute\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1aazure.planton.dev/v1alpha1R\n" +
	"apiVersion\x12.\n" +
	"\x04kind\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\n" +
	"\x13AzureFrontDoorRouteR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12c\n" +
	"\x04spec\x18\x04 \x01(\v2G.dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12a\n" +
	"\x06status\x18\x05 \x01(\v2I.dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteStatusR\x06status\"\x81\x01\n" +
	"\x19AzureFrontDoorRouteStatus\x12d\n" +
	"\aoutputs\x18\x01 \x01(\v2J.dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteOutputsR\aoutputsB\x80\x03\n" +
	"2com.dev.planton.azure.azurefrontdoorroute.v1alpha1B\bApiProtoP\x01Zcgithub.com/plantonhq/planton/catalog/azure/azurefrontdoorroute/v1alpha1;azurefrontdoorroutev1alpha1\xa2\x02\x04DPAA\xaa\x02.Dev.Planton.Azure.Azurefrontdoorroute.V1alpha1\xca\x02.Dev\\Planton\\Azure\\Azurefrontdoorroute\\V1alpha1\xe2\x02:Dev\\Planton\\Azure\\Azurefrontdoorroute\\V1alpha1\\GPBMetadata\xea\x022Dev::Planton::Azure::Azurefrontdoorroute::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDesc), len(file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDescData
}

var file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_goTypes = []any{
	(*AzureFrontDoorRoute)(nil),          // 0: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRoute
	(*AzureFrontDoorRouteStatus)(nil),    // 1: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteStatus
	(*shared.CatalogObjectMetadata)(nil), // 2: dev.planton.shared.CatalogObjectMetadata
	(*AzureFrontDoorRouteSpec)(nil),      // 3: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteSpec
	(*AzureFrontDoorRouteOutputs)(nil),   // 4: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteOutputs
}
var file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRoute.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRoute.spec:type_name -> dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteSpec
	1, // 2: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRoute.status:type_name -> dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteStatus
	4, // 3: dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteStatus.outputs:type_name -> dev.planton.azure.azurefrontdoorroute.v1alpha1.AzureFrontDoorRouteOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_init() }
func file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_init() {
	if File_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_azure_azurefrontdoorroute_v1alpha1_outputs_proto_init()
	file_catalog_azure_azurefrontdoorroute_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDesc), len(file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto = out.File
	file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_goTypes = nil
	file_catalog_azure_azurefrontdoorroute_v1alpha1_api_proto_depIdxs = nil
}
