syntax = "proto3";

package dev.planton.gcp.gcphierarchicalfirewallpolicy.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcphierarchicalfirewallpolicy/v1alpha1/outputs.proto";
import "catalog/gcp/gcphierarchicalfirewallpolicy/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-hierarchical-firewall-policy
message GcpHierarchicalFirewallPolicy {
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];
  string kind = 2 [(buf.validate.field).string.const = 'GcpHierarchicalFirewallPolicy'];
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];
  GcpHierarchicalFirewallPolicySpec spec = 4 [(buf.validate.field).required = true];
  GcpHierarchicalFirewallPolicyStatus status = 5;
}

message GcpHierarchicalFirewallPolicyStatus {
  GcpHierarchicalFirewallPolicyStackOutputs outputs = 1;
}
