apiVersion: aws.openmcf.org/v1
kind: AwsRoute53Zone
metadata:
  name: my-private-dns-zone
spec:
  region: us-east-1
  isPrivate: true
  vpcAssociations:
    - vpcId: <vpc-id>
      vpcRegion: <aws-region>
