syntax = "proto3";

package dev.planton.aws.awsbackuprestoretestingplan.v1alpha1;

import "catalog/aws/awsbackuprestoretestingplan/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsBackupRestoreTestingPlanIacInput is the input for the IaC
// modules that manage an AWS Backup restore testing plan.
message AwsBackupRestoreTestingPlanIacInput {
  // target is the AwsBackupRestoreTestingPlan resource to deploy.
  AwsBackupRestoreTestingPlan target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
