syntax = "proto3";

package dev.planton.azure.azuredatafactorylinkedservice.v1alpha1;

import "catalog/azure/azuredatafactorylinkedservice/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureDataFactoryLinkedServiceIacInput is the input to the IaC
// modules (Pulumi/Terraform). It contains the target resource
// definition and Azure provider credentials.
message AzureDataFactoryLinkedServiceIacInput {
  // The Data Factory linked service resource to deploy.
  AzureDataFactoryLinkedService target = 1;

  // Azure provider configuration (credentials).
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
