syntax = "proto3";

package dev.planton.gcp.gcpvertexaisearchdatastore.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcpvertexaisearchdatastore/v1alpha1/outputs.proto";
import "catalog/gcp/gcpvertexaisearchdatastore/v1alpha1/spec.proto";
import "shared/metadata.proto";

//gcp-vertex-ai-search-data-store
message GcpVertexAiSearchDataStore {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'GcpVertexAiSearchDataStore'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  GcpVertexAiSearchDataStoreSpec spec = 4 [(buf.validate.field).required = true];

  //status
  GcpVertexAiSearchDataStoreStatus status = 5;
}

//gcp-vertex-ai-search-data-store status
message GcpVertexAiSearchDataStoreStatus {
  //stack-outputs
  GcpVertexAiSearchDataStoreStackOutputs outputs = 1;
}
