apiVersion: kubernetes.planton.dev/v1
kind: KubernetesIstio
metadata:
  name: my-istio
spec:
  namespace:
    value: istio-system
  createNamespace: true
  container:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1Gi
