load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "terraform",
    srcs = [
        "apply.go",
        "destroy.go",
        "init.go",
        "plan.go",
        "refresh.go",
    ],
    importpath = "github.com/plantonhq/planton/cmd/planton/root/terraform",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/cli/cliprint",
        "//internal/cli/flag",
        "//internal/cli/manifest",
        "//internal/cli/ui",
        "//internal/cli/workspace",
        "//internal/manifest",
        "//pkg/catalogkindreflect",
        "//pkg/iac/iacinput",
        "//pkg/iac/iacinput/iacinputproviderconfig",
        "//pkg/iac/localmodule",
        "//pkg/iac/provisioner",
        "//pkg/iac/tofu/tfbackend",
        "//pkg/iac/tofu/tofumodule",
        "//pkg/kubernetes/kubecontext",
        "//shared",
        "//shared/iac/terraform",
        "@com_github_spf13_cobra//:cobra",
    ],
)
