syntax = "proto3";

package dev.planton.aws.awstransitgatewayvpcattachment.v1alpha1;

import "catalog/aws/awstransitgatewayvpcattachment/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsTransitGatewayVpcAttachmentIacInput is the input for the
// aws-transit-gateway-vpc-attachment IaC modules.
message AwsTransitGatewayVpcAttachmentIacInput {
  // target infra-component
  AwsTransitGatewayVpcAttachment target = 1;

  // provider-config
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
