apiVersion: gcp.planton.dev/v1
kind: GcpDataprocCluster
metadata:
  name: my-batch-spark
spec:
  projectId:
    value: "<your-gcp-project-id>"
  region: us-central1
  clusterName: my-batch-spark
  clusterConfig:
    masterConfig:
      numInstances: 1
      machineType: n2-standard-4
      diskConfig:
        bootDiskSizeGb: 100
    workerConfig:
      numInstances: 2
      machineType: n2-standard-4
      diskConfig:
        bootDiskSizeGb: 200
    secondaryWorkerConfig:
      numInstances: 10
      preemptibility: SPOT
      diskConfig:
        bootDiskSizeGb: 100
    softwareConfig:
      imageVersion: "2.2-debian12"
      properties:
        "spark:spark.dynamicAllocation.enabled": "true"
        "spark:spark.shuffle.service.enabled": "true"
    lifecycleConfig:
      idleDeleteTtl: "900s" # Auto-delete after 15 minutes idle
