apiVersion: kubernetes.openmcf.org/v1
kind: KubernetesExternalSecrets
metadata:
  name: my-external-secrets
spec:
  namespace:
    value: external-secrets
  createNamespace: true
  container:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  gke:
    projectId:
      value: "<your-gcp-project-id>"
    gsaEmail: "<your-gsa-email@your-project.iam.gserviceaccount.com>"
