// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/cloudflare/cloudflareturnstilewidget/v1alpha1/api.proto

package cloudflareturnstilewidgetv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// cloudflare-turnstile-widget
type CloudflareTurnstileWidget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CatalogObjectMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *CloudflareTurnstileWidgetSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *CloudflareTurnstileWidgetStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudflareTurnstileWidget) Reset() {
	*x = CloudflareTurnstileWidget{}
	mi := &file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudflareTurnstileWidget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudflareTurnstileWidget) ProtoMessage() {}

func (x *CloudflareTurnstileWidget) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudflareTurnstileWidget.ProtoReflect.Descriptor instead.
func (*CloudflareTurnstileWidget) Descriptor() ([]byte, []int) {
	return file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CloudflareTurnstileWidget) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *CloudflareTurnstileWidget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CloudflareTurnstileWidget) GetMetadata() *shared.CatalogObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CloudflareTurnstileWidget) GetSpec() *CloudflareTurnstileWidgetSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CloudflareTurnstileWidget) GetStatus() *CloudflareTurnstileWidgetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// cloudflare-turnstile-widget status
type CloudflareTurnstileWidgetStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs
	//
	//	cloudflare-turnstile-widget outputs
	Outputs       *CloudflareTurnstileWidgetOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudflareTurnstileWidgetStatus) Reset() {
	*x = CloudflareTurnstileWidgetStatus{}
	mi := &file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudflareTurnstileWidgetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudflareTurnstileWidgetStatus) ProtoMessage() {}

func (x *CloudflareTurnstileWidgetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudflareTurnstileWidgetStatus.ProtoReflect.Descriptor instead.
func (*CloudflareTurnstileWidgetStatus) Descriptor() ([]byte, []int) {
	return file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CloudflareTurnstileWidgetStatus) GetOutputs() *CloudflareTurnstileWidgetOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"?catalog/cloudflare/cloudflareturnstilewidget/v1alpha1/api.proto\x129dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1aCcatalog/cloudflare/cloudflareturnstilewidget/v1alpha1/outputs.proto\x1a@catalog/cloudflare/cloudflareturnstilewidget/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xd3\x03\n" +
	"\x19CloudflareTurnstileWidget\x12G\n" +
	"\vapi_version\x18\x01 \x01(\tB&\xbaH#r!\n" +
	"\x1fcloudflare.planton.dev/v1alpha1R\n" +
	"apiVersion\x124\n" +
	"\x04kind\x18\x02 \x01(\tB \xbaH\x1dr\x1b\n" +
	"\x19CloudflareTurnstileWidgetR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CatalogObjectMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12t\n" +
	"\x04spec\x18\x04 \x01(\v2X.dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12r\n" +
	"\x06status\x18\x05 \x01(\v2Z.dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetStatusR\x06status\"\x98\x01\n" +
	"\x1fCloudflareTurnstileWidgetStatus\x12u\n" +
	"\aoutputs\x18\x01 \x01(\v2[.dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetOutputsR\aoutputsB\xc8\x03\n" +
	"=com.dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1B\bApiProtoP\x01Ztgithub.com/plantonhq/planton/catalog/cloudflare/cloudflareturnstilewidget/v1alpha1;cloudflareturnstilewidgetv1alpha1\xa2\x02\x04DPCC\xaa\x029Dev.Planton.Cloudflare.Cloudflareturnstilewidget.V1alpha1\xca\x029Dev\\Planton\\Cloudflare\\Cloudflareturnstilewidget\\V1alpha1\xe2\x02EDev\\Planton\\Cloudflare\\Cloudflareturnstilewidget\\V1alpha1\\GPBMetadata\xea\x02=Dev::Planton::Cloudflare::Cloudflareturnstilewidget::V1alpha1b\x06proto3"

var (
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDesc), len(file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDescData
}

var file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_goTypes = []any{
	(*CloudflareTurnstileWidget)(nil),        // 0: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidget
	(*CloudflareTurnstileWidgetStatus)(nil),  // 1: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetStatus
	(*shared.CatalogObjectMetadata)(nil),     // 2: dev.planton.shared.CatalogObjectMetadata
	(*CloudflareTurnstileWidgetSpec)(nil),    // 3: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetSpec
	(*CloudflareTurnstileWidgetOutputs)(nil), // 4: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetOutputs
}
var file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidget.metadata:type_name -> dev.planton.shared.CatalogObjectMetadata
	3, // 1: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidget.spec:type_name -> dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetSpec
	1, // 2: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidget.status:type_name -> dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetStatus
	4, // 3: dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetStatus.outputs:type_name -> dev.planton.cloudflare.cloudflareturnstilewidget.v1alpha1.CloudflareTurnstileWidgetOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_init() }
func file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_init() {
	if File_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_outputs_proto_init()
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDesc), len(file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto = out.File
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_goTypes = nil
	file_catalog_cloudflare_cloudflareturnstilewidget_v1alpha1_api_proto_depIdxs = nil
}
