// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/hetznercloud/hetznercloudplacementgroup/v1/stack_outputs.proto

package hetznercloudplacementgroupv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HetznerCloudPlacementGroupStackOutputs captures the resulting placement group
// identifiers after provisioning.
type HetznerCloudPlacementGroupStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Hetzner Cloud numeric ID of the created placement group (as a string).
	// Referenced by HetznerCloudServer.placement_group_id via StringValueOrRef.
	PlacementGroupId string `protobuf:"bytes,1,opt,name=placement_group_id,json=placementGroupId,proto3" json:"placement_group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HetznerCloudPlacementGroupStackOutputs) Reset() {
	*x = HetznerCloudPlacementGroupStackOutputs{}
	mi := &file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HetznerCloudPlacementGroupStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HetznerCloudPlacementGroupStackOutputs) ProtoMessage() {}

func (x *HetznerCloudPlacementGroupStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HetznerCloudPlacementGroupStackOutputs.ProtoReflect.Descriptor instead.
func (*HetznerCloudPlacementGroupStackOutputs) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *HetznerCloudPlacementGroupStackOutputs) GetPlacementGroupId() string {
	if x != nil {
		return x.PlacementGroupId
	}
	return ""
}

var File_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Sdev/planton/provider/hetznercloud/hetznercloudplacementgroup/v1/stack_outputs.proto\x12?dev.planton.provider.hetznercloud.hetznercloudplacementgroup.v1\"V\n" +
	"&HetznerCloudPlacementGroupStackOutputs\x12,\n" +
	"\x12placement_group_id\x18\x01 \x01(\tR\x10placementGroupIdB\xfb\x03\n" +
	"Ccom.dev.planton.provider.hetznercloud.hetznercloudplacementgroup.v1B\x11StackOutputsProtoP\x01Z~github.com/plantonhq/planton/apis/dev/planton/provider/hetznercloud/hetznercloudplacementgroup/v1;hetznercloudplacementgroupv1\xa2\x02\x05DPPHH\xaa\x02?Dev.Planton.Provider.Hetznercloud.Hetznercloudplacementgroup.V1\xca\x02?Dev\\Planton\\Provider\\Hetznercloud\\Hetznercloudplacementgroup\\V1\xe2\x02KDev\\Planton\\Provider\\Hetznercloud\\Hetznercloudplacementgroup\\V1\\GPBMetadata\xea\x02DDev::Planton::Provider::Hetznercloud::Hetznercloudplacementgroup::V1b\x06proto3"

var (
	file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescData []byte
)

func file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDesc), len(file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDesc)))
	})
	return file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDescData
}

var file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_goTypes = []any{
	(*HetznerCloudPlacementGroupStackOutputs)(nil), // 0: dev.planton.provider.hetznercloud.hetznercloudplacementgroup.v1.HetznerCloudPlacementGroupStackOutputs
}
var file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_init()
}
func file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_init() {
	if File_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDesc), len(file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto = out.File
	file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_goTypes = nil
	file_dev_planton_provider_hetznercloud_hetznercloudplacementgroup_v1_stack_outputs_proto_depIdxs = nil
}
