// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awscloudmapnamespace/v1alpha1/outputs.proto

package awscloudmapnamespacev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsCloudMapNamespaceOutputs captures the observable state of
// the Cloud Map namespace after apply.
type AwsCloudMapNamespaceOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace's id (ns-...) - the provider's import ID (a
	// PRIVATE_DNS namespace imports as "{namespace_id}:{vpc_id}").
	NamespaceId string `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// The namespace's ARN.
	NamespaceArn string `protobuf:"bytes,2,opt,name=namespace_arn,json=namespaceArn,proto3" json:"namespace_arn,omitempty"`
	// The Route 53 hosted zone Cloud Map created for a DNS namespace -
	// what record-level tooling and zone delegations reference.
	HostedZoneId string `protobuf:"bytes,3,opt,name=hosted_zone_id,json=hostedZoneId,proto3" json:"hosted_zone_id,omitempty"`
	// The name an HTTP namespace's DiscoverInstances calls use.
	HttpName string `protobuf:"bytes,4,opt,name=http_name,json=httpName,proto3" json:"http_name,omitempty"`
	// AWS-generated service IDs (srv-...) keyed by service name - what
	// instance registrations and imports reference.
	ServiceIds map[string]string `protobuf:"bytes,5,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Service ARNs keyed by service name - what ECS service
	// registries wire as the registry_arn.
	ServiceArns map[string]string `protobuf:"bytes,6,rep,name=service_arns,json=serviceArns,proto3" json:"service_arns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Each registration's owning service ID keyed by
	// "{service_name}//{instance_id}" - the first half of the
	// instance's composite import ID.
	InstanceServiceIds map[string]string `protobuf:"bytes,7,rep,name=instance_service_ids,json=instanceServiceIds,proto3" json:"instance_service_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AwsCloudMapNamespaceOutputs) Reset() {
	*x = AwsCloudMapNamespaceOutputs{}
	mi := &file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsCloudMapNamespaceOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsCloudMapNamespaceOutputs) ProtoMessage() {}

func (x *AwsCloudMapNamespaceOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsCloudMapNamespaceOutputs.ProtoReflect.Descriptor instead.
func (*AwsCloudMapNamespaceOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *AwsCloudMapNamespaceOutputs) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *AwsCloudMapNamespaceOutputs) GetNamespaceArn() string {
	if x != nil {
		return x.NamespaceArn
	}
	return ""
}

func (x *AwsCloudMapNamespaceOutputs) GetHostedZoneId() string {
	if x != nil {
		return x.HostedZoneId
	}
	return ""
}

func (x *AwsCloudMapNamespaceOutputs) GetHttpName() string {
	if x != nil {
		return x.HttpName
	}
	return ""
}

func (x *AwsCloudMapNamespaceOutputs) GetServiceIds() map[string]string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *AwsCloudMapNamespaceOutputs) GetServiceArns() map[string]string {
	if x != nil {
		return x.ServiceArns
	}
	return nil
}

func (x *AwsCloudMapNamespaceOutputs) GetInstanceServiceIds() map[string]string {
	if x != nil {
		return x.InstanceServiceIds
	}
	return nil
}

var File_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	"7catalog/aws/awscloudmapnamespace/v1alpha1/outputs.proto\x12-dev.planton.aws.awscloudmapnamespace.v1alpha1\"\x82\x06\n" +
	"\x1bAwsCloudMapNamespaceOutputs\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12#\n" +
	"\rnamespace_arn\x18\x02 \x01(\tR\fnamespaceArn\x12$\n" +
	"\x0ehosted_zone_id\x18\x03 \x01(\tR\fhostedZoneId\x12\x1b\n" +
	"\thttp_name\x18\x04 \x01(\tR\bhttpName\x12{\n" +
	"\vservice_ids\x18\x05 \x03(\v2Z.dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.ServiceIdsEntryR\n" +
	"serviceIds\x12~\n" +
	"\fservice_arns\x18\x06 \x03(\v2[.dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.ServiceArnsEntryR\vserviceArns\x12\x94\x01\n" +
	"\x14instance_service_ids\x18\a \x03(\v2b.dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.InstanceServiceIdsEntryR\x12instanceServiceIds\x1a=\n" +
	"\x0fServiceIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10ServiceArnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17InstanceServiceIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xff\x02\n" +
	"1com.dev.planton.aws.awscloudmapnamespace.v1alpha1B\fOutputsProtoP\x01Zcgithub.com/plantonhq/planton/catalog/aws/awscloudmapnamespace/v1alpha1;awscloudmapnamespacev1alpha1\xa2\x02\x04DPAA\xaa\x02-Dev.Planton.Aws.Awscloudmapnamespace.V1alpha1\xca\x02-Dev\\Planton\\Aws\\Awscloudmapnamespace\\V1alpha1\xe2\x029Dev\\Planton\\Aws\\Awscloudmapnamespace\\V1alpha1\\GPBMetadata\xea\x021Dev::Planton::Aws::Awscloudmapnamespace::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_goTypes = []any{
	(*AwsCloudMapNamespaceOutputs)(nil), // 0: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs
	nil,                                 // 1: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.ServiceIdsEntry
	nil,                                 // 2: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.ServiceArnsEntry
	nil,                                 // 3: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.InstanceServiceIdsEntry
}
var file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_depIdxs = []int32{
	1, // 0: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.service_ids:type_name -> dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.ServiceIdsEntry
	2, // 1: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.service_arns:type_name -> dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.ServiceArnsEntry
	3, // 2: dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.instance_service_ids:type_name -> dev.planton.aws.awscloudmapnamespace.v1alpha1.AwsCloudMapNamespaceOutputs.InstanceServiceIdsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_init() }
func file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_init() {
	if File_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDesc), len(file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto = out.File
	file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_aws_awscloudmapnamespace_v1alpha1_outputs_proto_depIdxs = nil
}
