syntax = "proto3";

package dev.planton.aws.awssagemakerfeaturegroup.v1alpha1;

import "catalog/aws/awssagemakerfeaturegroup/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsSagemakerFeatureGroupIacInput is the input for the IaC modules
// that deploy the feature group.
message AwsSagemakerFeatureGroupIacInput {
  // target is the AwsSagemakerFeatureGroup resource to deploy.
  AwsSagemakerFeatureGroup target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
