syntax = "proto3";

package dev.planton.azure.azureeventhubschemagroup.v1alpha1;

import "catalog/azure/azureeventhubschemagroup/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureEventHubSchemaGroupIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureEventHubSchemaGroupIacInput {
  // target infra-component to be deployed
  AzureEventHubSchemaGroup target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
