// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azureplantonrunner/v1alpha1/outputs.proto

package azureplantonrunnerv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzurePlantonRunnerOutputs captures the observable identifiers of a
// deployed runner appliance -- the handles for day-2 operations: finding
// the app in Azure tooling and the name the runner registered itself
// under with the control plane.
type AzurePlantonRunnerOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Azure resource ID of the Container App keeping the runner
	// running. The primary handle for inspecting the appliance with Azure
	// tooling.
	ContainerAppId string `protobuf:"bytes,1,opt,name=container_app_id,json=containerAppId,proto3" json:"container_app_id,omitempty"`
	// The Container App's name (metadata.name).
	ContainerAppName string `protobuf:"bytes,2,opt,name=container_app_name,json=containerAppName,proto3" json:"container_app_name,omitempty"`
	// The name of the Container App secret holding the runner token. The
	// container reads PLANTON_RUNNER_TOKEN from this secret; the token
	// authorizes joining and is never the runner's identity.
	TokenSecretName string `protobuf:"bytes,3,opt,name=token_secret_name,json=tokenSecretName,proto3" json:"token_secret_name,omitempty"`
	// The name the runner registers itself under with the control plane --
	// the value shown by `planton runner list` the moment it joins.
	RunnerName string `protobuf:"bytes,4,opt,name=runner_name,json=runnerName,proto3" json:"runner_name,omitempty"`
	// The resource group the runner was deployed in. Echoed so downstream
	// tooling and verifiers can target the correct group.
	ResourceGroupName string `protobuf:"bytes,5,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AzurePlantonRunnerOutputs) Reset() {
	*x = AzurePlantonRunnerOutputs{}
	mi := &file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzurePlantonRunnerOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzurePlantonRunnerOutputs) ProtoMessage() {}

func (x *AzurePlantonRunnerOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzurePlantonRunnerOutputs.ProtoReflect.Descriptor instead.
func (*AzurePlantonRunnerOutputs) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *AzurePlantonRunnerOutputs) GetContainerAppId() string {
	if x != nil {
		return x.ContainerAppId
	}
	return ""
}

func (x *AzurePlantonRunnerOutputs) GetContainerAppName() string {
	if x != nil {
		return x.ContainerAppName
	}
	return ""
}

func (x *AzurePlantonRunnerOutputs) GetTokenSecretName() string {
	if x != nil {
		return x.TokenSecretName
	}
	return ""
}

func (x *AzurePlantonRunnerOutputs) GetRunnerName() string {
	if x != nil {
		return x.RunnerName
	}
	return ""
}

func (x *AzurePlantonRunnerOutputs) GetResourceGroupName() string {
	if x != nil {
		return x.ResourceGroupName
	}
	return ""
}

var File_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto protoreflect.FileDescriptor

const file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDesc = "" +
	"\n" +
	"7catalog/azure/azureplantonrunner/v1alpha1/outputs.proto\x12-dev.planton.azure.azureplantonrunner.v1alpha1\"\xf0\x01\n" +
	"\x19AzurePlantonRunnerOutputs\x12(\n" +
	"\x10container_app_id\x18\x01 \x01(\tR\x0econtainerAppId\x12,\n" +
	"\x12container_app_name\x18\x02 \x01(\tR\x10containerAppName\x12*\n" +
	"\x11token_secret_name\x18\x03 \x01(\tR\x0ftokenSecretName\x12\x1f\n" +
	"\vrunner_name\x18\x04 \x01(\tR\n" +
	"runnerName\x12.\n" +
	"\x13resource_group_name\x18\x05 \x01(\tR\x11resourceGroupNameB\xfd\x02\n" +
	"1com.dev.planton.azure.azureplantonrunner.v1alpha1B\fOutputsProtoP\x01Zagithub.com/plantonhq/planton/catalog/azure/azureplantonrunner/v1alpha1;azureplantonrunnerv1alpha1\xa2\x02\x04DPAA\xaa\x02-Dev.Planton.Azure.Azureplantonrunner.V1alpha1\xca\x02-Dev\\Planton\\Azure\\Azureplantonrunner\\V1alpha1\xe2\x029Dev\\Planton\\Azure\\Azureplantonrunner\\V1alpha1\\GPBMetadata\xea\x021Dev::Planton::Azure::Azureplantonrunner::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescOnce sync.Once
	file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescData []byte
)

func file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescGZIP() []byte {
	file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDesc), len(file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDesc)))
	})
	return file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDescData
}

var file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_goTypes = []any{
	(*AzurePlantonRunnerOutputs)(nil), // 0: dev.planton.azure.azureplantonrunner.v1alpha1.AzurePlantonRunnerOutputs
}
var file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_init() }
func file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_init() {
	if File_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDesc), len(file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_depIdxs,
		MessageInfos:      file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_msgTypes,
	}.Build()
	File_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto = out.File
	file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_goTypes = nil
	file_catalog_azure_azureplantonrunner_v1alpha1_outputs_proto_depIdxs = nil
}
