apiVersion: oci.openmcf.org/v1
kind: OciNetworkSecurityGroup
metadata:
  name: my-dev-nsg
spec:
  compartmentId:
    value: <compartment-ocid>
  vcnId:
    value: <vcn-ocid>
  displayName: dev-nsg
  ingressRules:
    - source: 0.0.0.0/0
      sourceType: cidr_block
      protocol: all
      description: Allow all inbound traffic
  egressRules:
    - destination: 0.0.0.0/0
      destinationType: cidr_block
      protocol: all
      description: Allow all outbound traffic
