syntax = "proto3";

package dev.planton.aws.awsmwaaenvironment.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/aws/awsmwaaenvironment/v1alpha1/outputs.proto";
import "catalog/aws/awsmwaaenvironment/v1alpha1/spec.proto";
import "shared/metadata.proto";

// aws-mwaa-environment
message AwsMwaaEnvironment {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'aws.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AwsMwaaEnvironment'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  AwsMwaaEnvironmentSpec spec = 4 [(buf.validate.field).required = true];

  //status
  AwsMwaaEnvironmentStatus status = 5;
}

// aws-mwaa-environment status
message AwsMwaaEnvironmentStatus {
  //outputs
  AwsMwaaEnvironmentOutputs outputs = 1;
}
