syntax = "proto3";

package dev.planton.kubernetes.kuberneteskubeprometheusstack.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/kubernetes/kuberneteskubeprometheusstack/v1alpha1/outputs.proto";
import "catalog/kubernetes/kuberneteskubeprometheusstack/v1alpha1/spec.proto";
import "shared/metadata.proto";

//kube-prometheus-stack-kubernetes
message KubernetesKubePrometheusStack {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'kubernetes.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'KubernetesKubePrometheusStack'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  KubernetesKubePrometheusStackSpec spec = 4 [(buf.validate.field).required = true];

  //status
  KubernetesKubePrometheusStackStatus status = 5;
}

//kube-prometheus-stack-kubernetes status.
message KubernetesKubePrometheusStackStatus {
  //outputs
  KubernetesKubePrometheusStackOutputs outputs = 1;
}
