syntax = "proto3";

package dev.planton.gcp.gcpprivatecacertificatetemplate.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/gcp/gcpprivatecacertificatetemplate/v1alpha1/outputs.proto";
import "catalog/gcp/gcpprivatecacertificatetemplate/v1alpha1/spec.proto";
import "shared/metadata.proto";

//GcpPrivateCaCertificateTemplate
message GcpPrivateCaCertificateTemplate {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'GcpPrivateCaCertificateTemplate'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  GcpPrivateCaCertificateTemplateSpec spec = 4 [(buf.validate.field).required = true];

  //status
  GcpPrivateCaCertificateTemplateStatus status = 5;
}

//GcpPrivateCaCertificateTemplate status
message GcpPrivateCaCertificateTemplateStatus {
  //stack-outputs
  GcpPrivateCaCertificateTemplateStackOutputs outputs = 1;
}
