.PHONY: preview
preview:
	openmcf pulumi preview --manifest $(manifest)

.PHONY: up
up:
	openmcf pulumi up --manifest $(manifest)

.PHONY: down
down:
	openmcf pulumi down --manifest $(manifest)

.PHONY: refresh
refresh:
	openmcf pulumi refresh --manifest $(manifest)
