syntax = "proto3";

package dev.planton.aws.awsbackupsettings.v1alpha1;

import "catalog/aws/awsbackupsettings/v1alpha1/api.proto";
import "catalog/aws/provider.proto";

// AwsBackupSettingsIacInput is the input for the IaC modules that
// manage AWS Backup account/region settings.
message AwsBackupSettingsIacInput {
  // target is the AwsBackupSettings resource to deploy.
  AwsBackupSettings target = 1;
  // provider_config contains the AWS provider credentials and configuration.
  dev.planton.aws.AwsProviderConfig provider_config = 2;
}
