apiVersion: kubernetes.openmcf.org/v1
kind: KubernetesGrpcRoute
metadata:
  name: my-grpc-route
spec:
  namespace:
    value: app-ns
  parentRefs:
    - name: <gateway-name>
  hostnames:
    - <api-hostname>
  rules:
    - matches:
        - method:
            service: <grpc-service>
      backendRefs:
        - name: <service-name>
          port: 9000
