load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gcpwebidentity",
    srcs = ["exchange.go"],
    importpath = "github.com/plantonhq/planton/pkg/iac/provider/gcp/gcpwebidentity",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/gcp",
        "@com_github_pkg_errors//:errors",
        "@org_golang_x_oauth2//google/externalaccount",
    ],
)

go_test(
    name = "gcpwebidentity_test",
    srcs = ["exchange_test.go"],
    embed = [":gcpwebidentity"],
    deps = [
        "//catalog/gcp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
