syntax = "proto3";

package dev.planton.digitalocean.digitaloceanfirewall.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceanfirewall/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceanfirewall/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-firewall
message DigitalOceanFirewall {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'digital-ocean.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'DigitalOceanFirewall'];

  //metadata
  dev.planton.shared.CatalogObjectMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanFirewallSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanFirewallStatus status = 5;
}

// digital-ocean-firewall status
message DigitalOceanFirewallStatus {
  //outputs
  //  digital-ocean-firewall outputs
  DigitalOceanFirewallOutputs outputs = 1;
}
