syntax = "proto3";

package dev.planton.cloudflare.cloudflarezerotrustgatewaypolicy.v1alpha1;

import "catalog/cloudflare/cloudflarezerotrustgatewaypolicy/v1alpha1/api.proto";
import "catalog/cloudflare/provider.proto";

// CloudflareZeroTrustGatewayPolicyIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message CloudflareZeroTrustGatewayPolicyIacInput {
  // the catalog object to deploy to be deployed
  CloudflareZeroTrustGatewayPolicy target = 1;
  // provider-config for Cloudflare authentication
  dev.planton.cloudflare.CloudflareProviderConfig provider_config = 2;
}
