syntax = "proto3";

package dev.planton.kubernetes.kubernetesrequestauthentication.v1alpha1;

import "catalog/kubernetes/kubernetesrequestauthentication/v1alpha1/api.proto";
import "catalog/kubernetes/provider.proto";

// KubernetesRequestAuthenticationIacInput provides the inputs for creating the
// RequestAuthentication on a Kubernetes cluster.
message KubernetesRequestAuthenticationIacInput {
  // target infra-component
  KubernetesRequestAuthentication target = 1;
  // provider-config
  dev.planton.kubernetes.KubernetesProviderConfig provider_config = 2;
}
