syntax = "proto3";

package dev.planton.azure.azureroledefinition.v1alpha1;

import "catalog/azure/azureroledefinition/v1alpha1/api.proto";
import "catalog/azure/provider.proto";

// AzureRoleDefinitionIacInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureRoleDefinitionIacInput {
  // the catalog object to deploy to be deployed
  AzureRoleDefinition target = 1;
  // provider-config for Azure authentication
  dev.planton.azure.AzureProviderConfig provider_config = 2;
}
