apiVersion: gcp.planton.dev/v1alpha1
kind: GcpHaVpnConnection
metadata:
  name: hq
spec:
  gateway:
    valueFrom:
      kind: GcpHaVpnGateway
      name: hub-vpn
      fieldPath: status.outputs.gateway_self_link
  router:
    valueFrom:
      kind: GcpHaVpnGateway
      name: hub-vpn
      fieldPath: status.outputs.router_name
  region:
    valueFrom:
      kind: GcpHaVpnGateway
      name: hub-vpn
      fieldPath: status.outputs.region
  peer:
    externalGateway:
      redundancyType: TWO_IPS_REDUNDANCY
      description: HQ firewall pair
      interfaces:
        - id: 0
          ipAddress: 203.0.113.10
        - id: 1
          ipAddress: 203.0.113.11
  tunnels:
    - name: hq-tunnel-0
      vpnGatewayInterface: 0
      peerExternalGatewayInterface: 0
      sharedSecret: ${secrets-group.hq-vpn.psk-0}
      bgpSession:
        interfaceIpRange: 169.254.10.1/30
        peerAsn: 65001
        bfd:
          sessionInitializationMode: ACTIVE
    - name: hq-tunnel-1
      vpnGatewayInterface: 1
      peerExternalGatewayInterface: 1
      sharedSecret: ${secrets-group.hq-vpn.psk-1}
      bgpSession:
        interfaceIpRange: 169.254.11.1/30
        peerAsn: 65001
        bfd:
          sessionInitializationMode: ACTIVE
  deletionPolicy: PREVENT
