apiVersion: oci.planton.dev/v1
kind: OciVcn
metadata:
  name: my-dev-vcn
spec:
  compartmentId:
    value: <compartment-ocid>
  cidrBlocks:
    - 10.0.0.0/16
  displayName: dev-vcn
  dnsLabel: devvcn
  isIpv6Enabled: false
  isInternetGatewayEnabled: true # Basic internet connectivity for dev workloads
  isNatGatewayEnabled: false # Omitted to avoid hourly charges
  isServiceGatewayEnabled: false # Omitted to avoid hourly charges
