apiVersion: kubernetes.openmcf.org/v1
kind: KubernetesPostgres
metadata:
  name: my-postgres
spec:
  namespace:
    value: "<your-namespace>"
  createNamespace: false
  container:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    diskSize: 10Gi
